.gitignore

It's customary to have a .gitignore file that will ignore all temporary/final output ot the build process so "git status" gives a cleaned-up version of what kind of changes are still pending a commit to the repo.

Add .gitingore file to have clean 'git status' output

---

lib/core/src/unix/net_lib.c

When we call accept() on a listening socket, we need to inherit
the sctp PPID from the master socket to the new socket of the
just-accepted connection.  Otherwise any sent packets (such as S1AP)
will be sent to PPID=0 rather than the configured PPID (e.g. 18 for
S1AP).

net_accept(): Inherit PPID from listening socket

---

lib/freeDiameter-1.2.1/libfdcore/endpoints.c

There's an odd restriciton in freediameter that makes it silently ignore any "ListenOn" addresses that are either loopback, link-local or site-local.  I don't see a reason why those should be ignored.  In testing and/or private LTE installations, this seems perfectly legal.

Allow loopback/link-local/site-local addresses

---

src/mme/emm_handler.c
src/mme/mme_context.c
src/mme/mme_context.h
support/config/mme.conf.in

Hello, 
Firstly congratulations for your project, it is very useful LTE EPC software.
I made a little change in these source files, that will provide a config option to change the Network name that will be show in the UE instead of the MNC + MCC code.
With this we need add these option in mme.conf file:
network_name:
full: NextEPC
short: NEPC
In attached you can found a photo showing the Network name in the UE.
Thanks
R.Medeiros

Network Name

---

lib/nas/support/nas_message.py

Files are not generated by gtpv2c_tlv.py but by nas_message.py

nas_message.py: Fix copy+paste error

---

src/pgw/pgw_context.c

Hello,
I made some changes to increase the log information file from PGW, now it's saving information about what IMSI get the address.
Now, when an user connect the information about it is saved in the log:
05/02 12:53:19.082: [pgw] INFO: UE IMSI:[724120000000001] APN:[internet] IPv4:[192.168.0.2] IPv6:[2001:db8:cofe::2] (pgw_context.c:922).
Thanks 
Romeu Medeiros

Change in the Log about the address use for the UE.

---

lib/asn1c/Makefile.am
lib/base/Makefile.am
lib/fd/Makefile.am
lib/freeDiameter-1.2.1/libfdcore/sctp.c
lib/gtp/Makefile.am
lib/nas/Makefile.am
src/Makefile.am
src/app/Makefile.am

The fallback to the old SCTP API must be made if either SCTP_SEND_FAILED_EVENT
or SCTP_NOTIFICATIONS_STOPPED_EVENT are undeclared.
This fixes building nextepc on e.g. Debian unstable.
Closes: #208

freeDiameter: Fix compilation on Linux without SCTP_SEND_FAILED_EVENT

---

support/freeDiameter/hss.conf.in
support/freeDiameter/mme.conf.in
support/freeDiameter/pcrf.conf.in
support/freeDiameter/pgw.conf.in

The existing freeDiameter default config files for HSS, MME, PCRF and PGW
disabled SCTP and enabled TCP.  This is not in compliance with
3GPP TS 29.272 secition 7.1.5 which clearly states:
"Diameter messages over the S6a, S6d, S13 and S13' interfaces shall
make use of SCTP IETF RFC 4960 [14]"

freeDiameter: Use SCTP-only by default, not TCP-only

---

src/mme/mme-fd-path.c

The check for whether the AVP exists in the ULA was wrong, resulting in
the MME refusing to proceed without this AVP.  However, it is not a
mandatory AVP.

mme: Fix ULA without Subscribed-RAU-TAU-Timer

---

src/mme/s1ap-conv.c
tests/unit/crash-test.c

The aper_encode function returns the number of encoded bits and when
converting to bytes we should round up or use the ((.encoded + 7) / 8)
formula as described in per_encoder.h
Fixes: #257

Fix buffer length calculation in s1ap_copy_ie

---

meson.build

The default prefix for the package installation was set to /usr, which I truly found quite strange, given that normally every package build from source defaults to /usr/local instead. IMHO, using the default /usr/local is much more common and standard and what a user would expect. Especially since setting only the prefix to /usr would end up setting sysconfdir to /usr/etc and that is incredibly confusing :D
A default meson configuration would end up giving:
```
$ meson build
Message: 
prefix:                       /usr/local
libdir:                       /usr/local/lib/x86_64-linux-gnu
bindir:                       /usr/local/bin
sysconfdir:                   /usr/local/etc
localstatedir:                /usr/local/var
source code location:         /home/aleksander/nextepc
compiler: …
```

Build system updates

---

.gitignore
misc/mac/setup.sh
webui/.gitignore

- I wrote a handy helper script when I moved my development environment to Mac. Hoping to see if someone else might also find this useful.
- Added `.gitignore` to the project so that the `build/` directory is not committed to git by error from future contributors.
Signed-off-by: Sudheesh Singanamalla <sudheesh@cs.washington.edu>

Prepares an easy install script for mac builds and initializes gitignore

---

webui/src/components/Profile/Edit.js
webui/src/components/Subscriber/Edit.js
webui/src/components/Subscriber/View.js

I am working on supporting different PDN types and realized we need this feature in the WebUI. Right now it functionally works, but has two small problems. First, the selection bar has a blank option above IPv4. Second, I think the bar is too big and makes more sense to put it on the line above. @acetcom if you have a moment to help on this, I couldn't figure out how to make node do what I want, but I think you're more familiar with this code base than I am :-).

add an option for PDN Type (IPv4, IPv6, IPv4v6) to webui

---

src/mme/esm-build.c

If a UE requests PDN Type IPv4v6 but is assigned IPv4 or IPv6 only by the HSS, we need to include an appropriate ESM Error Cause message. Otherwise, the UE will complain and request additional APNs (e.g. UE requests type IPv4v6, is assigned IPv4, then issues a second request for IPv6). The second APN request currently crashes the MME; the correct fix to this problem is here.

send PDN error cause if needed

---

src/sgw/sgw-context.c
src/sgw/sgw-context.h
src/sgw/sgw-gtp-path.c
src/sgw/sgw-s5c-handler.c

This feature is useful in scenarios where SGW is run inside a container or openstack vm i.e. behind 1-to-1 mapping NAT. In docker/openstack environment, we often have 1-to-1 mapped NAT IP address in order for eNB to reach SGW. But, this 1-to-1 mapping NAT IP address is not seen on SGW host and hence non UDP socket bindable. Since SGW can only bind to IP address visible in it's host (usually a private IP beind a NAT), it advertises the same to UE in S1AP message resulting in eNB not able to reach SGW on Uplink. This commit solves this issue by providing a means to advertise a different IP address than the one SGW UDP socket is bound to.
Example of sgw.yaml to use this feature:
<pre>
logger:
file: /root/open5gs/install/var/log/open5gs/sgw.log
level: debug
parameter:
no_ipv6: true
sgw:
gtpc: …

Add feature to provide custom SGW GTP-U (S1) address to be advertised inside S1AP messages

---

configs/systemd/open5gs-pgwd.service.in

PGW must "Require" systemd-networkd  for apt-get installation of open5gs. This makes sense (because PGW depends on systemd-networkd to configure the ogstun interface) but also fixes an important bug.
Default install of open5gs starts all the services running. If the PGW is running and you then type "systemctl restart systemd-networkd", the PGW will stay running, and this will allow systemd-networkd to stop, but will then prevent systemd-networkd from restarting. This has massive consequences for network configuration in Debian 10/Ubuntu 1804 (it disables DNS resolution)
Correct behavior should be to (1) restart the PGW when you restart systemd-networkd and (2) much more importantly, ensure that systemd-networkd can safely restart after a default open5gs install.

PGW service must depend on systemd-networkd

---

configs/csfb.yaml.in
configs/installed.yaml.in
configs/mnc3.yaml.in
configs/open5gs/pgw.yaml.in
configs/simple.yaml.in
configs/split.yaml.in
configs/srslte.yaml.in
configs/systemd/99-open5gs.network
configs/volte.yaml.in
docker/build/setup.sh
docker/centos/8/dev/setup.sh
docker/fedora/30/dev/setup.sh
docker/ubuntu/bionic/dev/setup.sh
docs/_docs/guide/01-quickstart.md
docs/_docs/guide/02-building-open5gs-from-sources.md
docs/_docs/guide/04-troubleshooting.md
docs/_docs/platform/01-debian-ubuntu.md
docs/_docs/platform/02-centos.md
docs/_docs/platform/03-fedora.md
docs/_docs/platform/05-macosx.md
docs/_docs/tutorial/01-your-first-lte.md
docs/_pages/faq.md
misc/ipv6_netconf.sh
misc/netconf.sh
src/pgw/pgw-gtp-path.c
tests/mnc3/mnc3-test.c
tests/simple/attach-test.c
tests/simple/volte-test.c
tests/volte/volte-test.c

Hi @acetcom!
This PR changes the default UE address subnet from 45.45.0.0/16 to 10.45.0.0/16. I read the discussion in #41 and think this change should be made, I also wanted to address some concerns in that thread:
- You are correct that almost all mobile network operators use NAT, to my understanding. Acceptable subnets for NAT would be 10.0.0.0/8, 172.16.0.0/20, or 192.168.0.0/24. 
- You're correct that someone can always change these values, but I do believe that the default values that work out of the box should definitely be a private IP address range. This is standard and correct practice; assigning public IP addresses you don't own should be strongly avoided.
- As someone mentioned in the comments, 45.45.0.0/16 are generally owned by Canadian networks. This means that default …

change default subnet from 45.45.0.0 to 10.45.0.0

---

debian/control

meson seems to need the 'git' program available at build time:
lib/diameter/common/meson.build:36:0: ERROR: Git program not found.
Closes: #372

debian/control: Add build dependency to 'git'

---

src/pgw/pgw-context.c
src/pgw/pgw-context.h
src/pgw/pgw-s5c-build.c

This feature can be used for provisioning a limit on the size of the packets
sent by the MS to avoid packet fragmentation in the backbone network between
the MS and the GGSN/PGW and/or across the (S)Gi reference point) when some
of the backbone links does not support packets larger then 1500 octets
(ETSI TS 123 060 V15.5.0 Annex C)
Example of pgw.yaml to use this feature:
<pre>
logger:
file: @localstatedir@/log/open5gs/pgw.log
parameter:
pgw:
freeDiameter: @sysconfdir@/freeDiameter/pgw.conf
gtpc:
- addr: 127.0.0.3
- addr: ::1
gtpu:
- addr: 127.0.0.3
- addr: ::1
ue_pool:
- addr: 10.45.0.1/16
- addr: cafe::1/64
dns:
- 8.8.8.8
- 8.8.4.4
- 2001:4860:4860::8888
- 2001:4860:4860::8844
mtu: 1400
</pre>

Add feature to provide MTU size to be advertised in PCO options

---

configs/systemd/open5gs-hssd.service.in
configs/systemd/open5gs-pcrfd.service.in

I'm not sure how to properly fix this, as Debian Buster (10) and onward dropped the mongodb package. MongoDB Community Version is being recommended, but the systemd daemon service name also changed from mongodb.service to mongod.service in MongoDB Community Version (mongodb-org packages).

Make it installable in Debian Buster with MongoDB-ORG packages.

---

configs/meson.build
debian/open5gs-hss.install

I like using apt-get to install open5gs, and recommend this approach to others, except it does not come with the database tool that I wrote (which I also recommend people use as a quick-start). I modified /configs/meson.build to copy dbconf.sh into /build/configs/open5gs_db, and modified debian/open5gs-hss.install to install it to /usr/bin/open5gs_db as a part of the HSS package. Feel free to change the names or locations, figured it made the most sense to pair it with the HSS.

Add dbconf to hss Debian package

---

src/mme/esm-build.c

I am extending this work to handle properly the forcing of PDN connect based on the selection in WebUI. Previously, even though IPv4 or IPv6 was selected in Web UI only the ESM Cause was populated but still the IPv6 was sent even though IPv4 was force in Web UI (IPv4v6 Attach requested scenario) and vice-versa. But, the right way to do it was to send only the IPv4/IPv6 if IPv4/IPv6 is selected in Web UI (IPv4v6 Attach requested scenario).
I have also handled scenarios where UE requests for IPv4 and only IPv6 is selected in UI and vice-versa.
https://www.sharetechnote.com/html/Handbook_LTE_ESM_Cause_50_51_52.html

Handle forcing of IPv4 or IPv6 PDN connect using the Web UI

---

src/mme/mme-context.c
src/mme/mme-context.h
src/mme/mme-sm.c
src/mme/s1ap-handler.c

Closes #421 
Instead of crash `open5gs-mme` it will respond with S1 Setup Failure when maximum number of eNBs is reached.
In this PR `mme_enb_t` pool has been deleted. IMHO, to have a pool with the size of the configuration and taking account the current architecture, it would be more complex to send a S1 Setup Failure when it's reached. (the eNB instance is created on SCTP accept)
The S1 Setup Failure response is as follows:
```
S1 Application Protocol
S1AP-PDU: unsuccessfulOutcome (2)
unsuccessfulOutcome
procedureCode: id-S1Setup (17)
criticality: reject (0)
value
S1SetupFailure
protocolIEs: 2 items
Item 0: id-Cause
ProtocolIE-Field
id: id-Cause (2)
criticality: ignore (1)
value
Cause: misc (4)
misc: unspecified (4)
Item 1: id-TimeToWait
ProtocolIE-Field
id: id-TimeToWait (65) …
```

Fix MME crash on eNB connection when maximum number of eNBs reached

---

src/mme/mme-s11-handler.c
src/pgw/pgw-s5c-build.c

This patch handles the modification made by PCRF to the Bearer level QoS and AMBR

Add the modified Bearer level QoS if PCRF changes them

---

docs/_docs/tutorial/02-VoLTE-setup.md

Following points address the changes made to tutorial
1. Don't run the P-CSCF, I-CSCF and S-CSCF as systemctl process (not so friendly for debugging and not so friendly to docker environment as well) 
2. Run all the IMS process in foreground for better debugging
3. Run all the IMS process (or atleast P-CSCF) in foreground as ROOT user and NOT SUDO - Handles non-creation of IPSec tunnel issue
Sorry for this over and over changes. But i was running under ROOT user and not SUDO user so didn't face this issue.

Update of VoLTE tutorial

---

configs/open5gs/mme.yaml.in
configs/open5gs/smf.yaml.in
lib/core/ogs-3gpp-types.h
lib/pfcp/context.c
lib/pfcp/context.h
src/mme/mme-context.c
src/mme/mme-context.h
src/smf/context.c
src/smf/context.h

MME: select SGW by RR,TAC,ENB_ID
and enable round robin inside each option
SMF: select PFCP associated UPF by RR,TAC,APN,ENB_ID
and enable round robin inside each option
Reworked due to code base having changed quite a lot
@acetcom - should the UPF selection logic apply to both these functions? If so I can duplicate
add session by APN - [``smf_sess_add_by_apn``](https://github.com/open5gs/open5gs/blob/master/src/smf/context.c#L601) << code currently in here
add session by PSI - [``smf_sess_add_by_psi``](https://github.com/open5gs/open5gs/blob/master/src/smf/context.c#L857)
Should add, this has been tested and confirmed working (with srsENB and UEs etc..)

MME: select SGW by RR,TAC,ENB_ID ||  SMF: select PFCP associated UPF by RR,TAC,APN,ENB_ID (re-worked)

---

lib/sbi/server.c

Unfortunately upstream microhttpd has changed their callback function
prototypes in an API-incompatible way.  At least if you build with
-Werror, gcc will fail due to non-matching prototypes.
Work around this by using a typedef which uses the proper return type
depending on the microhttpd version used.
Closes: #497

fix compilation warnings/errrors with microhttpd >= v0.97.1

---

src/sgwc/context.c
src/smf/context.c

Previously, after searching for a SGWU/UPF designed to serve a particular TAC/APN/cell_ID and not finding a node that was suitable, SGWC and SMF would run this line to select a node in round robin fashion:
```
return next ? next : ogs_list_first(&ogs_pfcp_self()->peer_list);
```
However this did not check that node `next` was PFCP associated. 
https://github.com/open5gs/open5gs/issues/555
The code now runs as follows:
- search for matching SGWU/UPF nodes as before
- if none are found, enter RR mode
- in RR mode, find next PFCP associated node in list and use it
- if there are no PFCP associated nodes, print error message (and select first from list)

Fix for SGWC and SMF round robin selection

---

configs/open5gs/sgwc.yaml.in
configs/open5gs/smf.yaml.in
lib/pfcp/context.c
lib/pfcp/context.h
src/sgwc/context.c
src/smf/context.c

Hey @acetcom - another one for you!
The first commit deals with the first point in https://github.com/open5gs/open5gs/issues/559, flipping the search order from TAC/APN/cell_ID to APN/ cell_ID/ TAC
This means the logic for (eg) the SMF is now:
1. Search through node list to see if any are dedicated to support the APN
-- round robin between nodes that support the APN && are PFCP associated
-- if there are none, move to 2
2. Search through node list to see if any are dedicated to support the e_cell_ID
-- round robin between nodes that support the e_cell_ID && are PFCP associated
-- if there are none, move to 3
3. Search through node list to see if any are dedicated to support the nr_cell_ID
-- round robin between nodes that support the nr_cell_ID && are PFCP associated
-- if there are none, …

Change PFCP node search order, fix typo, add feature to disable RR for a node

---

docs/_docs/tutorial/02-VoLTE-setup.md

1. Remove NAT rules for the tun interface used for IMS (NATing in IMS does not work)
2. Update the APN configuration to force usage of IPv4
3. Point FHoSS repo to https://github.com/herlesupreeth/FHoSS
4. Add a note related to open5gs configuration files used for reference

Update VoLTE tutorial

---

lib/pfcp/context.c
lib/pfcp/context.h

Hey @acetcom 
I noticed a couple of typos in the PFCP context files for SMF>UPF selection based  on the `nr_cell_id`
As this is a 36 bit long number, the config file needs to be parsed with `ogs_uint36_from_string` and held in a `uint64`
Kenny

Fix for SMF nr_cell_id selection

---

webui/server/index.js

In order to access the webui from other hosts make it listen on the any address. 
Should be safe as we have user authentication and the default password could be changed.

make webui listen on 0.0.0.0

---

src/hss/hss-fd-path.c
src/mme/mme-fd-path.c
src/pcrf/pcrf-fd-path.c

- Advertises Gx and Rx for PCRF
- Advertises S6A for HSS and MME

Add Vendor-Specific-Application-Id in CER for advertising the diameter applications supported

---

docs/_docs/hardware/01-genodebs.md
docs/_pages/docs.md

Created pages documenting Radio hardware people in the community have used with Open5GS, as per suggestion in Discord chat.
- Created new folder in docs for Hardware
- Added file containing list of eNodeBs / gNodeBs confirmed to work by the community
- Linked to a post on CSFB Setup with Osmocom GSM stack on docs page
- Linked to a post on SMS over SGs with Osmocom GSM stack on docs page
- Linked to e/gNodeB list from main docs page

Doc Update - Added list of eNodeBs / gNodeBs confirmed to work by community, links to CSFB & SMS Docs

---

docs/_docs/hardware/01-genodebs.md

Hello, Open5GS Support Teams,
Here is Intelligent Mobile Associate Community (IMAC)  Teams department of Taiwan's National Taichung University of Science and Technology Computer Science and Information Engineering.
We test the Open5GS on Monolithic Architecture with Taiwan's Gemtek 4G Small Cell,
and it support Open5GS's MME Element communication and help UE connect to Internet,
So we add it to Open5GS's eNodeBs/gNodeBs support list, and provided we used software version
Signed-off-by: ZhengSheng <j13tw@yahoo.com.tw>

NUTC-IMAC_Add Gemtek 4G small cell to eNodeB/gNodeB support list

---

lib/asn1c/common/constr_TYPE.h

There is a small typo in lib/asn1c/common/constr_TYPE.h.
Should read `specific` rather than `speciic`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, speciic -> specific

---

lib/pfcp/handler.c

func: ogs_pfcp_handle_create_pdr, repeated ogs_pfcp_qer_find_or_add
```
if (message->qer_id.presence) {
qer = ogs_pfcp_qer_find_or_add(sess, message->qer_id.u32);
ogs_assert(qer);
ogs_pfcp_pdr_associate_qer(pdr, qer);
}
if (message->qer_id.presence) {
qer = ogs_pfcp_qer_find_or_add(sess, message->qer_id.u32);
ogs_assert(qer);
ogs_pfcp_pdr_associate_qer(pdr, qer);
}
```

remove repeated qer in handling create pdr

---

configs/open5gs/pcrf.yaml.in
lib/app/ogs-context.c
lib/app/ogs-context.h
src/pcrf/pcrf-rx-path.c

IE (IPV4-local-addr field ) is not supported on the LTE pre release-11 UEs, resulting in failure in establishing a VoLTE call in those devices. In order for the call to work the local address in packet filter must be replaced by any.

Legacy support for pre-release LTE 11 devices while performing VoLTE call

---

lib/sbi/message.c
lib/sbi/message.h
src/udm/nudr-build.c
src/udm/nudr-handler.c
src/udr/nudr-handler.c

As TS29.505  5.2.4 SmfSelectionSubscriptionData said:
{apiRoot}/nudr-dr/<apiVersion>/subscription-data/{ueId}/{servingPlmnId}/provisioned-data/smf-selection-subscription-data
UDM:  smf-select-data
UDR:  smf-selection-subscription-data

modify udr smf selection subscription data

---

src/amf/ngap-build.c
src/amf/ngap-handler.c

ngap-build.c file:  ngap_build_handover_command,
```
ogs_debug("Handover request");
```
ngap-handler.c:  ngap_handle_uplink_ran_status_transfer
```
ogs_debug("Handover notify");
```

modify handover request and uplink ran status transfer debug info

---

lib/dbi/ogs-mongoc.c
lib/dbi/ogs-mongoc.h

When using credentials to connect to MongoDB, the credentials are leaked through the logs. This will mask the username and password in the logs if they're present.

mask mongo credentials when logging

---

src/amf/amf-sm.c
src/amf/ngap-sctp.c

Hey Sukchan
I noticed some of the AMF's log messages were referring to "S1" and "N1" for NGAP chatter. I think these should all be "N2"? Did a search and think I've got them all.
Cheers
Kenny

NGAP - N2 path name

---

misc/db/python/README.md
misc/db/python/SchemaUpdater.py

Updated Readme for Python library to manage Open5Gs to include the new database format,
Created a simple Python script for migrating basic Subscriber data to the new schema
As per discussion in #872

Updated Python Lib docs and script to migrate DB data to new format

---

misc/db/python/Open5GS.py
misc/db/python/README.md
misc/db/python/SchemaUpdater.py
misc/db/python/test_SchemaUpdater.py

This pull request does some cleanup of the initial rough database migration script added by @nickvsnetworking . It also adds a basic test, although I was not sure how to incorporate python unit testing with the existing meson test infrastructure. I tried to keep the commits individually small, so it might be easier to review on a commit by commit basis rather than as a whole PR. I have tested this in my local virtual environment to make sure the daemons don't crash immediately, but have not tested it with an attached RAN.

Some cleanup for the db migration script

---

misc/db/python/SchemaUpdater.py

This pull request updates the python schema update script to specify a default session type when the old session type is not a valid enum for the new session types. This pull request also updates the upgrade script to use the correct units enum to correspond to kbps, matching the expectation from the old UI.

[misc] Use correct units and session types when upgrading

---

lib/core/ogs-macros.h
lib/ipfw/glue.h
lib/ipfw/objs/include_e/netinet/ip_fw.h
lib/sbi/client.c

Alpine Linux is one of the popular container Image's which is widely used. This PR add's support for systems built using musl libc such as Alpine Linux.
To Build on Alpine Linux follow the same process as documented in https://open5gs.org/open5gs/docs/guide/02-building-open5gs-from-sources/ the only change is as Alpine Linux uses `apk` package management tool need to install required tools on alpine Linux as follows.
`sudo apk add  alpine-sdk cmake yaml-dev lksctp-tools-dev mongo-c-driver  
mongo-c-driver-static libgcrypt-dev libidn-dev 
gnutls-dev nghttp2-dev libmicrohttpd-dev curl-dev musl-dev  
linux-headers lksctp-tools bsd-compat-headers git meson flex 
bison make`
Also if you are using Alpine Linux latest-stable (3.13) or > 3.9 you will need to install mangodb from Alpine Linux v3.8 …

Added support for musl libc systems

---

configs/open5gs/pcrf.yaml.in
src/pcrf/pcrf-rx-path.c
src/smf/binding.c
src/smf/context.h

The https://github.com/open5gs/open5gs/commit/6cde7e2eb5cb53e483f559688af8aaae18c39fa6 commit addresses the issue seen when a video call is attempted by IMS registered UEs
Since the precedence in a TFTs under a DNN was set 0 to number of flow rules received via Gx. The UE was requesting deletion of TFTs for the bearer serving the audio (QCI 1) whenever a video call/another dedicated bearer creation under the same DNN was attempted. As per Table 10.5.162/3GPP TS 24.008: Traffic flow template information element, 
> The packet filter evaluation precedence field is used to specify the precedence for the packet filter among all packet filters in all TFTs associated with this PDP address. Higher the value of the packet filter evaluation precedence field, lower the precedence of that packet …

Support for IMS video calling

---

src/smf/binding.c
src/smf/context.c
src/smf/context.h

This commit address the issue where a bearer with particular
PCC rule name exists with TFTs and addtional TFTs needs to be added
to same bearer and DRB lost is reported by UE.
This is achieved by creating EPS Bearer Level Traffic Flow Template
with TFT operation code as 'OGS_GTP_TFT_CODE_ADD_PACKET_FILTERS_TO_EXISTING_TFT' in
above scenario rather than use 'OGS_GTP_TFT_CODE_CREATE_NEW_TFT' at all times.
And, not remove existing packet filters for the bearer.
Attaching the pcap containing the issue, observe that after packet 1883, the RTP packets are flowing over default bearer for IMS signalling
[drb_lost_before_fix.zip](https://github.com/open5gs/open5gs/files/6555182/drb_lost_before_fix.zip)

fix: DRB lost issue when additional TFTs needs to be added to existing bearer with TFTs

---

debian/open5gs-common.install

open5gs-dbctl used to be included with apt packages, but it looks like this was commented out in 9af4268bab01e59ea5ca7a61b0825bd534fb2726 when the DB schema was redesigned. Since then, bf5f64b5e59f5702339103e8b54919f234468023 updated open5gs-dbctl to work with the new schema, but forgot to put it back in the Debian packages. Best I can tell, this fix is good and it appears to work as intended.

add open5gs-dbctl back into apt packages

---

lib/pfcp/rule-match.c

I recently encountered a strange situation where the UPF was given a junk packet and segfaulted. I am still investigating the cause of the junk packet (looks like encapsulation, might have more PRs later) but in the meantime, the segfault was caused at line 198 as a result of calling src_addr[k] when src_addr was never set.
I dont know the exact pfcp logic and am not clear if we should return NULL or OGS_ERROR. This seemed correct but I defer to your wisdom. On a related note, I am assuming/hoping that we should free the packet somewhere else along the line to avoid leaks?

need to return here to prevent segfault

---

lib/diameter/common/init.c

Occasionally, I have seen freeDiameter throw a FD_LOG_FATAL error at the HSS, which is defined to be a serious and unrecoverable error (see https://github.com/Metaswitch/freeDiameter/blob/master/include/freeDiameter/libfdproto.h). I am not sure the exact cause of this error, but I have observed it happening completely unprompted (i.e. not in response to a message from the MME).
When this error happens, freeDiameter essentially shuts down and the HSS is left in a "limbo" where it rejects all connections at the tranport layer (e.g. SCTP Abort or TCP Reset). From this state, the only way to recover appears to be by restarting the HSS.
I am continuing to investigate the true cause of these FD_LOG_FATAL errors. In the meantime, I believe that correct HSS behavior is to purposefully crash …

need to exit (and therefore restart HSS) on FD_LOG_FATAL

---

src/smf/gx-path.c

fix: session data was accessed when NULL resulting in crash

---

lib/pfcp/build.c
lib/pfcp/context.c
lib/pfcp/context.h
lib/pfcp/handler.c
lib/pfcp/message.h
src/smf/gx-path.c

@acetcom I am attaching the trace where I see the issue of stack smashing on SMF along with its logs, please let me know what you think of this fix.
In the trace attached, the UE with IP 10.46.0.3 already has 8 PFs for E-RAB ID 7 and when 4 more new Flow rules need to be added SMF crashes (after receiving Update Bearer Response in packet 12132)
[smf_log_pcap.zip](https://github.com/open5gs/open5gs/files/6868668/smf_log_pcap.zip)

Fixes the stash smashing when number of PFs per bearer > 8

---

lib/core/ogs-pkbuf.c

Observed following error while bringing up 1000 simultaneous sessions on K8s cluster:
```
^[[32m08/22 22:30:43.554^[[0m: [^[[33mmem^[[0m] ^[[1;33mERROR^[[0m: cluster_alloc: Expectation `buffer' failed. (../lib/core/ogs-pkbuf.c:310)
^[[32m08/22 22:30:43.554^[[0m: [^[[33mmem^[[0m] ^[[1;33mERROR^[[0m: ogs_pkbuf_alloc() failed [size=1255] (../lib/core/ogs-pkbuf.c:198)
^[[32m08/22 22:30:43.554^[[0m: [^[[33mmem^[[0m] ^[[1;33mERROR^[[0m: ogs_malloc_debug: Expectation `pkbuf' failed. (../lib/core/ogs-memory.c:38)
^[[32m08/22 22:30:43.554^[[0m: [^[[33mcore^[[0m] ^[[1;33mERROR^[[0m: ogs_memdup_debug: Expectation `res' failed. (../lib/core/ogs-strings.c:165)
^[[32m08/22 22:30:43.554^[[0m: [^[[33mcore^[[0m] ^[[1;33mERROR^[[0m: ogs_strdup_debug: Expectation `res' failed. …
```

Increase cluster_2048_pool to 1024

---

misc/db/open5gs-dbctl

This PR fix the exit code of open5gs-dbctl. Before is always 0, now It is the same exit code as the call to the mongo cli.
The PR also enable the control of mongodb other than localhost. You can provide a mongodb uri through the env variable DB_URI or the flag `--db_uri='. flag takes precedence over env variable. If none is provided, the default value is the same as before (mongodb://localhost/open5gs).

Improve open5gs-dbctl

---

src/upf/context.h
src/upf/meson.build

The UPF currently includes a dependency to Diameter (specifically the Gx interface) that isn't needed. Best I can tell, Gx interface connects the old PGW-C (now the SMF) to the PCRF, so my guess is that this got left behind during the CUPS refactoring. I already checked that the UPF does not have any Diameter code and removing these dependencies does not appear to create any errors.
The reason I care about this is because I'm currently working to build a very lightweight open5gs User Plane Server (just the SGWU and UPF) and our target environment (OpenWRT) does not support Diameter.
Thanks a ton for all your hard work!
Spencer

Remove Diameter dependencies from upf

---

src/pcf/context.c
src/pcf/context.h
src/pcf/npcf-handler.c

Hello @acetcom,
working with Open5gs I notice that when a UE establishes two pdu sessions with the same dnn and s-nssai (this is correct, in fact from ts 23.502 4.3.2.2.4: A UE can establish multiple PDU sessions associated with the same DNN and S-NSSAI ) the PCF creates two different sm-policies resources (since the body of the POST / sm-policies request contains the session id). Instead, the BSF binds a bond based on s-nssai and dnn, so only one bond is created.
The first time the UE activates a pdu session release for one of the two previously established the procedure works, after which, for the second, a semantic error is given (in the BSF there is no longer any constraint for the session).
To work around this problem, you can drop the BSF association only when there is only one …

BSF bind delete possible fix

---

src/mme/mme-sm.c

Hey @acetcom 
When an unknown UE/IMSI attempts to attach, currently the MME responds with EMM Cause 8 "EPS services and non-EPS services not allowed" after the HSS reports the user as unknown. 
https://github.com/open5gs/open5gs/blob/main/src/mme/mme-sm.c#L48
Take the example of a MNO UE in an area of very poor coverage. It is struggling to connect to its home network, so carries out a cell search to try and find other candidate cells to connect to. It sees a number of other rival MNO cells; but these PLMNs are blacklisted in the FPLMN parameter on the USIM. It sees the Open5GS private network... tries to attach and is rejected with Cause 8. This does not explicitly tell the UE it is not permitted to attach to the cell or network, and the result is that after a short timeout period, the …

Attach reject for foreign IMSI

---

lib/core/ogs-sockaddr.c
lib/core/ogs-sockaddr.h
src/smf/gtp-path.c

As per RFC 4861 Router advertisement message
format, Source Address MUST be the link-local address
assigned to the interface from which this message is sent.
Since SMF was not sending it as per RFC, certain
phones were not completing the procedure of stateless
IPv6 address autoconfiguration mentioned in
3GPP TS 23.401 version 15.12.0 Release 15, section 5.3.1.2.2

[SMF] Fix router advertisement as per rfc 4861

---

src/mme/emm-build.c
src/mme/emm-handler.c
src/mme/s1ap-handler.c
src/sgwc/s11-handler.c

Noticed an inconsistency where cell ID is printed in info/debug logs. Sometimes printed as hex (which matches all other logs - although also printed as `CellID[0x%x]`), but it is printed in decimal. So changed to hex representation!
```
cd open5gs
grep -r "CELL_ID:" .
./src/smf/nsmf-handler.c:   ogs_debug("    NR_CGI[PLMN_ID:%06x,CELL_ID:0x%llx]",
./src/smf/nsmf-handler.c:   ogs_debug("    NR_CGI[PLMN_ID:%06x,CELL_ID:0x%llx]",
./src/mme/s1ap-handler.c:   ogs_info("    OLD E_CGI[PLMN_ID:%06x,CELL_ID:%d]",
./src/mme/s1ap-handler.c:   ogs_info("    E_CGI[PLMN_ID:%06x,CELL_ID:%d]",
./src/mme/s1ap-handler.c:   ogs_debug("    OLD E_CGI[PLMN_ID:%06x,CELL_ID:%d]",
./src/mme/s1ap-handler.c:   ogs_debug("    E_CGI[PLMN_ID:%06x,CELL_ID:%d]",
./src/mme/emm-handler.c:    ogs_debug("    OLD …
```

print cellID in hex for consistency

---

configs/systemd/open5gs-smfd.service.in
configs/systemd/open5gs-upfd.service.in

This pull request relaxes the systemd "Requires" specifications currently used for the smf and upf. This allows them to keep running when systems using netplan.io (ubuntu) run `netplan apply` to update interface configurations. This PR has been tested on Ubuntu 20.04 and Debian 11, but please check if I am misunderstading a reason why the hard Requires dependency is needed!

Relax systemd requirements

---

lib/gtp/xact.c

The mandatory part of the header must be excluded from the header, that
is flags(1)+type(1)+length(2)+teid(4) = 8 bytes.

[GTPv1C] Fix outer message length field containing wrong value

---

lib/gtp/v1/message.c
lib/gtp/v1/message.h
lib/gtp/v1/support/gtp1-tlv.py
src/smf/gn-build.c

It seems to be actually mandatory in GGSN->SGN directon, though it is
ignored in Release99 upwards. Let's hardcode it to 0 for now, should be
fine in the majority of cases.

[GTPv1C] Send conditional IE Reordering Required in CreatePDPCtxResp

---

src/smf/gn-build.c
src/smf/gn-handler.c

SMF setting incorrect Cause when answering
with a changed APN type IPv4v6 ->IPv4/IPv6
Related: https://github.com/open5gs/open5gs/issues/1360

[SMF] incorrect GTPv1C cause with changed APN

---

configs/open5gs/pcrf.yaml.in
configs/open5gs/smf.yaml.in
lib/ipfw/ogs-ipfw.c
lib/ipfw/ogs-ipfw.h
src/pcrf/pcrf-rx-path.c
src/smf/binding.c
src/smf/gsm-build.c

As per 3GPP TS 24.008, following Packet filter component type identifier
are not supported on the LTE pre release-11 UEs:
IPv4 local address type
IPv6 remote address/prefix length type
IPv6 local address/prefix length type
And,
IPv6 remote address/prefix length type and
IPv6 local address/prefix length type shall be used when both MS and
Network support Local Address in TFTs.
This commit add logic to omit adding local address in packet filters
for compatibility with pre-release LTE 11 devices. The following parameter
could be used to toggle omit/no to omit behavior.
```
parameter:
no_ipv4v6_local_addr_in_packet_filter: <true/false>
```

Bugfix packet filter for pre rel11 LTE devices

---

src/pcrf/pcrf-gx-path.c
src/smf/gx-path.c

As per 3GPP TS 23.401 version 15.12.0, section 5.3.1.2.2
The PDN GW allocates a globally unique /64
IPv6 prefix via Router Advertisement to a given UE.
After the UE has received the Router Advertisement message, it
constructs a full IPv6 address via IPv6 Stateless Address
autoconfiguration in accordance with RFC 4862 using the interface
identifier assigned by PDN GW.
For stateless address autoconfiguration however, the UE can
choose any interface identifier to generate IPv6 addresses, other
than link-local, without involving the network.
And, from section 5.3.1.1, Both EPS network elements and UE shall
support the following mechanisms:
/64 IPv6 prefix allocation via IPv6 Stateless Address
autoconfiguration according to RFC 4862, if IPv6 is
supported.

Fix prefix length in Gx CCR Framed-IPv6-Prefix AVP

---

src/smf/context.c

Without this patch, SMF crashes when allocating 1024 concurrent PDP
Contexts. With this patch, instead of crashing, SMF answers a Create PDP
Context Response with cause "No Context", hence properly rejecting the
creation of the PDP contexts and staying alive providing service.

[SMF] Avoid crash if smf_ue_pool is full (1024 UEs)

---

docs/_docs/guide/02-building-open5gs-from-sources.md

Signed-off-by: ji3k54j062k7 <ji3k54g4j062k7@gmail.com>
Since `cd install/bin/` cannot execute `./install/bin/open5gs-mmed` and other 5G components, this command should not be executed.

modify building from source md file

---

lib/core/ogs-socket.c
lib/core/ogs-socket.h
lib/core/ogs-socknode.c
lib/core/ogs-socknode.h
lib/core/ogs-udp.c
lib/gtp/context.c
lib/pfcp/context.c
lib/sbi/context.c
src/amf/context.c
src/mme/mme-context.c
src/nssf/context.c
tests/common/context.c
tests/core/socket-test.c

This is useful, among other possible applications, to make use of VRFs [1],
in this case for GTP-C and GTP-U traffic in the PGW.
The bind_dev field is added to the ogs_socknode_t so that it's easy to
extend its use into lots of other sockets being set up based on config
file information.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/networking/vrf.rst

[GTP] Support binding socket to device

---

lib/core/ogs-time.c
lib/core/ogs-time.h
lib/pfcp/context.c

These will be further needed in PFCP in the future, as well as in other
Diameter based interfaces (such as Gy).
Let's put all implementation details in APIs so that devs don't need to
care about those details every time.

[CORE] time: Add APIs to manage NTP 32-bit timestamps

---

src/smf/gx-path.c

Otherwise, if h->msg_appl is left as 0, libfreediameter will not try to
match against supported peer's AppIds when taking routing decisions for
the packet (see libfreediameter's dont_send_if_no_common_app()).

[SMF] Gx: Prevent sending Gx messages to non-PCRF Diameter peers 

---

lib/pfcp/build.c
lib/pfcp/types.h

The "Report Triggers" is sent SMF->UPF to tell in which situations a
report should be sent.
The "Usage Report Trigger" is sent UPF->SMF to indicate which situation
triggered the report.

[PFCP] Use proper IE to signal triggers in Usage Report

---

lib/diameter/common/message.c
lib/diameter/common/message.h
lib/diameter/gy/dict.c
lib/diameter/gy/meson.build
lib/diameter/gy/message.c
lib/diameter/gy/message.h
lib/diameter/gy/ogs-diameter-gy.h

This commit adds required blocks in lib/diameter to be able to handle Gy
messages later in open5gs apps.
The Gy interface is mainly decribed in 3GPP TS 32.299  and 3GPP TS
32.251, which in turn refers to Diameter protcols defined in RFC4006.
This interface allows charging managment through an external OCS node.

[DIAM] Add Gy interface support to lib/diameter

---

lib/pfcp/build.c
lib/pfcp/build.h
lib/pfcp/xact.h
src/smf/context.h
src/smf/event.c
src/smf/event.h
src/smf/fd-path.c
src/smf/gx-handler.c
src/smf/gy-handler.c
src/smf/gy-handler.h
src/smf/gy-path.c
src/smf/meson.build
src/smf/n4-build.c
src/smf/n4-handler.c
src/smf/smf-sm.c

TODO:
* Use an event for the report, like SMF_EVT_N4_TIMER?
*  Properly set Service identifier in Gy CCR
* SMF: Properly set pkt/octet volumes in Gy CCR
** Update when receiving PFCP Modify Response.
* Figure out best way to require Gy through config file in open5gs-smfd.
* Create a new sess-sm.c which handles smf_sess_t state through
Gx+Gy+PFCP creation, modification and tear down. This way we can do
stuff in parallel, for instance Gx+Gy. It will alsoavoid duplicating
some code paths due to Gy being optional.

[WIP, RFC] Introduce Gy interface

---

configs/open5gs/smf.yaml.in
lib/pfcp/build.c
lib/pfcp/build.h
lib/pfcp/xact.h
src/smf/context.c
src/smf/context.h
src/smf/event.c
src/smf/event.h
src/smf/fd-path.c
src/smf/gx-handler.c
src/smf/gy-handler.c
src/smf/gy-handler.h
src/smf/gy-path.c
src/smf/meson.build
src/smf/n4-build.c
src/smf/n4-handler.c
src/smf/smf-sm.c

The use of the Gy interface (SMF acting as CTF towards an OCS node) is
mandated through configuration file. Default value "enable: auto" will
only make use of it in case a Diameter peer announcing support for the
Credit-Control Application is found.
Upon subscriber session creation, and after auth check over Gx, the SMF
will create a Gy session with the OCS and only after that step the SMF
will accept the session back to the subscriber.
The OCS may then grant some traffic volumes/time and ask to be notified
back with updated measurements.
In order to get the measurements, the SMF relies on PFCP URR configured
to the UPF through Session Repoort Request messages.
When closing the subscriber session, the SMF will also terminate the Gy
session at the OCS.
So far only some specifics parts of …

[SMF] Introduce optional Gy interface support

---

src/mme/emm-build.c

This commit adds EMM Cause to Attach accept message when
Attach Request has COMBINED EPS IMSI ATTACH but the HSS
Network-Access-Mode is configure for EPS ONLY.

Send EMM Cause when Attach Request type is not same as HSS Network-Access-Mode

---

src/smf/event.h
src/smf/gn-handler.c
src/smf/gn-handler.h
src/smf/gsm-sm.c
src/smf/gx-handler.c
src/smf/gx-handler.h
src/smf/gy-handler.c
src/smf/gy-handler.h
src/smf/n4-handler.c
src/smf/n4-handler.h
src/smf/pfcp-sm.c
src/smf/s5c-handler.c
src/smf/s5c-handler.h
src/smf/smf-sm.c
src/smf/smf-sm.h

It allows for much better control on the lifecycle of the session, and
already shows some missing tear down paths in case of errors.
It also clarifies the existence of "sess" pointer in several paths.
The code also becomes clearer overall, since all the transitions and
logic to send next messages are put together.
Tear down of the session will be integrated into gsm-sm in a follow-up
patch.
The 5gc session setup is only partially moved to gsm-sm, and left as an
exercise for users wishin to improve 5gc support.

[SMF] Inegrate session setup cycle into sess->sm

---

src/smf/context.h
src/smf/gsm-sm.c

There's no real need to having to wait until Gx is processed in order to
set up Gy. This speeds up time required to set up the UE session.

[SMF] Parallelize Gx+Gy CCR Initial

---

src/smf/context.h
src/smf/gn-handler.c
src/smf/gy-path.c
src/smf/s5c-handler.c
tests/common/context.c

The encoding in GTPv1C is different than in GTPv2C. The former has an
extra byte prepended specifying the nature of address and numbering plan
indicator. Diameter doesn't require that information so we simply strip
it of.
In any case TS 29.060 (GTPv1C) sec 7.7.33 states:
"""
The MSISDN shall be in international format and the "nature of address indicator" shall indicate
"international number".
"""
So we are fine stripping and copying over.

[SMF] Store MSISDN from GTPC and pass it in Gy CCR

---

src/smf/gn-handler.c
src/smf/gy-path.c
src/smf/s5c-handler.c

Issue:
When the ULA - Subscription Data does not contain MSISDN, the Create Session Request
from MME to SGW does not contain MSISDN IE resulting in SMF throwing following log
```
smf        | 05/09 15:20:53.683: [smf] ERROR: No MSISDN (../src/smf/s5c-handler.c:82)
sgwc       | 05/09 15:20:53.683: [sgwc] ERROR: No Context in TEID (../src/sgwc/s5c-handler.c:104)
mme        | 05/09 15:20:53.683: [mme] ERROR: No Context in TEID (../src/mme/mme-s11-handler.c:122)
```
As per 3GPP TS 29.274 version 16.5.0, table 7.2.1-1: MSISDN IE shall only be included
in Create Session Request if its provided in subscription data from the HSS. This commit
fixes this by removing the mandatory MSISDN IE check in SMF.

Fix attach reject when ULA subscription data does not contain MSISDN

---

src/mme/mme-gtp-path.c

This is a tentative fix to an obscure crash we have started noticing in production. I would love some help/feedback as to the best way to solve this problem, because I am not sure if this is the best place to put this fix, or if the fix needs something else as well.
The crash happens when one or more users is connected to an eNB, and then the eNB and user-plane-server (SGWU and UPF) go offline at the same time. More explanation: when the eNB goes offline, after 90 seconds of unanswered HEARTBEAT messages, the SCTP handler tears down the connection. This codepath results in the MME sending a Release Access Bearers Request to the SGWC. The SGWC then sends a PFCP Session Modification Request to the SGWU. If the SGWU is offline, it (obviously) does not respond. The SGWC re-sends the Session …

fix MME crash after sctp disconnect

---

lib/sbi/message.c
lib/sbi/message.h
src/smf/nudm-handler.c
src/udm/nudr-handler.c
src/udr/nudr-handler.c

According to the following standards the response to the endpoint
/nudm-sdm/${supi}/sm-data should be an array of
SessionManagementSubscriptionData objects, instead of only one object.
TS 29.503 version 16.6.0
TS 29.505 version 16.4.0
UDR now responds to the request with only item in the array.
UDM copies all items as is.
SMF uses only the first item in the array, even if there are more
present.

Change handling of SessionManagementSubscriptionData as an array

---

src/smf/gn-build.c

While at it, fix indentation for the same existent code blocks.

[SMF] Gn: Avoid building QoS Profile IE twice in UpdatePdpContextResp

---

lib/nas/5gs/conv.c
src/amf/context.c
src/amf/gmm-handler.c

For null protection scheme the SUCI needs to be BCD encoded. Whereas for
protection scheme profiles A and B the SUCI needs to be converted from
hexadecimal to ASCII.
This still needs the support for protection schemes A and B in UDM to
work.

[AMF] Add support for SUCI protection schemes A and B

---

lib/metrics/meson.build
lib/sbi/meson.build

Recent commit re-enabling SBI HTTP/1.1 support
(10bdf39505cf525b95886c140b3c2e82e7427d29) started using libmicrohttpd's
API MHD_create_response_from_buffer_with_free_callback(), which is only
available starting from v0.9.61.
As a result, compilation in xUbuntu 18.04 started failing with errors
about the function not being found, since it ships with libmicrohttpd
v0.9.59.
Depending on 0.9.61 is fine since it's quite old (november 2018) and all
major current distros should for sure have an >= one. Let's simply bump
the version check so that it fails in an informative manner.

meson: Depend explicitly on libmicrohttpd >=0.9.61

---

lib/sbi/custom/patch_item.c
lib/sbi/message.c
lib/sbi/message.h
lib/sbi/ogs-sbi.h
src/amf/gmm-sm.c
src/amf/nsmf-handler.c
src/amf/nudm-build.c
src/amf/nudm-build.h
src/udm/nudm-handler.c
src/udm/nudm-handler.h
src/udm/nudr-build.c
src/udm/nudr-build.h
src/udm/nudr-handler.c
src/udm/ue-sm.c
src/udr/nudr-handler.c

[UDM,UDR] Add support for endpoint for patching subscription data
[AMF] Send deregistration event to UDM
When UE sends deregistration request, AMF needs to send a
Nudm_UECM_Deregistration request to UDM.
The order of requests is now the following:
- send PDU session release to SMF
- send AM policy control release to PCF
- send deregistration event to UDM

Send deregistration event from AMF to UDM

---

lib/core/ogs-sockaddr.c
lib/sbi/client.c

A sockaddr of type AF_INET and AF_INET6 has fields: addr and port.
Only port was checked so far, meaning sockaddresses with same IP address
but different port would be seen as equal, which is wrong.
As a result, ogs_gtp_node_find_by_addr() would be unable to identify GTP
peers having same IP address but different remote port.
Related: https://github.com/open5gs/open5gs/issues/1607

[CORE] Compare port in ogs_sockaddr_is_equal()

---

src/mme/mme-sm.c

Still in an MME, so, should refer to the eNB interface as S1.

Update mme-sm.c for Typo

---

lib/sbi/client.c

Valgrind memcheck tool reports an error, of invalid read beyond the
allocated memory.
Function "write_cb()" already allocates (realloc) +1 byte and
null-terminates the data. But the length "conn->size" does not contain
this extra null-terminated byte.
When a copy of the received data is made in "check_multi_info()", it
does not include the null character, resulting in potentially a
non-null terminated string.
Later on when parsing the data, "strlen()" will read beyond the
allocated memory to search for the null character, resulting in an
invalid read.
==1994== Invalid read of size 1
==1994==    at 0x484ED24: strlen (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1994==    by 0x4D3F401: cJSON_ParseWithOpts (cJSON.c:1109)
==1994==    by 0x4D3F65C: cJSON_Parse (cJSON.c:1197) …

[SBI] Fix invalid read beyond allocated memory

---

misc/db/open5gs-dbctl

Added the following show commands for the command line user interface of Mongo to be able to see the list of users in database
showall: shows the list of subscribers in the db"
showpretty: shows the list of subscribers in the db in a pretty json tree format"
showfiltered: shows {imsi key opc apn ip} information of subscriber"

Added show commands in the dbctl

---

.dockerignore
docker/build/Dockerfile
docker/docker-compose.yml

"build" Docker image previously downloaded latest version of Open5GS
from github, and built the project from that.
Use local source files for building instead.

[build] Use local sources to build applications

---

src/smf/gy-path.c

Gy (3GPP TS 32.299 ) refers to AVP in DCCA (RFC4006).
RFC4006 5.1.2:
"[...] by including the Multiple-Services-Indicator AVP in the first
interrogation."
Nokia's infocenter documentation also states it's sent during Initial CCR
only: "(CCR-I only)".

[SMF] Gy: Send Multiple-Services-Indicator AVP only during Initial CCR

---

lib/sbi/nghttp2-server.c

Delete nghttp2 session to prevent memory leaks.
The issue was detected using valgrind.

[SBI] Fix memory leak for nghttp2 session

---

configs/open5gs/sgwc.yaml.in
configs/open5gs/smf.yaml.in
lib/app/ogs-context.c
lib/app/ogs-context.h

This is needed specially for SMFs handling a pool of SGWs.

[SGWC,SMF] Add specific config opt max.gtp_peer to set gtp_node mempool size

---

src/upf/n4-handler.c

In that case, ogs_pfcp_ue_ip_alloc() will fail with  the error message
"CHECK CONFIGURATION: Cannot find subnet [...]" and the assert will make
upf crash.
That's not desirable, let's keep it running and simply reject the
request. The error log is big enoguh to find out.

[UPF] Avoid crash if no default subnet configured

---

src/smf/pfcp-sm.c

It was spotted that if DeleteSessionReq sent by SMF is answered by UPF
with cause="Session context not found", then it contains SEID=0 (this is
correct as per specs). Hence, since SEID=0 session is not looked up, so
sess=NULL.

[SMF] pfcp-sm: Fix ogs_fsm_dispatch() on NULL sess

---

src/smf/npcf-handler.c

This helps UPF to add ACL based on UE src ip
Signed-off-by: Networkmama <networkmama12@gmail.com>

[SMF] copy UE ip address to uplink PDR rules.

---

debian/open5gs-upf.postinst

Don't attempt to restart systemd-networkd if systemd is not running
(e.g. installing open5gs inside a chroot).
Fix for:
```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error processing package open5gs-upf:amd64 (--configure):
installed open5gs-upf:amd64 package post-installation script subprocess returned error exit status 1
```

d/open5gs-upf.postinst: don't restart service in chroot

---

src/amf/gmm-sm.c
src/amf/nsmf-handler.c

According to TS 23.502, 4.2.2.2.2, AMF sends Registration event to UDM
in the following cases:
- If the AMF has changed since the last Registration procedure, or
- if the UE provides a SUPI which doesn't refer to a valid context in
the AMF,
- or if the UE registers to the same AMF it has already registered
to a non- 3GPP access (i.e. the UE is registered over a non-3GPP access
and initiates this Registration procedure to add a 3GPP access).
In case that UE re-registers to the network with a GUTI, it bypasses
authentication check to the AUSF. In this case, AMF does not send
Registration event to UDM.
Consequently, when UE deregisters again, AMF would send a Deregistration
Event to a UDM, which does not have a context for it.
3GPP standard does not say when AMF sends Deregistration Event to …

[AMF] Do not send Deregistration Event to UDM when UE deregisters

---

docker/docker-compose.test.yml

The issue was introduced with the commit, which builds Open5GS from
local sources instead of downloading them each time from Github.
Fixes: d2cbcf711 ("[build] Use local sources to build applications (#1583)")

[tests] Fix running unit tests inside docker environment

---

src/mme/mme-fd-path.c

For HSS's which do not include the NAM, the MME should not treat this as a fatal error.  MME should just assume PACKET_AND_CIRCUIT (0), as was decided in a previous PR.

[MME] Set default Network-Access-Mode to 0

---

lib/core/ogs-3gpp-types.h
lib/diameter/s6a/message.c
lib/diameter/s6a/message.h
src/mme/mme-context.h
src/mme/mme-fd-path.c
src/mme/mme-s11-build.c
src/mme/mme-s6a-handler.c

When using commercial HSS which includes the CC in the profile, the expected result was not found in the S11 Create Session Request.  Similarly, when the HSS did not include the CC, it was still being included.  MME currently uses a default charging_characteristics value.  I am recommending this change to make use of the charging characteristics value at both the subscription and PDN level.  If there is no charging characteristic specifically sent for the PDN, the subscription level cc is used.  If neither are included, then no charging characteristic is sent in S11, following TS32.251 A.4.

[MME] Introduce support for handling Charging Characteristics from HSS

---

src/hss/hss-s6a-path.c
src/hss/hss-swx-path.c
src/mme/mme-fd-path.c

Noticed in error cases when experimental result code was being used that a few AVPs were duplicated.  
Results from setting Origin-Host, Origin-Realm and Result-Code with fd_msg_rescode_set before we have checked all the potential error conditions which result in the use of ogs_diam_message_experimental_rescode_set.
Resolves #913

[MME+HSS] AVP Occurring Too Many Times

---

src/smf/gn-handler.c
src/smf/s5c-handler.c

S5c: As per 3GPP TS 29.274 version 10.5.0, section 7.2.9 and 7.2.10,
Only if PCO IE is included in Delete Session Request then it
must be present in Delete Session Response.
And
Gn: As per 3GPP TS 29.060 version 15.3.0, section 7.3.3, 7.3.4, 7.3.5 and 7.3.6
Only if PCO IE is included in Update/Delete PDP Context Request then it
must be present in Update/Delete PDP Context Response.
In order to reflect on whether the request contained PCO IE or not
the SMF context containing the GTP request needs to be updated
i.e. update if present else clear the contents

Fix PCO IE sent in response over S5c and Gn irrespective of its presence in request

---

lib/metrics/prometheus/context.c

Adding metric instance to the list used "&inst->entry", while trying to
remove it from the list used pointer "inst". This has caused that the
instance was freed, but the pointer still remained in the list.
On application exit, each application cleanups it's own metrics, while
metrics library does the same. This has caused double-free crash.

[metrics] Fix double-free on application exit

---

lib/diameter/gx/message.c
lib/diameter/gx/message.h
src/smf/gx-path.c

The 3GPP-Charging-Characteristics is an operator specific AVP
(optional). The 3GPP-Charging-Characteristics can be filled by the HSS
and forwarded by the MME, SGWc towards the SMF.
In preparation to allow the PCRF to work without any database.

Gx: add support for 3GPP-Charging-Identifier

---

src/smf/gx-path.c

I've pushed early version to github instead of the correct one. 
- Gy instead of Gx AVP was used.
- Use correct avp position and avp variables.
Fixes: 657eef9169af ("[SMF] send 3GPP-Charging-Characteristics on Gx if received on S5/8c")

[SMF] fixup send 3GPP-Charging-Characteristics on Gx if received on S5/8c

---

src/smf/context.h
src/smf/n4-handler.c
src/smf/nsmf-handler.c

According to TS 29.502 5.2.2.3.2.2. step 4 we should reply with a 200 response
including the upCnxState attribute.

[SMF] Handle upCnxState=ACTIVATING by later replying with 200 instead of 204

---

lib/sbi/message.c

OpenAPI specification for sending NF discovery query with
"service-names" parameter is defined as folowing:
- name: service-names
...
style: form
explode: false
According to OpenAPI specification, this means array items
should be delimited with a comma character (example: /users?id=3,4,5).

[SBI] Send NF discovery query with service-names delimited with comma

---

src/amf/gmm-handler.c

In case that APN name sent from UE does not case-match with the one configured in the database, AMF would reject the registration with the message:
[gmm] WARNING: [imsi-xxx] DNN Not Supported OR Not Subscribed in the Slice (../src/amf/gmm-handler.c:1051)
Also somewhat relevant issue: https://github.com/open5gs/open5gs/issues/617

[AMF] Handle APN/DNN names as case-insensitive

---

src/smf/context.h
src/smf/gsm-sm.c

When UE would send a request to release PDU session, AMF would eventually send "PDU Session Resource Release Command" downlink to both UE (N1) and gNB (N2). Each UE and gNB would then reply with "PDU Session Resource Release Response" indicating they released their own resources.
Usually the first one to respond would be gNB. SMF made an assumption that this would always be the case. And it would wait for signal that UE resources were freed, before releasing session resources. But occasionally the situation is that UE responds first, and SMF releases resources prematurely.
This situation does not normally occur. But under high stress (100's of UE PDU releases at the same time) this happens occasionally. According to the standard, this situation is perfectly normal.
3GPP TS 23.502 Rel. 16 …

[SMF] Wait for both N1&N2 release signals before releasing session

---

lib/proto/types.h
lib/sbi/context.h
lib/sbi/nnrf-build.c
src/amf/context.c
src/amf/context.h

The actual configured GUAMIs and TAIs are used to form NF profile. Comparing to SMF the "info" section is not introduced into amf.yaml! Each amf_id (region, set) produces a separate Info in the InfoList. Guami list consists of all GUAMIs of particular Info. taiList consists of all TAIs for all PLMNs of particular Info.
Examle:
amf.yaml:
guami:
- plmn_id: mcc: 999 mnc: 70 amf_id: region: 2 set: 2 pointer: 4
- plmn_id: mcc: 001 mnc: 01 amf_id: region: 2 set: 1 - plmn_id: mcc: 001 mnc: 02 amf_id: region: 2 set: 2 tai: - plmn_id: mcc: 001 mnc: 01 tac: [1, 2, 3] tai: - plmn_id: mcc: 002 mnc: 02 tac: 4 - plmn_id: mcc: 001 mnc: 02 tac: 10 tai: - plmn_id: mcc: 004 mnc: 04 tac: [6, 7] - plmn_id: mcc: 005 mnc: 05 tac: 8 - plmn_id: mcc: 999 mnc: 70 tac: [9, 10]
"amfInfoList":  {
"1":    { …

[AMF] Add amfInfoList to NFProfile

---

lib/core/ogs-time.c

On 32bit systems, the timer will lock-up after running for approximately 70 minutes due to a buffer overflow. Specifically, the value (ts.tv_sec * 1000000UL) is read as a 32bit val and overflows itself.
The code as-written (multiplying 32bit and 64bit vals together) downgrades "1000000UL" and the result to 32bits (potentially creating a buffer overflow) and then casts the result to 64bit. To get correct behavior we need to cast ts.tv_sec to 64bits before we multiply.

[core] prevent timer overflow on 32bit systems

---

src/sgwc/pfcp-sm.c
src/sgwu/pfcp-sm.c
src/smf/pfcp-sm.c
src/upf/pfcp-sm.c

Adding slightly more verbose logging when PFCP associates/de-associates. This is very useful in contexts where you have more than one sgwu or upf.

[pfcp] add addr and port to pfcp assoc/de-assoc log messages

---

src/amf/gmm-sm.c

Provide pointer to state machine, instead of pointer to timer structure. Bug was noticed when switching compiler optimization to -O2.

[AMF] Fix for switching state when sending Deregistration Request fails

---

lib/diameter/s6a/message.h
lib/proto/types.h
src/hss/hss-context.c
src/hss/hss-s6a-path.c
src/hss/hss-s6a-path.h
src/mme/mme-fd-path.c
src/mme/mme-s6a-handler.c
src/mme/mme-s6a-handler.h
src/mme/mme-sm.c

* Supported AVPs in IDR will overwrite existing subscription information
* Provide error on partial APN updates
* IDR and ULA use same function to process AVPs
* Move subdatamask values into s6a, so both HSS and MME can use them
* Updates are not actioned at this time.  A Re-attach is required for most changes to take effect.  This is future work.
Closes the loop on https://github.com/open5gs/open5gs/issues/1694, and I think we're at the point where an operator can change a setting in the HSS, and have the changes show up at the MME without restarting.

[MME] Support for Insert Subscriber Data

---

src/sgwu/context.c
src/upf/context.c

To my understanding, the CP SEID is generated by the control plane functions {sgwc, smf} and the UP SEID is generated by the user plane functions {sgwu, upf}. The ogs_info log messages currently have this backwards.

swap CP and UP SEIDs in ogs_info log messages

---

lib/sbi/message.c
lib/sbi/message.h
lib/sbi/ogs-sbi.h
src/amf/amf-sm.c
src/amf/context.c
src/amf/context.h
src/amf/gmm-sm.c
src/amf/namf-handler.c
src/amf/namf-handler.h
src/amf/nudm-build.c
src/amf/nudm-build.h
src/amf/nudm-handler.c
src/udm/context.c
src/udm/context.h
src/udm/nudm-handler.c
src/udm/nudm-handler.h
src/udm/ue-sm.c

AMF subscribes to UDM for each registered UE.
At the moment, UDM does not send callback to AMF when any of the UE's properties in the database changes.
At the moment, AMF does properly parse the ModificationNotification, but does not do anything useful.

[AMF,UDM] Add support to subscribe to SDM changes

---

src/amf/context.c

Each UE context has 'current' and 'next' TMSI values. AMF first allocates the 'next' value, before confirming it and releasing the 'previous'. This means that we potentially need pool size of 2x the amount of maximum configured UE.
Without this change, AMF would crash in case that there are 'x' configured maximum amount of UE, and there are already 'x' registered UE.
[gmm] INFO: Registration request (../src/amf/gmm-sm.c:135)
[gmm] INFO: [suci-0-001-01-1234-0-1-1000000000]    SUCI (../src/amf/gmm-handler.c:149)
[gmm] DEBUG:     OLD TSC[UE:0,AMF:0] KSI[UE:7,AMF:0] (../src/amf/gmm-handler.c:179)
[gmm] DEBUG:     NEW TSC[UE:0,AMF:0] KSI[UE:7,AMF:0] (../src/amf/gmm-handler.c:186)
[amf] FATAL: amf_m_tmsi_alloc: Assertion `m_tmsi' failed. (../src/amf/context.c:2160)
[core] FATAL: backtrace() …

[AMF] Increase size of TMSI pool

---

src/amf/amf-sm.c
src/amf/context.c
src/amf/ngap-handler.c

AMF does not crash anymore when a new UE registration request arrives, and there is no available space left in UE context pool. Now it just rejects the request with an error.

[AMF] Reject registration requests when pool for UE contexts is empty

---

lib/app/ogs-context.c
lib/dbi/ogs-mongoc.c
lib/dbi/ogs-mongoc.h
src/hss/hss-context.c

In response to this:
> Hi Folks, what version of the mongo-c-driver are you assuming? I'm asking because this appears to break compilation on my side. I'm building open5gs on AmazonLinux2, which comes with version 1.3.6 of the mongo-c-driver. See
> 
> ## In file included from ../lib/dbi/ogs-dbi.h:28:0,
> 592 | from ../lib/dbi/session.c:20: 
> 593 | ../lib/dbi/ogs-mongoc.h:40:5: error: unknown type name 'mongoc_change_stream_t' 
> 594 | mongoc_change_stream_t *stream; 
> 595 | ^~~~~~~~~~~~~~~~~~~~~~
_Originally posted by @rmerz in https://github.com/open5gs/open5gs/issues/1758#issuecomment-1275785067_
Support for change stream is only available in mongoc >=1.9.0
- Disabled related functions in dbi.
Support for bson to json used in debug statement only in libbson >=1.7.0
- Simple debug …

[DBI] Disable Change Streams with mongo Version

---

lib/sbi/nnrf-build.c

OpenAPI dictates that certain arrays should have at least one item, otherwise they should not be present.
This includes lists for IPv4/v6 addresses, TAI/TAC lists, ...
Add a check if there is at least 1 item, before creating an array. Also move variable declarations to inner blocks, to prevent some accidental usage out of wanted scope.

[SBI] Do not send empty arrays when registering to NRF

---

docker/webui/Dockerfile

Use local copy of source code to build webui,
instead of downloading the code from Github.

Build webui from local source

---

lib/sbi/client.c
lib/sbi/client.h
lib/sbi/context.c
lib/sbi/conv.c
lib/sbi/meson.build
lib/sbi/nghttp2-server.c
lib/sbi/server.h

This TLS support is currently implemented only on NF HTTP2 server side to get encrypted traffic between NFs.
It is still not implemented that client checks server certificate and that server checks client certificate. That's left for the next phase.
https://github.com/open5gs/open5gs/issues/754
https://github.com/open5gs/open5gs/discussions/1102

Add TLS support

---

src/amf/init.c
src/mme/mme-init.c

Even if the configured log level for the application was set to "error", the first "info" message of the metrics library was output to the log. Reorder the initialization of the metrics library.

[metrics] Fix log output for metrics

---

src/amf/nnrf-handler.c

amf_ue will be null and cause a coredump when type is OGS_SBI_OBJ_SESS_TYPE.

get amf_ue from sess

---

src/amf/gmm-handler.c

Hey @acetcom,
Unfortunately commit https://github.com/open5gs/open5gs/commit/5295c108adc2fc5ae97ee5007760334ef7a6297b broke smf selection on the amf based on the defined smf configuration info (tac, S-NSSAI, DNN, etc). Use case is described by @s5uishida in https://github.com/s5uishida/open5gs_5gc_ueransim_nearby_upf_sample_config (link from the open5gs documentation).
This sounds like a regression to me since according to the documentation on the `smf.yaml` configuration files (https://github.com/open5gs/open5gs/blob/main/configs/open5gs/smf.yaml.in#L363-L490) this is supposed to work.

amf: fix regression for smf selection

---

configs/open5gs/pcf.yaml.in
configs/open5gs/upf.yaml.in
configs/sample.yaml.in
configs/slice.yaml.in
configs/srslte.yaml.in
configs/volte.yaml.in
configs/vonr.yaml.in
lib/sbi/conv.c
lib/sbi/conv.h
src/pcf/context.c
src/pcf/context.h
src/pcf/init.c
src/pcf/meson.build
src/pcf/metrics.c
src/pcf/metrics.h
src/pcf/nbsf-handler.c
src/pcf/npcf-handler.c
src/pcf/nudr-handler.c
src/upf/context.c
src/upf/context.h
src/upf/gtp-path.c
src/upf/init.c
src/upf/meson.build
src/upf/metrics.c
src/upf/metrics.h
src/upf/n4-handler.c
src/upf/pfcp-path.c

Expose metrics with labels according to ETSI TS 128 552 V16.13.0 in
PCF and UPF by using hash.
The metrics are named respecting the rule:
<generation>_<measurement_object_class>_<measurement_family_name>_<metric_name_as_in_TS_128_552>

[PCF, UPF] Add metrics support

---

src/smf/npcf-build.c

In case that database is (manually) corrupted for a specific UE, SSC mode and ARP preemption vulnerability fields are not set correctly, SMF will crash when trying to build a request to create PCF association.
Function smf_npcf_smpolicycontrol_build_create() will end prematurely, and when cleaning up resources it will try to free() up invalid pointer, which was not set to 0 at beginning of the function.
[smf] ERROR: SSCMode is not allowed (../src/smf/nudm-handler.c:165) [sbi] DEBUG: STATUS [201] (../lib/sbi/nghttp2-server.c:443) [sbi] DEBUG: SENDING...: 3 (../lib/sbi/nghttp2-server.c:451) [sbi] DEBUG: {
} (../lib/sbi/nghttp2-server.c:452)
[sbi] DEBUG: STREAM closed [1] (../lib/sbi/nghttp2-server.c:962) [smf] ERROR: No Arp.preempt_cap (../src/smf/npcf-build.c:132) <crash>
0  __GI_abort () …

[SMF] fix crash due free-ing invalid pointer

---

src/amf/context.c
src/amf/context.h
src/amf/gmm-sm.c
src/amf/metrics.c
src/amf/metrics.h
src/amf/nas-path.c
src/smf/context.c
src/smf/metrics.c
src/smf/metrics.h
src/smf/n4-handler.c
src/smf/nsmf-handler.c

Expose RM and SM metrics with labels according to ETSI TS 128 552 V16.13.0 by using hash.
The metrics are named respecting the rule:
<generation>_<measurement_object_class>_<measurement_family_name>_<metric_name_as_in_TS_128_552>
Existing SMF gauge sessions_active is renamed!

[AMF, SMF] Add RM and SM metrics support

---

lib/sbi/nnrf-build.c
src/amf/amf-sm.c
src/amf/context.c
src/amf/context.h
src/ausf/ausf-sm.c
src/ausf/context.c
src/ausf/context.h
src/bsf/bsf-sm.c
src/bsf/context.c
src/bsf/context.h
src/nssf/context.c
src/nssf/context.h
src/nssf/nssf-sm.c
src/pcf/context.c
src/pcf/context.h
src/pcf/pcf-sm.c
src/smf/context.c
src/smf/context.h
src/smf/smf-sm.c
src/udm/context.c
src/udm/context.h
src/udm/udm-sm.c

The current load percentage of the NF Service Consumer is provided in the payload body of the PATCH request when periodically contacting the NRF (heart-beat).
- AMF: ratio between currently connected ran_ue and maximum number of them
- SMF: ratio between current PDU sessions and maximum available
- PCF: ratio between current AM+SM policy associations and maximum available
or ratio between currently connected UEs and maximum number of them
(the load which is higher)
- AUSF, UDM: ratio between currently connected UE and maximum number of them
- BSF: ratio between current sessions and maximum available
- NSSF: ratio between currently used NSIs and maximum number of them
NRF currently doesn't determine that the NF Profile has changed.

Add NF load to NRF Heartbeat

---

src/smf/context.c

Metric 'bearers_active' was incremented in only one code path (smf_bearer_add() for 4G only), while it was decremented from two paths (smf_bearer_remove() for both 4G and 5G).
Increment metric also for 5G path (smf_qos_flow_add()), so it won't get decremented into negative values.

[SMF] Fix metric bearers_active

---

lib/dbi/ogs-mongoc.c

If one restricts mongo by creating a separate user for the "open5gs" database, OGS NFs may not have sufficient privileges on the "admin" database, to perform the "serverStatus" command.

[mongo] Use "ping" command instead of "serverStatus" during mongo initialization

---

src/smf/nsmf-handler.c

Implementation on SMF only, for now:
From TS 23.502 release 16, chapter 5.2.8.2.1 General:
... UE is handed-over from an (old) AMF towards another (new) AMF, the old AMF provides the new AMF with the SMF addressing information corresponding to the AMF-SMF association related with each PDU Session of that UE. The new AMF can thus further act upon the association with the SMF via Nsmf_PDUSession_UpdateSMContext and Nsmf_PDUSession_ReleaseSMContext operations. This may take place:
-	at inter AMF change due to AMF planned maintenance or due to AMF failure described in clause 5.21.2 of TS 23.501 [2];

New AMF ID in SMF session context for 'inter-AMF change or mobility'

---

src/amf/context.c
src/amf/context.h
src/amf/gmm-sm.c
src/amf/ngap-path.c
src/amf/timer.c
src/amf/timer.h

Two timers are introduced (both with duration of T3512 + 4 min):
-MOBILE_REACHABLE
-IMPLICIT_DEREGISTRATION
MOBILE_REACHABLE is set when NAS connection for the UE is released.
IMPLICIT_DEREGISTRATION is set when MOBILE_REACHABLE expires.
On MOBILE_REACHABLE expiry Paging is ignored.
On IMPLICIT_DEREGISTRATION expiry:
-UE's RM_State is set to DEREGISTERED
-UE is Nudm_SDM_Unsubscribed
-UE is Nudm_UECM_Deregistered
-PDU sessions are released
-AM policies are deleted
Existing flag amf_ue->network_initiated_de_reg is used.

[AMF] Implicit Network-initiated Deregistration

---

lib/diameter/s6a/message.h
lib/gtp/xact.h
src/mme/esm-sm.c
src/mme/mme-context.h
src/mme/mme-fd-path.c
src/mme/mme-fd-path.h
src/mme/mme-gtp-path.c
src/mme/mme-path.c
src/mme/mme-s11-handler.c
src/mme/mme-s6a-handler.c
src/mme/mme-s6a-handler.h
src/mme/mme-sm.c
src/mme/nas-path.c
src/mme/s1ap-handler.c

This pull requests adds the Purge-UE procedure to the MME based on 29.272 5.2.1.3.  The Purge-UE event here is triggered after a failed location update which the MME removes the subscriber information.  The MME informs the HSS that the subscriber's profile has been deleted from the MME.  The procedure is followed when the MME is initiating the removal of the subscriber information after a successful ULR/ULA exchange with the HSS.  Purge-UE is not need when the HSS sends a Cancel Location request, as the UE is marked as purged at MME at that time.  This procedure can be used for other events where the subscriber information is deleted such as O&M operators or timer based subscriber deletion.
The Open5GS HSS currently supports PUR functionality.

[MME] Add Purge-UE Capability

---

src/amf/amf-sm.c
src/ausf/ausf-sm.c
src/bsf/bsf-sm.c
src/pcf/pcf-sm.c
src/scp/scp-sm.c
src/smf/smf-sm.c
src/udm/udm-sm.c
tests/af/af-sm.c

<nf>/init.c:<nf>_main() :
ogs_pollset_poll() receives the time of the expiration of next timer as an argument. If this timeout is in very near future (1 millisecond), and if there are multiple events that need to be processed by ogs_pollset_poll(), these could take more than 1 millisecond for processing, resulting in the timer already passed the expiration.
In case that another NF is under heavy load and responds to an SBI request with some delay of a few seconds, it can happen that ogs_pollset_poll() adds SBI responses to the event list for further processing, then ogs_timer_mgr_expire() is called which will add an additional event for timer expiration. When all events are processed one-by-one, the SBI xact would get deleted twice in a row, resulting in a crash.
0  __GI_abort () at …

[NF] Fix double-free crash when NF is under heavy load

---

src/amf/namf-handler.c
src/smf/context.h
src/smf/gsm-sm.c
src/smf/pfcp-sm.c

SMF detects UPF failover by checking PFCP Heartbeats and perform transfer to new UPF (could be same after restart) according to 3GPP 23.502, chapter 4.3.5.1
All PDU sessions on failed UPF are released with cause OGS_5GSM_CAUSE_REACTIVATION_REQUESTED and so UE requests new PDU session that can be establish on some other UPF (if exists)

Support for UPF HA - release/establish new PDU session

---

lib/sbi/nghttp2-server.c

This is in line with the implementation with microhttpd server (mhd-server.c).

[SBI] Do not treat removed streams as errors when sending responses

---

lib/pfcp/xact.c

As written, if the node encounters any sort of socket()/sendto() related errors it goes to out:, calls pfcp_xact_delete() without setting any new timers, and then this side of the connection never sends any further messages. This fix is super easy: we just log the error and return, the actual problem is handled by the rest of the system (timeouts etc), the next timer gets set, and code proceeds as normal.
I know that socket()/sendto() errors are somewhat uncommon over localhost, but they definitely pop up in a lot of real-world deployment contexts, especially when VPNs or other tunneling software is used - that's actually how I found this issue in the first place.

[pfcp] response_timeout should not call ogs_pfcp_xact_delete

---

src/sgwc/s11-handler.c

In this context GTP hasn't failed, it's actually working correctly. When a UE rejoins the network due to buffered data, there's essentially a slight "race condition" between the UE rejoining the network via MME and the SGWC sending a downlink data notification to the MME. if the UE wins, then the MME simply tells the SGWC that the UE has already re-attached. This is essentially a no-op operation and IMO should be handled silently, not logged as a GTP Failure.

[sgwc] silently handle downlink data ack when ue already reattached

---

src/upf/context.c

Sorry, I introduced undefined behavior in 990abbab2cddafec14c7b1cfaa605ea88b46bd7b. This should fix it.

Don't left-shift by negative amount, which is UB according to C17

---

src/amf/gmm-sm.c
src/mme/emm-sm.c

Running the unit tests, we can observe the additional check in action:
```
reset-test          : /02/24 08:08:20.996: [gmm] ERROR: [(null)] Handling service request failed [Not registered] (../src/amf/gmm-sm.c:1068)
```
reset-test:test1_func() sends a service request without prior registration.

[AMF] Disallow handling service requests unless UE is already registered

---

src/amf/gmm-handler.c
src/amf/gmm-sm.c
src/amf/metrics.c
src/amf/metrics.h
src/amf/nas-path.c
src/amf/ngap-path.c

[ETSI TS 128 552 V16.9.0](https://www.etsi.org/deliver/etsi_ts/128500_128599/128552/16.09.00_60/ts_128552v160900p.pdf)
5.2.2 Registration procedure related measurements
SNSSAI labels are not provided.
- Number of registration requests received by the AMF is exposed for each registration type.
```
fivegs_amffunction_rm_reginitreq 1
fivegs_amffunction_rm_regmobreq 0
fivegs_amffunction_rm_regperiodreq 0
fivegs_amffunction_rm_regemergreq 0
```
- Number of successful initial registrations at the AMF is exposed for each registration type.
```
fivegs_amffunction_rm_reginitsucc 1
fivegs_amffunction_rm_regmobsucc 0
fivegs_amffunction_rm_regperiodsucc 0
fivegs_amffunction_rm_regemergsucc 0
```
- The existing counter of failed registrations at the AMF is exposed separately for each registration …

[AMF] Expose more metrics

---

lib/gtp/v2/types.h
lib/nas/5gs/types.h
lib/nas/common/types.h
lib/nas/eps/types.h
lib/pfcp/types.h
src/amf/gmm-build.c
tests/common/emm-build.c

As raised in #2147, AMF fails to decode S1 UE Network Capability.
So I reviewed all IE in NAS, GTP and PFCP and fixed it for Release-17.

[NAS/GTP/PFCP] Upgrade IE to Release-17

---

src/amf/gmm-sm.c

In case that handling Service Request results in an error, AMF sends a Service Reject and sets UE's context to exception state. Without the 'break', the code would set UE's context to registered state.

[AMF] Fix handling Service Request

---

src/pcf/npcf-handler.c

When both IPv4 and IPv6 Frame Routes are set, IPv4 Frame Route list was subsequently cleared.
When UE tried to deregister, PCF would crash when it tried to free the Frame Routing list.

[PCF] Fix crash when both IPv4 and IPv6 Frame Routes are set

---

src/amf/namf-handler.c

When UDM issues a SDM Data Change Notification with request to modify RAT restrictions, AMF would crash when it tried to send a SDM subscription delete as part of Network Initiated Deregistration.
Function amf_ue_sbi_discover_and_send() changed from returning boolean, to returning integer (one of OGS_OK/OGS_ERROR/...).

[AMF] Fix Network Initiated Deregistration

---

src/amf/npcf-build.c
src/amf/nsmf-build.c
src/pcf/nbsf-build.c
src/pcf/npcf-handler.c
src/pcf/nsmf-build.c

SMF already handles the freeing in labels correctly. In the same manner the memsets are moved to the beginning of the problematic functions in AMF and PCF.

[AMF, PCF] Don't free unallocated memory

---

configs/open5gs/amf.yaml.in
configs/open5gs/mme.yaml.in
configs/open5gs/smf.yaml.in
lib/nas/5gs/types.c
lib/nas/5gs/types.h
lib/nas/eps/types.c
lib/nas/eps/types.h
lib/pfcp/context.c
lib/proto/types.h
src/amf/context.c
src/amf/context.h
src/amf/gmm-build.c
src/mme/emm-build.c
src/mme/mme-context.c
src/mme/mme-context.h
src/smf/context.c
tests/common/context.c
tests/common/context.h
tests/unit/nas-message-test.c

You can configure TAI using **RANGE** as below.
```
amf:
tai:
- plmn_id:
mcc: 002
mnc: 02
tac: [6-10, 15-18]
mme:
tai:
- plmn_id:
mcc: 002
mnc: 02
tac: [30-32, 34, 36-38, 40-42, 44, 46, 48]
```
When multiple TAIs are configured as shown below, the Served TAI is determined by comparing UserLocationInformation of UplinkNASTransport sent from gNB.
For example, if the gNB sends TAC with 30 to the AMF, the fourth TAI (TAC: 20, 28, 29-32, 36-38, 40-42, 50, 60, 70, 70) is determined as the Served TAI. The result is transmitted to the gNB as a Tracking Area identity List in Registration Accept.
```
amf:
tai:
- plmn_id:
mcc: 001
mnc: 01
tac: [1, 3, 5]
tai:
- plmn_id:
mcc: 002
mnc: 02
tac: [6-10, 15-18]
tai:
- plmn_id:
mcc: 003
mnc: 03
tac: 20
- plmn_id:
mcc: 004
mnc: 04
tac: 21
tai:
- plmn_id: …
```

Introduce TAI Range in the AMF/MME configuration

---

src/upf/gtp-path.c

Discussion #2208, #2209
Metrics reduce data plane performance.
It should not be used on the UPF/SGW-U data plane until this issue is resolved.
close #2210

[UPF] Remove Metrics in Data Plane (#2210)

---

lib/pfcp/build.c
lib/pfcp/context.c
lib/pfcp/context.h
lib/pfcp/handler.c
lib/pfcp/handler.h
lib/pfcp/path.c
lib/pfcp/xact.c
lib/pfcp/xact.h
src/amf/context.c
src/amf/context.h
src/amf/gmm-handler.c
src/amf/namf-handler.c
src/amf/nsmf-handler.c
src/pcf/context.c
src/sgwc/pfcp-sm.c
src/sgwu/context.c
src/sgwu/pfcp-sm.c
src/smf/pfcp-sm.c
src/upf/context.c
src/upf/pfcp-sm.c
tests/app/5gc-init.c
tests/handover/5gc-n2-test.c

TS23.007
19A PFCP based restart procedures
TS23.527
4 Restoration Procedures related to the N4 Interface
When a SGW-U/UPF detects that a peer PFCP entity in the SGW-C/SMF has restarted (as specified in clause 4.2), the SGW-U/UPF shall delete all session contexts affected by the PFCP entity restart that it may have stored.
The part where SGW-C/SMF detects that SGW-U/UPF's peer PFCP entity has been restarted has not yet been implemented. We should implement that the SGW-C/SMF sends PFCP Session Establishment Request message to the SGW-U/UPF with RESTI(restoration indication), which is a bit complicated.
I will try this out soon.

[PFCP] SGWU/UPF Restoration

---

src/smf/gy-path.c

as per discussion here #2204 the default Service-Context-Id costant is not compliant with 3gpp specs [3GPP 32.299 7.1.12](https://www.etsi.org/deliver/etsi_ts/132200_132299/132299/10.07.00_60/ts_132299v100700p.pdf)

[SMF] Fixed Gy Service-Context-Id

---

docs/_pages/support.md
lib/sbi/context.c
lib/sbi/context.h
lib/sbi/nnrf-build.c
lib/sbi/nnrf-handler.c
src/bsf/context.h
src/bsf/nbsf-handler.c
src/nssf/context.c
src/pcf/nbsf-build.c
tests/af/context.c
tests/af/context.h
tests/af/nbsf-handler.c

If FQDN is used, the default ports (HTTP:80, HTTPS:443) are used. HTTP:80 works fine, but HTTPS:443 fails to connect when using TLS. Fixed an issue where SBI connections do not work properly when FQDN and TLS are used together.

[SBI] Fixed an issue with FQDN/TLS (#2252)

---

src/upf/context.c
src/upf/context.h
src/upf/n4-handler.c

SMF started to provide APN/DNN in PFCP Establishment. APN/DNN is used to provide dnn label of metric fivegs_upffunction_upf_qosflows.

[UPF metrics] Use APN/DNN to expose dnn label

---

docs/_docs/guide/01-quickstart.md

On ubuntu 22.04 (Jammy)
```bash
$ echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
```

FIX:  22.04 (jammy) gpg keyring addition

---

configs/open5gs/mme.yaml.in
src/mme/mme-context.c
src/mme/mme-context.h
src/mme/mme-gtp-path.c
src/mme/mme-s11-build.c

This pull request is for https://github.com/open5gs/open5gs/discussions/1127.
At Initial Attach, MME can select SMF corresponding to TAC or e_CellID according to connected eNodeB, and select the neaby UPF (PGW-U).
`mme.yaml`
```
#
#
#
```

[MME] add facility to select smf(pgwc) by tac and e_cell_id

---

src/amf/gmm-handler.c

When the served_tai_index < 0 the open5gs crashes because its being used as index into an array.

[AMF] Fixed crash if served_tai_index < 0 (#2059)

---

src/amf/context.c
src/mme/mme-context.c

Add 0xc000000 when assigning M-TMSI. However, this value was not reset on release. So in the next allocation, 0xc000000 was automatically added, causing this problem.

[AMF/MME] Fixed crashes by M-TMSI (#2307)

---

src/smf/metrics.c
src/smf/metrics.h
src/smf/nsmf-handler.c
src/smf/nudm-handler.c
src/smf/sbi-path.c
src/smf/smf-sm.c

[ETSI TS 128 552 V16.9.0](https://www.etsi.org/deliver/etsi_ts/128500_128599/128552/16.09.00_60/ts_128552v160900p.pdf):
Registration type label is not provided.
A nonstandard PLMNID label is added to achieve uniqueness.
- 5.3.1.3 Number of PDU sessions requested to be created by the SMF
PLMNID and SNSSAI are defined during PDU session creation processing. Some requests can be rejected during processing before label values are known. Those requests are not counted under particular labels. To count also such requests, the basic metric with empty labels is exposed too.
```
fivegs_smffunction_sm_pdusessioncreationreq{plmnid="",snssai=""} 1
fivegs_smffunction_sm_pdusessioncreationreq{plmnid="00101",snssai="1000009"} 1
```
- 5.3.1.4 Number of PDU sessions successfully created by the SMF
``` …
```

[SMF] Expose metrics for nr. of PDU session creations

---

src/smf/fd-path.c
src/smf/fd-path.h
src/smf/gx-path.c
src/smf/gy-path.c

Now "3GPP-User-Location-Info" located in the wrong place.
at according 3GPP TS 32.299 "3GPP-User-Location-Info" is 3GPP specific AVP, which used in CCR,
and must locate on top level, as below:

[SMF] relocation of user-location-info on top level for Gx,Gy

---

src/hss/hss-swx-path.c

Multimedia-Auth-Answer and Server-Assignment-Answer defines the AVP User-Name as mandatory. It must also be present on failure cases.
See 3GPP TS 29.273 Rel 17.
Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

[HSS] SWx: SAR & MAR: set mandatory User-Name on failure cases

---

lib/core/ogs-pool.h
lib/pfcp/context.c
src/mme/mme-context.c
src/smf/context.c

ogs_pool_init() shall be used in the initialization routine. Otherwise, memory will be fragment since this function uses system malloc()
Compared with ogs_pool_init()
ogs_pool_create() could be called while the process is running, so this function should use ogs_malloc() instead of system malloc()

[CORE] Rollback ogs_pool_init/final (#2339)

---

src/smf/npcf-handler.c

Similar to how SMF sends UE ip address in bot UL and DL pdrs, it makes sense to send framed routes as well.

[SMF/PFCP] Send framed routes in both UL and DL pdrs

---

src/smf/gx-path.c
src/smf/gy-path.c

The current code uses the cc request number as an index to the transaction array (xact/xact_data). Since cc request number is a 32 bit integer this is unfeasible for longer sessions and if more than a handful of messages are exchanged per session.
The array size was already increased in #2038 which simply delays the issue.
Furthermore, the current code asserts that cc_request_number is <= MAX_CC_REQUEST_NUMBER which leads to an out-of-bounds write if cc_request_number == MAX_CC_REQUEST_NUMBER.
Instead use a smaller array and index into it using cc_request_number % array size. More than 2 requests should never be in flight at any one time (initial or update request together with a termination request) so an array size of 4 should be fine.

[SMF] Fix Gx/Gy assert() if more than 64 CCRs are sent

---

src/smf/context.c

Since [redesign](https://github.com/open5gs/open5gs/commit/8553c77733f50f82bfa6a9a4ee57f7ca0133a815) of fivegs_smffunction_sm_sessionnbr gauge, the metric doesn't expose some decrements. The decreasing of gauge had been moved out of function stats_remove_smf_session.
It should be decreased every time stats_remove_smf_session is called, but this particular case is easily reproducible by killing UPF while the session is established.

[SMF] Decrease sessions metric on OLD Session Release

---

docs/_docs/hardware/01-genodebs.md

We successfully tested the BTI Wireless nCELL-F2240 Femto Cell together with Open5GS and a Quectel RM520N-GL modem in the N78 band (in Germany)!.

BTI Wirelss Femto Cell nCELL-F2240 added

---

src/amf/context.c

Each SMF's NfProfile can contain multiple SmfInfo items. The issue was that AMF checked only the first SmfInfo for correct S-NSSAI/NR-TAI information.
In case of a 5G core setup with SMF handling 2 or more slices, and UE trying to establish multiple PDU sessions, AMF would report an error when trying to find the correct serving SMF.
[amf] ERROR: [1:0] (NF discover) No [nsmf-pdusession] (../src/amf/nnrf-handler.c:85)

[AMF] Fix search for correct SMF based on SmfInfo

---

src/upf/arp-nd.cpp

Playing around with using Open5gs on a flat network and discovered that the UPF was restarting frequently when the interface was changed to a TAP device, usually once every few seconds.
Traced the issue back to Tins throwing a Tins::pdu_not_found error.  The is_nd_req() function in upf/arp-nd.cpp runs every IPv6 message reveived on a TAP interface against a Tins rfind_pdu() call to try and detect the type of ND message it might contain, but in the case that the message did not contain any ICMPv6 payload, Tins throws an exception.  
This means that any "normal" IPv6 message can crash the UPF, in my case it was a stray mDNS packet.
Patched to catch the exception and return false, as a packet not containing an ICMPv6 payload cannot ever be an ICMPv6 NEIGHBOUR_SOLICIT request.
Tested working …

fix crashing of UPF with interface in TAP mode

---

docs/_docs/platform/05-macosx-apple-silicon.md

Trying to build Open5GS from sources on an M1 Mac, I noticed that the documentation specifies an incorrect config path for running MongoDB (c.f. the respective page in the [MongoDB documentation](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/#install-mongodb-community-edition)). This PR simply updates the docs with the correct path, resolving the issue.

mac: fix mongodb config path for Apple Silicon

---

src/nrf/nrf-sm.c

This is a fix for bug #2417 by adding:
1. A check whether the NRF ID is null, before searching an NRF instance based on the ID which led to the bug in the first place
2. A separate switch case for OPTIONS requests to `/nnrf-nfm/v1/nf-instances` which will be replied to with a 501 `Not Implemented`
fixes #2417

[NRF] Fix crash due to failing assertion on OPTIONS request

---

.github/workflows/cifuzz.yml

Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This service is offered by OSS-Fuzz where open5gs already runs. CIFuzz can help catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.

Add CIFuzz workflow

---

lib/gtp/xact.c

The xarg->org is set to a specific value above in the same function, so no need to check for its value.

gtp: xact: Fix unneeded conditionals

---

lib/gtp/xact.c

The RAN INFORMATION RELAY message has no associated response, and hence it should not start T3-RESPONSE timer to retrigger retransmissions.
TS 29.060 11.1:
"The Error Indication, Version Not Supported, RAN Information Relay,
Supported Extension Headers Notification and the SGSN Context Acknowledge
messages shall be considered as Responses for the purpose of this clause"
TS 29.060 7.5.14.1:
"For handling of protocol errors the RAN Information Relay message is treated as a
Response message."

gtp1: Add missing RAN INFORMATION RELAY msg

---

src/mme/mme-fd-path.c

The 'data' struct used to specify the diameter dispatch options for the MME callbacks was not being initialized properly, which meant that the App id could contain garbage. This was preventing the callbacks from being invoked when receiving ISD/CLR requests.

mme: fix missing memset in mme_fd_init

---

src/amf/gmm-sm.c
src/amf/ngap-handler.c
src/amf/nsmf-handler.c

When AMF release the NAS signalling connection,
ran_ue context is removed by ran_ue_remove() and
amf_ue/ran_ue is de-associated by amf_ue_deassociate().
In this case, implicit deregistration is attempted by the mobile reachable timer according to the standard document, and amf_ue will be removed by amf_ue_remove().
TS 24.501
5.3.7 Handling of the periodic registration update timer and
Start AMF_TIMER_MOBILE_REACHABLE
mobile reachable timer
The network supervises the periodic registration update procedure of the UE by means of the mobile reachable timer.
If the UE is not registered for emergency services, the mobile reachable timer shall be longer than the value of timer T3512. In this case, by default, the mobile reachable timer is 4 minutes greater than the value of timer T3512.
The …

[AMF] Implicit Deregistration (Reset, ConnRefused)

---

configs/open5gs/mme.yaml.in
src/mme/mme-context.c

Move the config to the sgsn node instead of having a specific route with specific format "default: route", since anyway internally it's already applied to the sgsn object.
Should fix the problem reported in https://github.com/open5gs/open5gs/pull/2441#issuecomment-1642034949

[MME] rework sgsn default route config in mme.yaml

---

src/upf/arp-nd.cpp
src/upf/arp-nd.h
src/upf/gtp-path.c

Checks if the target IP address of an ARP message is associated with a session before replying to it.  Fixes an issue I ran into where the UPF will ARP-poison every other device on the network by replying to every ARP request as if it holds that IP.
Didn't notice this was happening at first until it commandeered my gateway's IP...
It is possible the same (or similar) is happening with IPv6 ND messages, but I do not have the hardware or network configuration to test that correctly.
All changed code-paths are isolated to TAP interface mode, and these changes are working reliably on my test network.

[UPF] fix tap mode arp table poisoning

---

docs/_docs/tutorial/03-VoLTE-dockerized.md

Updating some names: 
Based on naming scheme in docker_open5gs these need changed
kamailio_base -> ims_base 
open5gs_kamailio -> docker_kamailio
docker-compose is the old version so that's been changed as well to the new "docker compose"

Update VoLTE Dockerized Tutorial

---

src/upf/n4-handler.c

After usual single QoS flow PDU session establishment/deletion negative metric is exposed:
`fivegs_upffunction_upf_qosflows{dnn="internet"} -3`

[UPF] Fix wrong number of QoS flows metric

---

src/amf/context.c
src/amf/gmm-build.c
src/amf/gmm-build.h
src/amf/gmm-sm.c
src/amf/nas-path.c
src/amf/nudm-handler.c

Changed to that registration can be accepted only when the UE slice is available in the RAN slice.
See the following the standard document in TS23.502
```
4.2.2 Registration Management procedures
4.2.2.2 Registration procedures
4.2.2.2.2 General Registration
21. ...
If the Requested NSSAI does not include S-NSSAIs which map to S-NSSAIs
of the HPLMN subject to Network Slice-Specific Authentication and
Authorization and the AMF determines that no S-NSSAI can be provided
in the Allowed NSSAI for the UE in the current UE's Tracking Area and
if no default S-NSSAI(s) not yet involved in the current UE Registration
procedure could be further considered, the AMF shall reject the UE
Registration and shall include in the rejection message the list
of Rejected S-NSSAIs, each of them with the …
```

UE slice shall be also available in RAN (#2482)

---

docs/_docs/troubleshoot/02-now-in-github-issues.md
lib/dbi/session.c
lib/dbi/subscription.c
lib/gtp/v2/types.c
lib/gtp/v2/types.h
lib/nas/common/types.c
src/pcf/nbsf-handler.c
src/pcf/nudr-handler.c
src/smf/gn-handler.c
tests/common/gsm-build.c

NAS, GTP, PFCP, SBI, all except S1AP/NGAP use x1000 multiplier for Kbps, Mbps, Gbps ... etc.
From now on in WebUI all units also use a multiplier of x1000.

Use x1000 multiplier for Kbps, Mbps, ... etc.

---

src/smf/gsm-sm.c
src/smf/nsmf-handler.c
tests/vonr/session-test.c

A situation in which you establish two sessions and release both of them.
In the first SESSION, the UE normally sent PDUSessionResourceReleaseResponse and PDU session release complete. However, these were not sent when releasing the second SESSION.
At this point, when the UE tried to do a deregistration, the SMF was not properly handling the exception.
I've just fixed this.

[SMF] Deregister issue during sess release (#2537)

---

src/udm/context.c
src/udm/udm-sm.c

Modifications were made to resolve the following assertion..
Invalid HNET PKI Value [0] (../lib/sbi/conv.c:135) ogs_supi_from_supi_or_suci: Expectation `supi' failed. (../lib/sbi/conv.c:262) udm_ue_add: Assertion `udm_ue->supi' failed. (../src/udm/context.c:144) backtrace() returned 8 addresses (../lib/core/ogs-abort.c:37)

[UDM] Fixed crash for invalid SUCI (#2571)

---

lib/pfcp/context.c

After examining the call stack and reading the source code, I found that in /lib/core/ogs-pool.h line 152: (pool)->array[i] = i+1; then in lib/pfcp/context.c line 78: pdr_random_to_index[ogs_pfcp_pdr_teid_pool.array[i]] = i; ogs_pfcp_pdr_teid_pool.array[i] may exceed the size of pdr_random_to_index, leading to a heap-buffer-overflow.

[PFCP] Fixed Possible heap buffer overflow (#2585)

---

src/smf/context.c
src/smf/smf-sm.c

curl --noproxy '*' --http2-prior-knowledge -X POST --header "Content-Type: multipart/related" --data-binary @pdu http:/192.168.29.231:7777/nsmf-pdusession/v1/sm-contexts Attaching file 'pdu'
SMF crashes as not able to decode the message properly. SmContextCreateData is not accessible.

[SMF] Invalid Message(SmContextCreateData) (#2590)

---

lib/gtp/util.c
lib/gtp/util.h
lib/gtp/v2/build.c
lib/gtp/v2/path.c
lib/gtp/v2/path.h
lib/gtp/v2/types.h
lib/pfcp/handler.c
lib/pfcp/handler.h
lib/pfcp/path.c
lib/pfcp/path.h
src/sgwu/gtp-path.c
src/smf/gtp-path.c
src/upf/gtp-path.c
tests/common/gtpu.c
tests/common/gtpu.h

Scenario is handover on S1AP, data forwarding is enabled, and the Source ENB is forwarding DL PDCP packets to EPC(SGWU) with PDCP SN included. SGWU is also forwarding these packets to the Target ENB.
However the PDCP SN is not present in the forwarded packets from SGWU to Target ENB.
I modified this part, and there was the same problem in 5GC, fixed it as well.
A lot of code in GTP-U has been modified,
so if you have any problems, please let us know right away.

[GTPU] Fixed PDCP SN handling (#2584, #2477)

---

webui/src/components/Account/Edit.js
webui/src/components/Profile/Edit.js
webui/src/components/Subscriber/Edit.js

After the page remains inactive for 10 minutes,
clicking on the edit page will result in a blank screen
when you click on edit after 10 minutes,
all user data is lost. After capturing the network packets, it can be observed that the frontend sends a fresh request to the backend for data, and the backend responds correctly, but the page does not refresh correctly.
`function recent(fetchedAt) {
if (fetchedAt === null) return false;
const interval = 10 * 60 * 1000; // 10 minutes
return ((Date.now() - interval) < fetchedAt);
}`

[WebUI] fixed a EDIT bug after 10 minutes (#2615)

---

lib/ipfw/ipv6.c

```sh
valgrind --leak-check=full --show-leak-kinds=all src/upf/open5gs-upfd -c ./configs/open5gs/upf.yaml
09/27 12:36:43.704: [app] INFO: UPF terminate...done (../src/upf/app.c:39)
==2320446== 
==2320446== HEAP SUMMARY:
==2320446==     in use at exit: 120 bytes in 3 blocks
==2320446==   total heap usage: 2,984 allocs, 2,981 frees, 505,391,902 bytes allocated
==2320446== 
==2320446== Thread 1:
==2320446== 24 bytes in 2 blocks are definitely lost in loss record 1 of 2
==2320446==    at 0x4841848: malloc (vg_replace_malloc.c:431)
==2320446==    by 0x4E863EE: strdup (strdup.c:42)
==2320446==    by 0x50A33ED: fill_ip6 (ipv6.c:378)
==2320446==    by 0x50A37F5: add_srcip6 (ipv6.c:498)
==2320446==    by 0x5099A5D: add_src (ipfw2.c:3421)
==2320446==    by 0x509B54D: compile_rule (ipfw2.c:4011) …
```

[ipfw] Fix memory leak when parsing ipv6

---

webui/package-lock.json
webui/package.json

I've fixed the following error.
```bash
$ npm clean-install
$ npm run build
> Using external babel configuration
> Location: "/tmp/open5gs-2.6.5/webui/.babelrc"
> Failed to build on /tmp/fdd1769d-9793-45ac-a613-b20e09756073
Error: commons.js from UglifyJs
Name expected [commons.js:8066,6]
at /tmp/open5gs-2.6.5/webui/node_modules/next/dist/server/build/index.js:182:21
at /tmp/open5gs-2.6.5/webui/node_modules/webpack/lib/Compiler.js:269:13
at Compiler.emitRecords (/tmp/open5gs-2.6.5/webui/node_modules/webpack/lib/Compiler.js:375:38)
at /tmp/open5gs-2.6.5/webui/node_modules/webpack/lib/Compiler.js:262:10
at /tmp/open5gs-2.6.5/webui/node_modules/webpack/lib/Compiler.js:368:12
at next (/tmp/open5gs-2.6.5/webui/node_modules/tapable/lib/Tapable.js:218:11)
at Compiler.<anonymous> …
```

[WebUI] Fixed when running 'npm run build' (#2564)

---

.gitignore

Open5GS documentation instructs to install into open5gs.git/install/ during build [1]:
"""
$ cd open5gs
$ meson build --prefix=`pwd`/install
$ ninja -C build
"""
As a result, this directory appears all the time when using git, since it's not in the .gitignore file. Add it.
[1] https://open5gs.org/open5gs/docs/guide/02-building-open5gs-from-sources/

.gitignore: Add install/ dir

---

src/smf/s5c-handler.c

currently, if no IP address is available from the configured subnets in the SMF when attempting to assign an IP to an UE, we assert and the SMF crashes. Handle the error more gracefully by returning an error cause instead.

smf: don't assert if we run out of IPs

---

src/amf/context.h
src/amf/gmm-sm.c
src/amf/nausf-handler.c
src/mme/emm-sm.c
tests/registration/auth-test.c

amf_ue->mac_failed flag to be cleared during security mode procedure but it was not. At this point, the only way to cleare the amf_ue->mac_failed flag is by UE Context Release. But I'd like to connect UEs as fast as possible without UE Context Release.

[AMF] mac_failed should be initialized (#2679)

---

src/amf/context.c
src/mme/mme-context.c

When configuring the TAC in the amf.yaml, if it is configured as tac: [1-2], it will report a configuration error "No amf.tai.plmn_id|tac in '/xxx/amf.yaml'".

[AMF] Fixed TAC configuration error (#2700)

---

src/amf/gmm-sm.c
src/ausf/ausf-sm.c
src/ausf/ausf-sm.h
src/ausf/nudm-handler.c
src/ausf/ue-sm.c

- Fix AUSF crashing when removing ausf_ue context
- Delete authentication data from AUSF on UE deregistration
Based on TS 29.509 - 5.2.2.2.5 Authentication Result Removal with 5G method:
In the case that the Purge of subscriber data in AMF after the UE
deregisters from the network or the NAS SMC fails following the
successful authentication in the registration procedure, the NF Service
Consumer (AMF) requests the AUSF to inform the UDM to remove the
authentication result.

Delete authentication data on UE deregistration

---

lib/sbi/context.c
lib/sbi/nf-sm.c
lib/sbi/nnrf-handler.c
lib/sbi/path.c

This problem can be occurred in the following scenarios.
1. Run NFs(NRF/SCP/SMF/UPF/AUSF/UDM/PCF/BSF/NSSF/UDR) except AMF.
2. Run AMF
3. Run gNB/UE and try to register
4. STOP PCF
5. AMF Crashed
AMF discovered the PCF through SCP during the UE registration process.
At this time, ogs_sbi_nf_fsm_init() is not called, so AMF does not have state information about PCF.
In other words, AMF state is NULL.
In such a situation, when PCF is terminated at this time, a crash occurs as AMF attempts to change the PCF state.
So, I've fixed that state information is initialized to solve this problem.

[AMF] Fixed crash in ogs_fsm_tran(!tmp) (#2719)

---

lib/asn1c/common/BIT_STRING_jer.c
lib/asn1c/common/OCTET_STRING_jer.c
lib/asn1c/common/asn_internal.h
lib/asn1c/common/asn_random_fill.c
lib/asn1c/common/constr_CHOICE_aper.c
lib/asn1c/support/README.md
tests/unit/crash-test.c

A malformed ASN.1 S1AP packet may be used to overwrite a pointer to a struct with data beyond the end of an array (buffer overflow). This can lead to a Denial of Service attack by an attacker repeatedly sending these packets. Additionally, the struct contains function pointers that are subsequently called; certain installations may be vulnerable to remote code execution as a result.
Crashing Input Examples (Base64 encoded):
a)
ACZAYwAACgB6QA8gBNIipkUAv0jzKBcLt1sAekACAAAAekACAAAAekAE9QI9TQB6UAIAAAB6QAMAAVoAekALIAAAj8X4nkVWSmZ6C0AMIAHMAKzE5zgAg72TAHpAAwABgwB6QAIAAA==
b) ACVAWgAACgB5QAsgAAAfZBElvWBQIQB5QAIAAAB5QAYABGgOmQkAeUACAAAAeUACAAAAeUAPIAQkjCirADXNVuo9rz91AHlAAgAAAHlAA/8B9gB5QAIA6gB5QAIAAA==
Steps to reproduce:
aper_decode() with the above decoded base64 payload
Observe segmentation …

[ASN.1] Fix buffer overflow (mouse07410/asn1c#134)

---

lib/sbi/context.c
lib/sbi/message.c
lib/sbi/message.h
lib/sbi/path.c
src/amf/gmm-handler.c
src/amf/nnssf-handler.c
src/nrf/nnrf-handler.c

According to 3GPP TS 29.510, the search parameter "tai" should be a single item, not an array of items.
TS 29.510: Table 6.2.3.2.3.1-1:
URI query parameters supported by the GET method on this resource

[SBI] Change discovery option TAI from array to single item

---

src/amf/gmm-sm.c

Bug:
In case that AMF does not have subscription data for the UE, PDU session remains unreleased after implicit de-registeration.
The exact test case:
- UE registered (integrity protection applied)
- UE deregistered (Nudm_SDM_Unsubscribe, Nudm_UECM_Registration (purgeFlag))
- UE registered, PDU session activated
UE data are still stored in AMF. So if integrity protected applies,
the steps 4 - 14 [ETSI TS 123 502 V16.7.0](https://www.etsi.org/deliver/etsi_ts/123500_123599/123502/16.07.00_60/ts_123502v160700p.pdf) are skipped.
Only AM Policy Association Establishment is performed.
- UE is moved out of radio coverage, 2 x (4 min + Timer t3512) expires
Result: UE is implicitly de-registered, PDU session is not released
The steps of implicit de-registeration:
1. Implicit Timer Expiration
2. …

[AMF] Fix Nudm_SDM_Get for re-registration

---

.editorconfig

Add a file that allows editors to automatically use the right indentation format when working with the open5gs source tree.

editorconfig: new file

---

lib/app/ogs-config.c
lib/app/ogs-config.h
src/amf/gmm-build.c
src/mme/emm-handler.c

Allow network operators to omit the local time zone in the EMM information. This is useful for better compatibility with some UEs.
According to 3GPP TS 124.301 Table 8.2.13.1, the parameter is optional.

[MME] Add no_time_zone_in_emm_information param

---

lib/core/ogs-epoll.c

If EPOLLIN, EPOLLOUT, and EPOLLRDHUP occur at the same time, Linux generates a SIGPIPE signal as below.
```
11/13 16:55:43.340: [core] INFO: after eopll_process , num_of_poll is 1 (../lib/core/ogs-epoll.c:215)
11/13 16:55:43.340: [core] INFO: received: 2005 (../lib/core/ogs-epoll.c:230)
11/13 16:55:43.340: [core] INFO: EPOLLIN event occurred (../lib/core/ogs-epoll.
11/13 16:55:43.340: [core] INFO: EPOLLOUT event occurred (../lib/core/ogs-epoll.c:259)
11/13 16:55:43.340: [core] INFO: EPOLLRDHUP event occurred (../lib/core/ogs-epoll.c:263)
11/13 16:55:43.340: [amf] DEBUG: SCTP_SHUTDOWN_EVENT:[T:32773, F:0x0, L:12] (../src/amf/ngap-sctp.c:191)
11/13 16:55:43.340: [amf] INFO: ogs_queue_push amf_sctp_event_push (../src/amf/event.c:104)
```
I've made modifications so that when EPOLLRDHUP …

[SCTP] Fixed a crash on SIGPIPE (#2734)

---

src/smf/context.c
src/smf/gtp-path.c

SLAAC RA sent by the network should contain ICMPv6 option type 5 (MTU) field.

[IPv6] Fixed to include MTU in SLAAC RA (#2754)

---

lib/proto/types.h
src/amf/context.c
src/amf/context.h
src/amf/gmm-build.c
src/amf/ngap-handler.c
src/mme/emm-build.c
src/mme/mme-context.c
src/mme/mme-context.h
src/mme/s1ap-build.c
src/mme/s1ap-handler.c
tests/common/context.c
tests/common/context.h

I have reset the number of TA, SLICE, and PLMN supported by AMF/MME as follows.
- From lib/proto/types.h
```
define OGS_MAX_NUM_OF_SERVED_GUMMEI    8   /* maxnoofRATs: 8 */
#define OGS_MAX_NUM_OF_SERVED_GUAMI     256 /* maxnoofServedGUAMIs: 256 */
#define OGS_MAX_NUM_OF_SUPPORTED_TA     256 /* maxnoofTACs: 256 */
/*
* If I set it to 1024, the AMF crashes in the 'meson test -v registration'.
* So for now, I will use 512. Once I figure out the cause of this problem,
* I will try 1024.
*/
#define OGS_MAX_NUM_OF_SLICE_SUPPORT    512 /* maxnoofSliceItems: 1024 */
#define OGS_MAX_NUM_OF_PLMN_PER_MME     32  /* maxnoofPLMNs(MME): 32 */
#define OGS_MAX_NUM_OF_PLMN             12  /* maxnoofPLMNs(AMF): 12 */
#define OGS_MAX_NUM_OF_BPLMN            OGS_MAX_NUM_OF_PLMN
#define OGS_MAX_NUM_OF_TAI …
```

Reset the number of TA, SLICE, and PLMN supported by AMF/MME(#2761)

---

src/amf/gmm-build.c

[ETSI TS 124 501 V16.5.1](https://www.etsi.org/deliver/etsi_ts/124500_124599/124501/16.05.01_60/ts_124501v160501p.pdf), 9.11.3.20 De-registration type
Switch off (octet 1, bit 4)
In the network to UE direction bit 4 is spare. The network shall set this bit to zero.

[AMF] Fix deregistration request De-registration type

---

src/mme/mme-context.h
src/mme/mme-s11-handler.c

This information will be required by the Gn interface in MME when answering an SGSN with an "SGSN Context Response" message during MS cell reselection EUTRAN->GERAN.

[MME] Store received PGW S5C IP address in mme_sess_t

---

src/mme/mme-s11-handler.c

This will be used by the Gn interface to obtain the UE IP and provide it to new SGSN when transmitting SGSN Context Response.

[MME] Store decoded PAA into session->ue_ip and session_type

---

lib/gtp/xact.c

As per TS 29.060:
The Initial/request message is "SGSN Context Request", sent by peer A. Peer B sends a response message "SGSN Context Response" with same SeqNr. Peer A sends a response message "SGSN Context Acknowledge" with same SeqNr.
If Peer B doesn't see a "SGSN Context Acknowlegde", it should keep retransmitting "SGSN Context Response" as usual.

lib/gtp: Fix xact logic for gtp1 messages with intermediate stage

---

src/nrf/nnrf-handler.c

NRF crash after receiving
curl --http2-prior-knowledge http://127.0.0.10:7777/nnrf-disc/v1/nf-instances?target-nf-type=AUSF&requester-plmn-list=[{"mcc":"999","mnc":"70"}]&requester-nf-type=AMF&service-names=nausf-auth&target-plmn-list=[{"mcc":"999","mnc":"70"}] curl --http2-prior-knowledge http://127.0.0.10:7777/nnrf-disc/v1/nf-instances\?target-nf-type=AUSF\&requester-plmn-list=%5B%7B%22mcc%22%3A%22999%22%2C%22mnc%22%3A%2270%22%7D%5D\&requester-nf-type\=AMF\&service-names=nausf-auth\&target-plmn-list=%5B%7B%22mcc%22%3A%22999%22%2C%22mnc%22%3A%2210%22%7D%5D

[NRF] crash after sending invalid message (#2808)

---

src/udm/nudm-handler.c

All the other error messages in this function use supi, except for one.  Just making things consistent.

[UDM] Use of SUPI not SUCI in error message

---

src/hss/hss-init.c

When `use_mongodb_change_stream` is enabled, the HSS is unable to start due to the following error:
```
[app] FATAL: hss_event_new: Assertion `e' failed. (../src/hss/hss-event.c:46)
```
In #2739, the event functions were moved into the hss app, however, `hss_event_init` is never called.  This adds the call to the function to allow the hss to start with change streams enabled.

[HSS] Add hss_event_init after change to event system

---

src/amf/amf-sm.c
src/amf/nsmf-handler.c
src/smf/gsm-sm.c
tests/common/nas-path.c
tests/registration/crash-test.c

I've resolved an issue where sending continuous 'PDU Session Release Request' message to the same session, when more than two sessions were created, was causing an SMF crash.
For your reference, this problem did not occur when only one session was created.

[SMF] Fixes crash when PDU session release

---

lib/core/ogs-sockaddr.c
lib/core/ogs-sockaddr.h
lib/nas/eps/conv.c
lib/nas/eps/conv.h
src/mme/mme-context.c
src/mme/mme-context.h

The assert is checking for sess->session->name, but afterwards there's a check to skip ses->session not being null, which means the assert can crash while dereferencing sess->session.

[MME] Fix potential null ptr dereference

---

lib/sbi/conv.c

When the input string contains a number and a unit too large to be represented by a 64-bit variable, AMF/SMF would crash due to conversion resulting in a negative value and unable to be used in compiling NAS-PDU container.
Now the value gets clipped at int64_t maximum value.
Failed to encode ASN-PDU [-1] (../lib/asn1c/util/message.c:42)

[SBI] Fix conversion of AMBR bitrates from string to integer

---

src/amf/amf-sm.c
src/amf/context.h
src/amf/gmm-handler.c
src/amf/gmm-handler.h
src/amf/gmm-sm.c
src/amf/namf-handler.c
src/amf/nas-path.c
src/amf/nas-path.h
src/amf/ngap-build.c
src/amf/ngap-build.h
src/amf/ngap-handler.c
src/amf/ngap-path.c
src/amf/ngap-path.h
src/amf/nnrf-handler.c
src/amf/nnssf-handler.c
src/amf/nsmf-handler.c
src/amf/nudm-handler.c
src/amf/sbi-path.c
tests/registration/guti-test.c

While they were continuing their fuzzy testing and developing PacketRusher, an unusual issue with the AMF was observed. The problem arises when a single Ethernet frame containing three bundled SCTP chunks is sent. This behavior is reproduced with PacketRusher when attempting to concurrently register two UEs with the same MSIN.
The expected behavior is that the PDU Session Establishment Accept is sent inside a DownlinkNASTransport to RAN UE NGAP ID 1. However, it is actually sent inside an InitialContextSetupRequest to RAN UE NGAP ID 2. The MAC of this NAS message is invalid for the Security Context of RAN UE NGAP ID 2 (probably valid for RAN UE NGAP ID 1)

[AMF] Issue during Concurrent UE Registration (#2839)

---

lib/crypt/ogs-kdf.c
lib/crypt/ogs-kdf.h

This function is needed by a follow-up patch implementing initial support for GERAN->EUTRAN idle mobility.

[CRYPT] Add ogs_kdf_kasme_idle_mobility()

---

src/mme/mme-context.c

This will be useful for other procedures where only the RAI is known, but not the specific CI. This is the case of idle mobility from Gb or Iu to EUTRAN, where MME needs to request contexts based on the RAI mapped in the GUTI obtained from the UE during TAU.
This also makes the config more resilient in RIM scenario, where an SGSN can be picked now even if CI doesn't match, instead of failing or faling back to the default route SGSN.

[MME] Match any SGSN in same RAI if none with specific RAI+CI found

---

src/smf/n4-build.c

Bug:
PFCP Session Modification Request is sent with URR associated in PDRs, but no Create URR IE.
Example:
[testVoNR_NoURR.zip](https://github.com/open5gs/open5gs/files/13974584/testVoNR_NoURR.zip)
Packet No. 10: both PDRs associate URR which is not present.
Fix:
URR building is added for Bearer Modification Request.

[SMF] Build URR at bearer modification

---

src/udm/context.c
src/udm/context.h
src/udm/nudm-handler.c

Hi @acetcom, 
I am currently working on a SMSF which I would like to propose to add to open5gs at a later date.  During the registration process for SMS over NAS (TS 23.502 4.13.3.1), the SMSF subscribes to the UDM in the case of a change to SMS Management Subscription data.  Currently, If the SMSF registers, it will remove the subscription that was added by the AMF.
This change will allow multiple NFs to subscribe to the UDM, and receive their own unique subscription identifier.

[UDM] Introduce ability to handle multiple sdmSubscriptions per UE

---

lib/core/ogs-timer.c
src/mme/mme-sm.c
src/mme/s1ap-build.c

A race condition can occur in the following situations. In conclusion, we can use this situation to determine whether or not the UE Context has been removed and avoiding a crash.
For example, suppose a UE Context is removed in the followings.
1. Attach Request
2. Authentication-Information-Request
3. Authentication-Information-Answer
4. Authentication Request
5. Authentication Response(MAC Failed)
6. Authentication Reject
7. UEContextReleaseCommand
8. UEContextReleaseComplete
The MME then sends a Purge-UE-request to the HSS and deletes the UE context as soon as it receives a Purge-UE-Answer.
Suppose an Attach Request is received from the same UE between Purge-UE-Request/Answer, then the MME and HSS start the Authentication-Information-Request/Answer process.
This can lead to the following …

[MME] Crash due to a race condition

---

lib/gtp/v1/types.h
src/mme/mme-gn-build.c
src/smf/gn-build.c

Before this patch, it was set as 0, which is Reserved in Network to MS direction.

[SMF,MME] Gn: Set Delivery order QoS field to No

---

lib/pfcp/context.c
src/sgwc/context.c
src/smf/binding.c
src/smf/context.c
src/smf/gx-handler.c
src/smf/npcf-handler.c

As mentioned in the sgwu.yaml configuration file, it is possible to configure multiple addresses with different source_interface values for the gtpu interface.
Following the this section, I defined two addresses, one with source_interface set to 0 and another with source_interface set to 1. My expectation was to see different addresses for the two PDRs in the Session Establishment Response message during session establishment. However, both addresses were the same, and it was the address I had set for source_interface = 0.
When I looked into the code, I found the reason for the issue. In the lib/pfcp/context.c file, on line 1185, the function that determines the address is called as follows:
...
} else {
ogs_gtpu_resource_t *resource = NULL;
resource = ogs_pfcp_find_gtpu_resource( …

[GTP-U] Fixed ogs_pfcp_find_gtpu_resource()(#2923)

---

lib/core/ogs-epoll.c
src/mme/mme-context.c
src/mme/mme-context.h
src/mme/mme-path.c
src/mme/mme-s11-handler.c
src/mme/mme-s6a-handler.c
src/mme/mme-sm.c
src/mme/s1ap-build.c
src/mme/s1ap-handler.c

Because a race condition can occur between S6A Diameter and S1AP message, the following error handling code has been added.
1. InitialUEMessage + Attach Request + PDN Connectivity request
2. Authentication-Information-Request/Authentication-Information-Answer
3. Authentication Request/Response
4. Security-mode command/complete
5. Update-Location-Request/Update-Location-Answer
6. Detach request/accept
In the ULR/ULA process in step 6, the PDN Connectivity request is pushed to the queue as an ESM_MESSAGE because the NAS-Type is still an Attach Request.
See the code below in 'mme-s6a-handler.c' for where the queue is pushed.
if (mme_ue->nas_eps.type == MME_EPS_TYPE_ATTACH_REQUEST) {
rv = nas_eps_send_emm_to_esm(mme_ue,
&mme_ue->pdn_connectivity_request);
if (rv != OGS_OK) { …

[MME] Fixes crash in building s1ap message

---

src/amf/amf-sm.c
src/amf/context.h
src/amf/gmm-handler.c
src/amf/ngap-handler.c
src/amf/nsmf-handler.c
src/smf/gsm-sm.c
tests/registration/dereg-test.c

There is an issue with SESSION RELEASE not working properly depending on the PDU session release complete order in the PDUSessionResourceReleaseResponse.
If the AMF receives PDUSessionResourceReleaseResponse followed by PDU session release complete, it works correctly.
However, if it receives PDU session release complete followed by PDUSessionResourceReleaseResponse, it does not work correctly and sends an Error Indication to the UE/gNB.
To fix this issue, we added pdu_session_release_complete_received and pdu_session_resource_release_response_received to the content so that CLEAR_SM_CONTEXT_REF() is executed when both are received.

[AMF/SMF] Resolved the Issue of Session Release Based on the Order of N1/N2 Messages (#2917)

---

lib/crypt/ogs-kdf.c
lib/crypt/ogs-kdf.h
lib/nas/5gs/decoder.c
lib/nas/5gs/encoder.c
lib/nas/5gs/ies.c
lib/nas/5gs/ies.h
lib/nas/5gs/message.h
lib/nas/5gs/support/nas-message.py
lib/nas/eps/decoder.c
lib/nas/eps/encoder.c
lib/nas/eps/ies.c
lib/nas/eps/ies.h
lib/nas/eps/message.h
lib/nas/eps/support/nas-message.py
src/mme/nas-path.c

1. Reachable assertion in ogs_nas_5gmm_decode
Location: lib/nas/5gs/decoder.c:4445
```c
int ogs_nas_5gmm_decode(ogs_nas_5gs_message_t *message, ogs_pkbuf_t *pkbuf)
{
int size = 0;
int decoded = 0;
ogs_assert(pkbuf);
ogs_assert(pkbuf->data);
ogs_assert(pkbuf->len);
```
When a NAS payload is received over `src/amf/context.c:1675`NGAP that has no data, the ogs_assert(pkbuf->len) assertion will be triggered.
2.Reachable assertion in ogs_nas_emm_decode
```
int ogs_nas_emm_decode(ogs_nas_eps_message_t *message, ogs_pkbuf_t *pkbuf)
{
int size = 0;
int decoded = 0;
ogs_assert(pkbuf);
ogs_assert(pkbuf->data);
ogs_assert(pkbuf->len);
```
Nearly identical to (1), but for LTE.
3. Reachable assertion in nas_eps_send_emm_to_esm
```
int nas_eps_send_emm_to_esm(mme_ue_t *mme_ue, …
```

[SEC] Several vulnerabilities have been resolved.

---

lib/sbi/nnrf-build.c
src/upf/context.c

The UPF is sending Session Report Request after the Session was Deleted, when the Gy interface is active.
UPF is sending PFCP session report request after the session has been deleted when the Gy interface is active. This is because some of the timers related to the report are not deleted when the session is deleted.
We have fixed it to delete all the timers in the session when the SESSION is deleted.

[UPF] Report after Session was Deleted (#2936)

---

lib/diameter/gx/message.h
lib/ipfw/ogs-ipfw.c
lib/ipfw/ogs-ipfw.h
lib/pfcp/build.c
lib/pfcp/context.h
lib/proto/types.h
lib/sbi/conv.c
src/smf/binding.c
src/smf/context.c
src/smf/context.h
src/smf/gsm-handler.c
src/smf/gx-handler.c
src/smf/gx-path.c
src/smf/npcf-handler.c
src/smf/s5c-handler.c
tests/common/context.c
tests/common/context.h
tests/volte/bearer-test.c
tests/vonr/qos-flow-test.c

For bi-directions, the rules are created in the same form as for downlink as shown below, so to apply them for uplink, we need to swap the rules according to the interface.
RX : permit out from <P-CSCF_RTP_IP> <P-CSCF_RTP_PORT> to <UE_IP> <UE_PORT>
GX : permit out from <P-CSCF_RTP_IP> <P-CSCF_RTP_PORT> to <UE_IP> <UE_PORT>
PFCP : permit out from <P-CSCF_RTP_IP> <P-CSCF_RTP_PORT> to <UE_IP> <UE_PORT>
RULE : Source <P-CSCF_RTP_IP> <P-CSCF_RTP_PORT> Destination <UE_IP> <UE_PORT>
TFT : Local <UE_IP> <UE_PORT> REMOTE <P-CSCF_RTP_IP> <P-CSCF_RTP_PORT>
RX : permit in from <UE_IP> <UE_PORT> to <P-CSCF_RTP_IP> <P-CSCF_RTP_PORT>
GX : permit out from <P-CSCF_RTP_IP> <P-CSCF_RTP_PORT> to <UE_IP> <UE_PORT>
PFCP : permit out from <P-CSCF_RTP_IP> <P-CSCF_RTP_PORT> to <UE_IP> <UE_PORT>
RULE : Source …

[SMF] Added Bi-Directional Flow (#2909)

---

lib/gtp/util.c

Running the code below caused a stack overflow, so I fixed that issue.
1. Start open5gs-sgwud so the gtp server listens to 127.0.0.6:2152.
2. Compile the attached poc and execute it. It sends a crafted message to gtp server and causes abort.
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <stdint.h>
uint8_t bytes[] = {0b00100100, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01,
0x01,       0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01,
0x01,       0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01,
0x01,       0x00, 0x00, 0x01, 0x01, …
```

[GTP-U] Fixed a stack overflow bug (#3003)

---

src/smf/context.h
src/smf/s5c-build.c
src/smf/s5c-handler.c

This IE is used by UEs registering through S2b interface (ePDG) to obtain DNS and P-CSCF server address information.

[SMF] Handle APCO IE in S2b GTPv2C CreateSessionRequest/Response

---

lib/pfcp/context.c

Checking the overlapping subnets is now enabled for the subnets with no DNN too.

[SMF] Check config file for overlapping UE subnets with no DNN

---

lib/ngap/build.c
lib/ngap/build.h
src/amf/amf-sm.c
src/amf/context.c
src/amf/context.h
src/amf/ngap-build.c
src/amf/ngap-handler.c
src/amf/ngap-path.c
src/amf/ngap-path.h
src/amf/sbi-path.c
src/mme/s1ap-path.c
src/smf/context.c
tests/common/context.h
tests/common/s1ap-path.c
tests/handover/5gc-n2-test.c
tests/handover/epc-s1-test.c
tests/registration/guti-test.c
tests/registration/idle-test.c
tests/unit/ngap-message-test.c

1. HandoverRequired
2. HandoverRequest
3. HandoverFailure
4. UEContextReleaseCommand
5. HandoverPreparationFailure
If UEContextReleaseComplete is not received,
the Source-UE will have the Target-UE.
6. HandoverRequired
There may be cases where the Source UE has a Target UE from a previous HandoverRequired process. In this case, it is recommended to force the deletion of the Target UE information when receiving a new HandoverRequired.
7. HandoverRequest
8. HandoverFailure
9. UEContextReleaseCommand
10. UEContextReleaseComplete
11. HandoverPreparationFailure
... Crashed ...

[MME/AMF] Fixed crash following Handover Request (#3014)

---

lib/nas/5gs/conv.c
src/amf/gmm-handler.c
src/amf/gmm-sm.c
tests/common/ngap-build.c
tests/common/ngap-build.h
tests/registration/crash-test.c

Reachable assertion in amf_ue_set_suci
Location: src/amf/context.c:1968
```
void amf_ue_set_suci(amf_ue_t *amf_ue,
ogs_nas_5gs_mobile_identity_t *mobile_identity)
{
amf_ue_t *old_amf_ue = NULL;
amf_sess_t *old_sess = NULL;
char *suci = NULL;
ogs_assert(amf_ue);
ogs_assert(mobile_identity);
suci = ogs_nas_5gs_suci_from_mobile_identity(mobile_identity);
ogs_assert(suci);
```
Exploitable by: Base Station
Severity: denial of service

[SEC] Vulnerabilities have been resolved (#2945)

---

src/mme/mme-gn-handler.c

Transaction Identity doesn't map 1-to-1 with Procedure Transaction Identity: The value ranges change, and PTI cannot use value 0 8which means unused).
Hence, for now let's simply set the PTI to a valid default value instead of asserting during mme_sess_add:
Assertion `pti != OGS_NAS_PROCEDURE_TRANSACTION_IDENTITY_UNASSIGNED'
Related: https://github.com/open5gs/open5gs/issues/3020

[MME] Assign valid PTI to sess created by mobility from 2G

---

src/amf/gmm-sm.c
src/amf/nas-path.c
src/amf/nas-path.h
src/mme/emm-handler.c
src/mme/emm-sm.c
src/mme/esm-sm.c
src/mme/mme-context.c
src/mme/mme-fd-path.c
src/mme/mme-fd-path.h
src/mme/mme-gn-handler.c
src/mme/mme-s11-handler.c
src/mme/mme-s6a-handler.c
src/mme/mme-sm.c
src/mme/nas-path.c
src/mme/nas-path.h
src/mme/sgsap-handler.c
tests/attach/crash-test.c
tests/common/nas-path.c
tests/common/s1ap-handler.c

Assume the UE has Attached, the session has been created, and is in the IDLE state with the UEContextRelease process.
This could result in the following call flow.
1. TAU request without Integrity Protected
2. Authentication request/response
3. Security-mode command/complete
MME can be performed simultaneously by the HSS(S6A) and UE(S1AP).
```
Update-Location-Request
Service request
Service reject
Delete Session Request
Delete Session Respnse
Update-Location-Answer
UEContextReleaseCommand for Service reject
TAU reject
UEContextReleaseCommand for TAU reject
UEContextReleaseComplete
UEContextReleaseComplete
```
MME crashes when UE sends a service request(S1AP) during ULR/ULA(S6A) with HSS, which has been fixed.

[MME] Race condition between S1AP and S6A

---

lib/sbi/message.c

"dnn" URL parameter was handled twice. Once as a NF discovery parameter, and once as normal URL parameter.
This fixes https://github.com/open5gs/open5gs/issues/3054 : DNN parameter was not propagated at UDM to UDR when SMF requested "sm-data".
If you have any other idea how to fix it, please tell.

[SBI] Fix handling "dnn" URL parameter

---

lib/nas/5gs/types.c
lib/nas/5gs/types.h
lib/proto/types.h
lib/sbi/context.c
lib/sbi/context.h
lib/sbi/message.c
lib/sbi/message.h
lib/sbi/nnrf-handler.c
lib/sbi/ogs-sbi.h
lib/sbi/path.c
src/amf/amf-sm.c
src/amf/context.c
src/amf/context.h
src/amf/gmm-handler.c
src/amf/gmm-handler.h
src/amf/gmm-sm.c
src/amf/meson.build
src/amf/namf-build.c
src/amf/namf-build.h
src/amf/namf-handler.c
src/amf/namf-handler.h
src/amf/sbi-path.c
src/nrf/nnrf-handler.c
src/scp/sbi-path.c

Added support for:
- `UEContextTransfer` request from new AMF to old AMF and
- `UEContextTransfer` response from old AMF to new AMF.
AMF info had to be stored in (new) AMF to be able to find the suitable (old) AMF and the `target_guami` is added in `discovery_option` as a parameter to search the AMF.
[ReportAndTrace.zip](https://github.com/open5gs/open5gs/files/14571502/ReportAndTrace.zip)

UE context transfer

---

src/amf/gmm-handler.c
src/amf/gmm-handler.h
src/amf/gmm-sm.c
src/amf/ngap-handler.c
src/amf/nnssf-handler.c
src/amf/nsmf-handler.c
src/amf/sbi-path.c
src/amf/sbi-path.h

When we try to send an SBI message to SMF to release a session, sometimes ran_ue is NULL. This happens when the Mobile Reachable Timer expires and Implicit Deregistration is triggered.
To account for this case, we added the `ran_ue` parameter to the SBI interface and made it work even if it is NULL.

[AMF] ran_ue can be NULL in IMPLICIT Dereg (#2999)

---

docs/_docs/tutorial/01-your-first-lte.md
src/mme/esm-handler.c
src/mme/mme-s11-handler.c
src/mme/sgsap-handler.c
tests/csfb/mo-idle-test.c

1. According to ETSI TS 129 118 4.1, if the Network Access Mode (NAM) is set to "Packet only," no SGs association should be established.
2. If the NAM is set to "Packet and Circuit," and the SGs association is rejected by the CS core, this rejection should only impact the SGs association itself and not result in a UE attach rejection for a UE with a valid HSS account.

[MME] incorrect behavior of the SGsAP

---

configs/logrotate/open5gs.in

Do not attempt to run "systemctl reload" on the open5gs services, unless they are running. This fixes the logrotate service failing on this postrotate script, if units are not running or not installed.

logrotate: fix reload failures

---

lib/gtp/path.h
src/mme/mme-gtp-path.c
src/sgwc/gtp-path.c
src/smf/gtp-path.c

When GTP-C secition of smf.yaml is deleted as follows to run smf as 5G, it crashed.
```diff
--- smf.yaml.orig       2024-03-26 14:13:12.000000000 +0900
+++ smf.yaml    2024-03-26 14:29:40.701508424 +0900
@@ -23,9 +23,6 @@
client:
upf:
- address: 127.0.0.7
-  gtpc:
-    server:
-      - address: 127.0.0.4
gtpu:
server:
- address: 127.0.0.4
@@ -47,7 +44,7 @@
-  freeDiameter: /root/open5gs/install/etc/freeDiameter/smf.conf
+#  freeDiameter: /root/open5gs/install/etc/freeDiameter/smf.conf
################################################################################
Open5GS daemon v2.7.0-119-g581d255
03/26 14:39:42.844: [app] INFO: Configuration: 'install/etc/open5gs/smf.yaml' (../lib/app/ogs-init.c:130)
03/26 14:39:42.845: [app] INFO: File Logging: …
```

[SMF] Crash SMF when no GTP-C config (#3094)

---

lib/dbi/ims.c
lib/dbi/ogs-mongoc.c
lib/dbi/ogs-mongoc.h
lib/dbi/session.c
lib/dbi/subscription.c
src/hss/hss-context.c
src/hss/hss-sm.c

checks mongoc version with
which can unexpectedly return false in case of mongoc versions such as 2.3.4.
So, I've fixed it as below.

[DBI] mongoc version not checked correctly (#3086)

---

src/mme/esm-build.c
src/mme/mme-context.c
src/mme/mme-s11-handler.c
src/mme/nas-path.c
src/mme/s1ap-build.c
tests/attach/auth-test.c
tests/attach/guti-test.c
tests/common/context.c
tests/common/context.h
tests/common/esm-build.c
tests/common/esm-handler.c
tests/common/esm-handler.h
tests/common/nas-path.c
tests/csfb/mo-idle-test.c

First of all, it crashes when creating a Dedicated Bearer on the default Session that is created for the first time. This behavior should be possible, so the related ASSERT is removed.
Next, the InitialContextRequest is modified
during the Attach Request to include the first Bearer.
Finally, there was an issue where trying to create a Dedicated Bearer with SGsAP enabled resulted in an InitialContextSetupRequest message with a PTI of zero. This is because MME initializes the PTI to 0 upon receiving the Create Bearer Request while processing SGsAP.
All of these issues has been fixed.

[MME] Incorrect behavior of SGsAP+Dedicated-Bearer (#3072)

---

src/smf/gsm-sm.c
src/smf/gy-handler.c
src/smf/gy-handler.h

This is the continuation of commit
12158eebb8ab0c6ea7b52291bce6cc4d3d38186c, which only checked the code in CCA[Update], but not in CCA[Initial].
The handling in CCA[Initial] is a bit more complex since depending on the outcome, we may end up with a Result-Code != SUCCESS in MSCC but the session may still be created at the OCS because the message Result-Code = SUCCESS. In that scenario, we want to abort setting up the PDN session but we still need to make sure we terminate the Gy session that was just created.

[SMF] Gy: Check Multiple-Services-Credit-Control Result-Code in CCA-I

---

docs/_docs/guide/01-quickstart.md
src/mme/mme-s11-handler.c
src/mme/mme-s11-handler.h
src/mme/mme-sm.c
src/sgwc/pfcp-sm.c
src/sgwc/s11-handler.c
src/sgwc/s5c-handler.c
src/sgwc/sxa-handler.c
src/sgwc/sxa-handler.h
src/sgwu/pfcp-sm.c
src/sgwu/sxa-handler.c
src/sgwu/sxa-handler.h
src/smf/gsm-sm.c
src/smf/n4-handler.c
src/smf/n4-handler.h
src/smf/pfcp-sm.c
src/smf/s5c-handler.c
src/smf/s5c-handler.h
src/smf/smf-sm.c
src/upf/n4-handler.c
src/upf/n4-handler.h
src/upf/pfcp-sm.c

If eg. PCRF or AAA diameter link is not yet ready (eg. PCRF crashed), and a client sends a CreateSessionRequest announcing its ow F-TEID, then open5gs-smfd answers with Create Session Response Cause="Remote peer not responding", but it is not setting the received F-TEID in the header of the response, instead it sends with TEID=0.
As a result, the peer cannot match the CreateSessionResponse, and needs to rely on its own timeout timer to figure out that specific request failed.
See 3GPP TS 29.274 5.5 Usage of the GTPv2-C Header:
```
Bit 4 represents a "T" flag, which indicates if TEID field is present in the GTP-C header or not. If the "T" flag is
set to 0, then the TEID field shall not be present in the GTP-C header. If the "T" flag is set to 1, then the TEID
field shall immediately follow …
```

[PFCP/GTP] Incorrect TEI/SEID=0 (#3043)

---

docs/_docs/guide/01-quickstart.md
lib/gtp/util.c
lib/gtp/util.h
src/smf/s5c-handler.c
src/smf/s5c-handler.h
src/smf/smf-sm.c

If eg. PCRF or AAA diameter link is not yet ready (eg. PCRF crashed), and a client sends a CreateSessionRequest announcing its ow F-TEID, then open5gs-smfd answers with Create Session Response Cause= "Remote peer not responding", but it is not setting the received F-TEID in the header of the response, instead it sends with TEI=0.
As a result, the peer cannot match the CreateSessionResponse, and needs to rely on its own timeout timer to figure out that specific request failed.
To address this issue, I modified the GTP Response message to check the Sender F-TEID and send it accordingly, setting the destination TEID to the value of the Sender F-TEID.
I've made this modification only for SMF, but MME and SGW-C have not done so; if you need to, you can work from the examples in SMF.
Similarly, …

[GTP] Incorrect destination TEID=0 (#3043)

---

src/smf/gy-handler.c

AS shown in 3GPP TS 29.244 C.2.1.1 diagram, the meaning of Threshold value is different in Diameter Gy and in PFCP interfaces. In Diameter Gy the value sets the trigger for the "remaining credit", while in PFCP the value sets the trigger for the "used credit".
ThresholdPFCP = Quota - ThresholdGy

[SMF] Fix Volume/Time Threshold conversion Gy->PFCP

---

src/amf/ngap-path.c
src/mme/s1ap-handler.c
src/mme/s1ap-path.c
tests/attach/issues-test.c
tests/registration/identity-test.c

In InitialUEMessage, send a NAS message with a message type other than Registration Request, Deregistration Request, or Service Request, the following messages from UE will not be accepted.
We found this issue in not only the initial state but multiple states. We believe if an attacker has the ability to inject a NAS message to the core, it can perform a DoS attack on the victim UE.
So, I've fixed that The MME/AMF deletes MME_UE_S1AP_ID/AMF_UE_NGAP_ID, and will not accept any following messages from the UE.

[AMF/MME] NAS message in an invaild state (#3131)

---

lib/nas/5gs/types.c
src/smf/gsm-handler.c

A malformed PDU Session Modification Request is sent from UE after Registration Complete.
```
Crash 1:
04/12 15:00:44.031: [amf] INFO: [imsi-999700000000001:1:11][0:0:NULL] /nsmf-pdusession/v1/sm-contexts/{smContextRef}/modify (../src/amf/nsmf-handler.c:837)
04/12 15:00:46.569: [nas] FATAL: ogs_nas_parse_qos_flow_descriptions: Assertion `descriptions->length' failed. (../lib/nas/5gs/types.c:486)
04/12 15:00:46.569: [core] FATAL: backtrace() returned 11 addresses (../lib/core/ogs-abort.c:37)
../src/smf/../../lib/nas/5gs/libogsnas-5gs.so.2(ogs_nas_parse_qos_flow_descriptions+0x162) [0x7e6e7a5a4e5d]
../src/smf/open5gs-smfd(+0x8c6ec) [0x5dd6c333d6ec]
../src/smf/open5gs-smfd(+0x2d69b) [0x5dd6c32de69b]
../src/smf/../../lib/core/libogscore.so.2(ogs_fsm_dispatch+0x119) [0x7e6e7b216c0c] …
```

[SMF] crash when malformed NAS message (#3132)

---

configs/310014.yaml.in
configs/csfb.yaml.in
configs/examples/5gc-sepp1-999-70.yaml.in
configs/examples/5gc-sepp2-001-01.yaml.in
configs/examples/5gc-sepp3-315-010.yaml.in
configs/examples/5gc-tls-sepp1-999-70.yaml.in
configs/examples/5gc-tls-sepp2-001-01.yaml.in
configs/examples/5gc-tls-sepp3-315-010.yaml.in
configs/examples/gnb-001-01-ue-001-01.yaml.in
configs/examples/gnb-001-01-ue-315-010.yaml.in
configs/examples/gnb-001-01-ue-999-70.yaml.in
configs/examples/gnb-315-010-ue-001-01.yaml.in
configs/examples/gnb-315-010-ue-315-010.yaml.in
configs/examples/gnb-315-010-ue-999-70.yaml.in
configs/examples/gnb-999-70-ue-001-01.yaml.in
configs/examples/gnb-999-70-ue-315-010.yaml.in
configs/examples/gnb-999-70-ue-999-70.yaml.in
configs/non3gpp.yaml.in
configs/open5gs/smf.yaml.in
configs/open5gs/upf.yaml.in
configs/sample.yaml.in
configs/slice.yaml.in
configs/srsenb.yaml.in
configs/volte.yaml.in
configs/vonr.yaml.in
lib/pfcp/context.c
lib/pfcp/context.h

The way subnet is set up has changed as shown below.
```
<OLD Format>
smf:
session:
- subnet: 10.45.0.1/16
<NEW Format>
smf:
session:
- subnet: 10.45.0.0/16
gateway: 10.45.0.1
```
For more information, please refer to Pull Request #2975.

[SMF/UPF] Changes subnet configuration (#2975)

---

configs/systemd/99-open5gs.network

When running the open5gs package with systemd network config, the 1st IP address of the UE pool configured in open5gs-upfd config file for ogstun was being assigned to the interface. This causes routing problems when traffic from the UE which was assigned that same IP address is routed to/from the ogstun interface.
As a result, every time that open5gs-upfd systemd service was restarted, the following changed had to be applied:
ip addr del 10.45.0.1/16 dev ogstun
ip route add 10.45.0.0/16 dev ogstun
The IP address was set in order to get the routing entry for free. Instead, it should only add the routing entry.
Related: https://osmocom.org/issues/6361

systemd: network: Avoid assigning IP addr from UE IP pool to ogstun interface

---

.github/workflows/meson-ci.yml
lib/sbi/nnrf-handler.c
src/sepp/n32c-handler.c

An assert shall be triggered if sepp_node is corrupted.
```
pwndbg> p *sepp_node
$5 = {
lnode = {
prev = 0x0,
next = 0xaaaac920c638
},
receiver = 0xaaaac9230990 "sepp2.localdomain",
negotiated_security_scheme = OpenAPI_security_capability_TLS,
target_apiroot_supported = true,
plmn_id = {{
mcc1 = 6 '\006',
mcc2 = 6 '\006',
mcc3 = 6 '\006',
mnc1 = 6 '\006',
mnc2 = 6 '\006',
mnc3 = 6 '\006'
} <repeats 12 times>},
num_of_plmn_id = 6710887,
target_plmn_id_presence = false,
target_plmn_id = {
mcc1 = 0 '\000',
mcc2 = 0 '\000',
mcc3 = 0 '\000',
mnc1 = 0 '\000',
mnc2 = 0 '\000',
mnc3 = 0 '\000'
},
supported_features = 1,
sm = {
init = 0xaaaaada181fc <sepp_handshake_state_initial>,
fini = 0xaaaaada18390 <sepp_handshake_state_final>,
state = 0xaaaaada194b4 <sepp_handshake_state_established>
}, …
```

[SEC] Heap overflow in parse PLMN-ID (#3154)

---

.github/workflows/meson-ci.yml
src/hss/hss-s6a-path.c

An assert shall be triggered if a stack corruption occurs.
The vulnerable code path is in src/hss/hss-s6a-path.c:
```
static int hss_ogs_diam_s6a_air_cb( struct msg **msg, struct avp *avp,
struct session *session, void *opaque, enum disp_action *act)
{
..
ogs_plmn_id_t visited_plmn_id;
..
ret = fd_msg_search_avp(qry, ogs_diam_visited_plmn_id, &avp);
ogs_assert(ret == 0);
ret = fd_msg_avp_hdr(avp, &hdr);
ogs_assert(ret == 0);
memcpy(&visited_plmn_id, hdr->avp_value->os.data, hdr->avp_value->os.len);
```

[SEC] Stack overflow in open5gs-hssd/s6a (#3155)

---

src/mme/mme-fd-path.c

An assert shall be triggered.
The vulnerable code path is in src/mme/mme-fd-path.c:
```
/* s6a process Subscription-Data from avp */
static int mme_s6a_subscription_data_from_avp(struct avp *avp,
ogs_subscription_data_t *subscription_data,
mme_ue_t *mme_ue, uint32_t *subdatamask)
{
...
/* AVP: 'MSISDN'( 701 )
* The MSISDN AVP is of type OctetString. This AVP contains an MSISDN,
* in international number format as described in ITU-T Rec E.164 [8],
* encoded as a TBCD-string, i.e. digits from 0 through 9 are encoded
* 0000 to 1001; 1111 is used as a filler when there is an odd number
* of digits; bits 8 to 5 of octet n encode digit 2n; bits 4 to 1 of
* octet n encode digit 2(n-1)+1.
* Reference: 3GPP TS 29.329
*/
ret = fd_avp_search_avp(avp, ogs_diam_s6a_msisdn, &avpch1);
ogs_assert(ret == …
```

[SEC] Heap overflow in open5gs-mmed/s6a (#3156)

---

.github/workflows/meson-ci.yml
src/amf/ngap-handler.c
src/mme/s1ap-handler.c

Assert shall be triggered if the mme_enb_t object is corrupted.
```
$ gdb -q -p `pidof open5gs-mmed`
..
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
0x0000ffff90deb46c in __GI___sigtimedwait (set=set@entry=0xfffffe63be68, info=info@entry=0xfffffe63bda8, timeout=timeout@entry=0x0) at ../sysdeps/unix/sysv/linux/sigtimedwait.c:61
61      ../sysdeps/unix/sysv/linux/sigtimedwait.c: No such file or directory.
Breakpoint 1 at 0xaaaabef69250: file ../src/mme/s1ap-handler.c, line 199.
[Switching to Thread 0xffff1efdef00 (LWP 20348)]
Thread 38 "open5gs-mmed" hit Breakpoint 1, s1ap_handle_s1_setup_request (enb=0xffff9029b5a0, message=0xffff1efdc498) at ../src/mme/s1ap-handler.c:199
warning: Source file is more recent than executable.
199         if …
```

[SEC] Heap overflow in open5gs-mmed/s1ap (#3153)

---

src/pcf/npcf-handler.c
src/pcrf/pcrf-rx-path.c

The indexes rx_message.ims_data.num_of_media_component and media_component->num_of_sub can overflow.
```
static int pcrf_rx_aar_cb( struct msg **msg, struct avp *avp,
struct session *sess, void *opaque, enum disp_action *act)
..
/* Gwt Specific-Action */
case OGS_DIAM_RX_AVP_CODE_SPECIFIC_ACTION:
break;
/* Gwt Media-Component-Description */
case OGS_DIAM_RX_AVP_CODE_MEDIA_COMPONENT_DESCRIPTION:
media_component = &rx_message.ims_data.
media_component[rx_message.ims_data.num_of_media_component];
ret = fd_msg_browse(avpch1, MSG_BRW_FIRST_CHILD, &avpch2, NULL);
ogs_assert(ret == 0);
while (avpch2) {
ret = fd_msg_avp_hdr(avpch2, &hdr);
..
}
fd_msg_browse(avpch2, MSG_BRW_NEXT, &avpch2, NULL);
}
rx_message.ims_data.num_of_media_component++;
break;
default:
ogs_warn("Not supported(%d)", …
```

[SEC] Stack overflow in PCRF/PCF (#3157)

---

.github/workflows/meson-ci.yml
lib/sbi/context.c
lib/sbi/context.h
lib/sbi/nnrf-handler.c
lib/sbi/path.c
src/amf/context.c
src/amf/gmm-handler.c
src/amf/namf-handler.c
src/amf/nnrf-handler.c
src/amf/nsmf-build.c
src/amf/sbi-path.c
src/ausf/nnrf-handler.c
src/bsf/nnrf-handler.c
src/nrf/nnrf-handler.c
src/nrf/nrf-sm.c
src/pcf/nnrf-handler.c
src/pcf/npcf-handler.c
src/pcf/nudr-handler.c
src/smf/nnrf-handler.c
src/udm/nnrf-handler.c
tests/af/nnrf-handler.c

Fixed not using Reference Count for adding/deleting NF Instances.
Up until now, NF Instances have been managed by referencing the Reference Count.
Initially, when an NF Instance is added, the Reference Count is incremented and when it is deleted, the Reference Count is decremented.
If a UE discovers another NF Instance through the NF Discovery function, the Reference Count is incremented. And if a UE de-registers, the Reference Count of the discovered NF is decremented.
However, there's a problem with this approach.
When other NF is de-registered,
there is no guarantee that it will be 100% notified.
For example, if a UDM is de-registered, but an SCP is de-registered before it, the AMF will not be notified that the UDM has been de-registered.
In situations where this is not clear, …

[SBI] Re-factor NF Instance Context (#3093)

---

lib/gtp/v2/types.c
lib/pfcp/handler.c
lib/pfcp/types.c
lib/proto/types.c
src/mme/sgsap-handler.c
src/sgwc/s11-handler.c
src/sgwu/context.c
src/smf/context.c
src/smf/fd-path.c
src/smf/s5c-handler.c
src/upf/context.c
src/upf/n4-handler.c

1. UPF
- upf_sess_find_by_smf_n4_f_seid: Assertion `OGS_OK == ogs_pfcp_f_seid_to_ip(f_seid, &key.ip)' failed. (../src/upf/context.c:280)
- ogs_pfcp_parse_sdf_filter in ../lib/pfcp/types.c
- ogs_pfcp_parse_volume in ../lib/pfcp/types.c:500
2. SGW-C
- sgwc_s11_handle_create_session_request: Assertion `0 < ogs_fqdn_parse(apn, req->access_point_name.data, ogs_min(req->access_point_name.len, OGS_MAX_APN_LEN))' failed. (../src/sgwc/s11-handler.c:224)
- ogs_gtp2_parse_uli in ../lib/gtp/v2/types.c
3. SMF
- ogs_pfcp_parse_user_plane_ip_resource_info in ../lib/pfcp/types.c

[SEC] Assertion to ERROR Handling (#3207)

---

src/amf/nausf-handler.c

HTTP Location header field does not contain the "5g-aka-confirmation" substring. Which means that when we try to delete the authentication from AUSF, it does not provide the correct URL according to the standard.
/nausf-auth/v1/ue-authentications/1
vs
/nausf-auth/v1/ue-authentications/1/5g-aka-confirmation
The current code/unit tests work without an issue due to laxed requirement in AUSF for deleting the authentication. AUSF checks for only the DELETE HTTP method and `ue-authentications` URL component, without checking for the `5g-aka-confirmation` URL component.

[AMF] Fix for storing 5G AKA Confirmation URL

---

lib/gtp/xact.c
lib/gtp/xact.h
src/mme/mme-context.c
src/mme/mme-context.h
src/mme/mme-gtp-path.c
src/mme/mme-path.c
src/mme/mme-s11-handler.c
tests/volte/rx-test.c

Consider the following situation.
```
1. SMF->SGW-C->MME: First Update Bearer Request
2. MME->UE:         First Modify EPS bearer context request
3. SMF->SGW-C->MME: Second Update Bearer Request
4. MME->UE:         Second Modify EPS bearer context request
5. UE->MME:         First Modify EPS bearer context accept
6. MME->SGW-C->SMF: First Update Bearer Response
7. UE->MME:         Second Modify EPS bearer context accept
8. MME->SGW-C->SMF: Second Update Bearer Response
```
Until now, only one GTP transaction was managed for one bearer.
Therefore, if the UE does not send an EPS Modify bearer accept to the MME, and the SMF/SGW-C sends an Update Bearer Request to the MME, The NEW update bearer request overwrites the OLD that was previously managed. So we modified it to manage them …

[MME/GTP] Managing multiple GTP xact (#3240)

---

src/mme/mme-s11-handler.c

We've encountered an issue where Downlink Data Notification Acks are not sent in the following situations.
1. SGW-U received Error Indication
2. SGW-U sends PFCP Report Request to SGW-C
3. SGW-C sends PFCP Report Response to SGW-U
4. SGW-C sends Downlink Data Notification to MME (MME Connected with eNB)
5. MME sends UEContextReleaseCommand to the eNB
6. eNB sends UEContextReleaseComplete to the MME
7. MME sends S1-Paging to the eNB
8. eNB sends Service-Request to the MME
9. MME sends InitialContextSetupRequest to the eNB
10. eNB sends InitialContextSetupResponse to the MME
Here, MME needs to send Downlink Data Notification Acknowledge.
So, we've fixed it

[MME] Fixed Error Indication (#3302)

---

src/mme/emm-sm.c
src/mme/mme-context.h
src/mme/mme-path.c
src/mme/mme-s11-handler.c
src/mme/s1ap-handler.c

On 4G only... when UE sent an inactivity UEContextReleaseRequest, Open5GS sent back UEContextReleaseCommand **with cause=normal-release. This, in turn, does not allow the Samsung UE to return to the low power state in our testing of the scenario.
Comparing the behavior of open5gs to other cores that we have tested the other cores are sending a ** cause=“Radio Network Layer Cause”: User inactivity ** when the UE sends inactivity. And this is what allows other cores to transition the UE to the low power state whereas with open5gs the UE is not entering the low power state.
We've fixed to allow open5gs to come to the same level of compliance in this area as to the other cores.

[MME] UEContextReleaseCommand cause (#3280)

---

lib/diameter/common/base.h
lib/diameter/common/config.c
src/mme/mme-context.c
src/smf/context.c

... via the YAML configuration
NOTE: when upgrading to 2.7.1 we noticed a change in behavior, where if the MME/SMF are started before their respective diameter peers, a connection will not be attempted again until the TcTimer expires, regardless of having new messages to deliver; and since the default value is 30 seconds, this becomes quite noticeable.
The timer can be set in the freediameter .conf file, but we prefer to use the yaml configuration, and this particular option was not exposed, so we added it. It would probably be a good idea to move the common freediameter parsing part to a separate library function rather than copy+pasting it in each daemon, but I did not want to make the pull request bigger than it strictly needed to be.

[MME,SMF]: allow setting of diameter TC_TIMER

---

lib/pfcp/handler.c
src/sgwu/gtp-path.c
src/upf/gtp-path.c

In ogs_pfcp_up_handle_pdr, there is a copy operation performed on recvbuf, which can reduce the sending performance in the data path. So, this copy operation can be eliminated. 
So I modified ogs_pfcp_up_handle_pdr() as shown below.
```
#if 0
sendbuf = ogs_pkbuf_copy(recvbuf);
if (!sendbuf) {
ogs_error("ogs_pkbuf_copy() failed");
return false;
}
#else
sendbuf = recvbuf;
#endif
```
If my modifications don't make UPF work properly, please let me know.

UPF Performance enhancement (#3306)

---

lib/proto/types.h
src/smf/s5c-handler.c
src/smf/smf-sm.c

TS24.008
10.5.6.12 Traffic Flow Template
Table 10.5.162: Traffic flow template information element
Number of packet filters (octet 3)
The number of packet filters contains the binary coding for the number of packet filters in the packet filter list. The number of packet filters field is encoded in bits 4 through 1 of octet 3 where bit 4 is the most significant and bit 1 is the least significant bit.
For the "delete existing TFT" operation and
for the "no TFT operation", the number of packet filters shall be coded as 0. For all other operations, the number of packet filters shall be greater than 0 and less than or equal to 15.
The array of TLV messages is limited to 16.
So, Flow(PDI.SDF_Filter) in PDR is limited to 16.
Therefore, we defined the maximum number of flows as 16.

[TFT] Incrase the number of flows 8->16 (#3339)

---

lib/proto/types.h
src/smf/s5c-handler.c
src/smf/smf-sm.c

TS24.008
10.5.6.12 Traffic Flow Template
Table 10.5.162: Traffic flow template information element
Number of packet filters (octet 3)
The number of packet filters contains the binary coding for the number of packet filters in the packet filter list. The number of packet filters field is encoded in bits 4 through 1 of octet 3 where bit 4 is the most significant and bit 1 is the least significant bit.
For the "delete existing TFT" operation and
for the "no TFT operation", the number of packet filters shall be coded as 0. For all other operations, the number of packet filters shall be greater than 0 and less than or equal to 15.
The array of TLV messages is limited to 16.
So, Flow(PDI.SDF_Filter) in PDR is limited to 16.
Therefore, we defined the maximum number of flows as 16.

[TFT] Incrase the number of flows 8->16 (#3343)

---

lib/crypt/zuc.c
tests/common/context.c
tests/volte/diameter-rx-path.c

The proposal out of the valgrind memcheck procedure are a couple of small patches to open5gs within the patches subdirectory.

[MEM] valgrind memcheck findings (#3349)

---

docs/_docs/platform/07-freebsd.md
subprojects/libtins.wrap
vagrant/freebsd/Vagrantfile

- Upgraded libraries to 4.5 to address compile error issues with CXX11 support
- Change the default version of FreeBSD Vagrant to 14.1-STABLE
- FreeBSD Platform documentation also changed to 14.x version

Tested on FreeBSD-14.1-STABLE (#3350)

---

lib/core/ogs-time.h
lib/sbi/context.h
lib/sbi/nnrf-build.c
lib/sbi/nnrf-handler.c
src/nrf/nnrf-handler.c
tests/app/5gc-init.c

NF should accept 204 No Content for Update Subscription requests. According to 3GPP 29.510 NRF specification document in figure 5.2.2.5.6.1 NRF may return 204 or 200 for success update operations.
2a. On success, if the NRF accepts the extension of the lifetime of the subscription, and it accepts the requested value for the "validityTime" attribute, a response with status code "204 No Content" shall be returned.
2b. On success, if the NRF accepts the extension of the lifetime of the subscription, but it assigns a validity time different than the value suggested by the NF Service Consumer, a "200 OK" response code shall be returned. The response shall contain the new resource representation of the "subscription" resource, which includes the new validity time, as determined by the NRF, …

[NRF] Fix the subscription valdityTime (#3360 #3361 #3363 #3364)

---

src/amf/nsmf-build.c

Previously, 5GMM cause was not being sent due to missing "is_x_value" not being set to true.

[AMF] Send 5GMM cause in request to SMF on AMF-initiated session release

---

lib/core/abts.c
lib/crypt/ecc.c
lib/crypt/kasumi.c
lib/crypt/ogs-aes.c
lib/gtp/v1/types.c
lib/ipfw/dummynet.c
lib/ipfw/ipfw2.c
lib/ipfw/tables.c
lib/sbi/conv.c
lib/sctp/ogs-lksctp.c
src/amf/nsmf-handler.c
src/mme/mme-fd-path.c
src/mme/mme-sm.c
src/mme/s1ap-handler.c
src/mme/sgsap-handler.c
src/nssf/context.c
src/pcf/pcf-sm.c
src/sgwc/context.c
src/sgwc/pfcp-sm.c
src/sgwc/sxa-handler.c
src/smf/gn-build.c
src/smf/gy-path.c
src/udm/nudm-handler.c

The clang scan-build procedure
```
Assume Ubuntu docker container with open5gs mounted to /src.
Assume these tools are installed to docker container:
sudo apt install -y clang-tools clang
For easy reference to clang scan-build tool:
Put normal open5gs build procedure into a file called /src/build
=======================
Inside docker container:
=======================
export CLANG_OUT_DIR=/src/scan_build_results
scan-build -disable-checker deadcode.DeadStores --override-compiler --keep-going
--exclude subprojects --exclude tests --exclude lib/asn1c -maxloop 200 -o $CLANG_OUT_DIR -plist-html /src/build 2>&1 | tee /src/logclang.txt
=======================
Results:
=======================
Results are in html format in $CLANG_OUT_DIR - top level index.html
```
Note that in this analysis the …

clang scan-build static analysis findings/resolutions (#3387)

---

src/mme/mme-context.h
src/mme/mme-gn-handler.c

Correct the Quality of Service values for a translated bearer when a UE comes from 2G to 4G.
Without the commits, the MME requests a bearer with QCI 0.
Certain eNodeBs will reject such bearer (Ericsson rbs6402).

[MME] Gn/2G to 4G mobility: Fix QoS values

---

src/amf/nudm-build.c

Set flag LimitedSubscriptions in the supportedFeatures field in SDMSubscription. This flag should be set in case that AMF supports unique SDM Subscription, notifying UDM in this case of the support.

[AMF] add supportedFeatures field in SDMSubscription request

---

src/smf/nudm-handler.c

The standard mandates that one SSC Mode is the default (if UE does not request one), with up to 2 additional SSC Modes can be selected. Always check also the default SSC Mode if it can be selected.
Same logic applies for Session Types.

[SMF] Fix handling allowed SSC Modes and Session Types

---

src/mme/emm-sm.c

This can happen if a UE never sends the UE Network Capabilities IE (eg Attach or TAU) when coming from 2G to 4G:
```
08/21 11:45:31.476: [emm] DEBUG: emm_state_security_mode(): ENTRY (/open5gs/src/mme/emm-sm.c:1162) 08/21 11:45:31.476: [mme] DEBUG: [262420000000007] Security mode command (/open5gs/src/mme/nas-path.c:336)
08/21 11:45:31.476: [emm] DEBUG:     Replayed UE SEC[LEN:2 EEA:0x0 EIA:0x0 UEA:0x0 UIA:0x0 GEA:0x0] (/open5gs/src/mme/emm-build.c:385)
08/21 11:45:31.476: [emm] DEBUG:     Selected[Integrity:0x0 Encrypt:0x0] (/open5gs/src/mme/emm-build.c:393)
08/21 11:45:31.476: [emm] ERROR: Encrypt[0x0] can be skipped with EEA0, but Integrity[0x0] cannot be bypassed with EIA0 (/open5gs/src/mme/emm-build.c:447)
08/21 11:45:31.476: [mme] ERROR: emm_build_security_mode_command() failed …
```

[MME] Avoid crash if tx Security Mode Command fails

---

src/mme/emm-sm.c
src/mme/mme-context.c
src/mme/mme-context.h
src/mme/mme-event.h
src/mme/mme-fd-path.c
src/mme/mme-fd-path.h
src/mme/mme-gn-handler.c
src/mme/mme-s6a-handler.c
src/mme/mme-sm.c

As per 3GPP TS 23.401 Annex D.3.6 step 6, "Security functions may be
executed" during TAU (UE cell reselection 2g->4g).
The idea is that the 4G network should check the integrity of the TAU,
and only if iexisting and valid then accept it right away. Otherwise,
an authorization procedure is started.
Until now, during 2g->4g TAU we were retrieving and acking the PDP Context
received from the SGSN and creating the session against the SGW right away.
Tests done so far with real phones ended up in unsuccesful results when
tring to reuse the 4g context derived from 2g, due to yet unknown
reasons.
Hence, with this patchset we simply force for now the re-auth and
recreation of security context before completing the TAU. This showed
good results during testing with real phones.
The security …

[MME] Force re-auth of UE during 2g->4g cell reselection

---

lib/diameter/common/config.c
lib/diameter/common/init.c
lib/diameter/common/logger.c
lib/diameter/common/logger.h
lib/diameter/common/meson.build
lib/diameter/common/ogs-diameter-common.h
lib/diameter/common/stats.c
lib/diameter/common/stats.h
src/hss/hss-cx-path.c
src/hss/hss-s6a-path.c
src/hss/hss-swx-path.c
src/mme/mme-fd-path.c
src/pcrf/pcrf-gx-path.c
src/pcrf/pcrf-rx-path.c
src/smf/gx-path.c
src/smf/gy-path.c
src/smf/s6b-path.c
tests/non3gpp/diameter-s6b-path.c
tests/non3gpp/diameter-swx-path.c
tests/volte/diameter-cx-path.c
tests/volte/diameter-rx-path.c

This is a preparation PR towards being able to provide diameter metrics updates through the mainloop, as discussed earlier here:
https://github.com/open5gs/open5gs/pull/3121#issuecomment-2044603693
Please merge without squashing, makes following the changes easier.

diameter: Integrate stats into mainloop

---

src/mme/s1ap-handler.c

The issue was that the PLMN-ID of the TAI was incorrectly being retrieved from the PLMN-ID of the EUTRAN_CGI.
As a result, when the PLMN-IDs of the TAI and EUTRAN_CGI were improperly set, the MME would crash.
All issues have now been resolved.

[MME] Incorrectly being retrieved from the PLMN-ID (#3480)

---

src/smf/s5c-build.c

I have modified the SMF configuration to send S2b PGW GTP-U instead of S5/S8 PGW GTP-U in WLAN.
This adjustment should ensure that the correct interface type is used, as per the specifications.

[SMF] Fixed interface-type in the Create Bearer Request (#3484)

---

src/smf/context.c

I have modified the PAA's IPv6 prefix length from 8 to 64. This adjustment ensures that the prefix length now correctly reflects the standard /64 notation, in accordance with the specifications.

[SMF] Fixed incorrect prefix length in GTPv2 PAA IE (#3495)

---

src/smf/gsm-build.c
src/smf/gsm-handler.c
tests/app/5gc-init.c

Decrement the Packet Filter Identifier by 1 before sending it to the UE during GSM message construction. This correction ensures proper synchronization between the UE and SMF, allowing `smf_pf_find_by_identifier()` to accurately locate the corresponding `pf` context without adjusting the identifier during the search.
This fix aligns the 5GC implementation with the EPC behavior, where the identifier was correctly decremented before transmission to the UE, preventing mismatches and synchronization issues.

[SMF] Fix Packet Filter Identifier handling in SMF (#3505)

---

lib/proto/types.h
src/smf/gsm-handler.c
tests/app/5gc-init.c
tests/common/gsm-build.c

- **Correct Packet Filter Identifier Handling:** Remove the addition of +1 when searching for the packet filter context using `smf_pf_find_by_identifier()` in the 5G Core SMF. According to 3GPP TS24.008 Section 10.5.6.12 and TS24.501 Section 9.11.4.13, the Packet Filter Identifier should range from 1 to 15 (or 0 to 15) depending on the operation and should be used directly as received from the UE.
- **Adjust Maximum Number of Packet Filter Identifiers:** Change the maximum number of Packet Filter Identifiers from **16** to **15** in the SMF to comply with the 3GPP specifications. The standards specify that the number of packet filters shall be greater than 0 and less than or equal to 15 for certain operations.
**Background:**
In the current 5GC implementation, the SMF incorrectly adds +1 …

[SMF] Fix Packet Filter Identifier handling and limit maximum number (#3505)

---

src/sgwc/pfcp-path.c
src/sgwu/pfcp-path.c
src/upf/pfcp-path.c

This commit fixes an issue where the system would crash due to improper memory release after receiving crafted PFCP packets from UEs.

[PFCP] Fix memory free issue causing crash (#3497)

---

lib/pfcp/build.c
lib/pfcp/context.h
lib/pfcp/handler.c
lib/pfcp/message.c
lib/pfcp/message.h
lib/pfcp/support/pfcp-tlv.py
lib/pfcp/types.h
src/sgwc/context.c
src/smf/context.c

This field was previously omitted, which could lead to improper handling of interface-specific logic in certain scenarios.
The addition of the 3GPP Interface Type ensures correct behavior in compliance with the 3GPP standards for PFCP message handling.

[PFCP] Add Missing 3GPP Interface Type in PFCP Messages

---

lib/asn1c/util/conv.c
src/mme/emm-build.c
src/mme/emm-sm.c
src/mme/mme-context.c
src/mme/mme-context.h
src/mme/mme-path.c
src/mme/mme-s6a-handler.c
src/mme/nas-path.c
src/mme/s1ap-build.c
src/mme/sgsap-handler.c
src/smf/ngap-build.c
tests/app/5gc-init.c
tests/common/sgsap-build.c
tests/csfb/abts-main.c
tests/csfb/meson.build
tests/csfb/tau-test.c

While experimenting with CSFB, it was observed that when the UE returns to E-UTRAN after a CS call, the UE performs a Tracking Area Update with a combined Tracking Area/Location Area update and IMSI attach. Currently, Open5GS's MME simply responds with a TAU Accept message but does not inform the MSC/VLR.
As a result, no further MT (Mobile Terminated) CS/SMS services are possible in cases where the MSC/VLR only attempts paging on GERAN. However, some MSC/VLR implementations with fast fallback may still attempt paging on E-UTRAN, allowing MT CS/SMS services to function intermittently.
According to 3GPP TS 29.118 Section 5.2.2 Procedures in the MME, specifically Section 5.2.2.2.1, if the timer Ts6-1 is not running, the MME shall start the location update for non-EPS services procedure upon …

[CSFB] Fix Location Update for non-EPS (#3381)

---

src/scp/sbi-path.c

In accordance with TS29.500 Section 5.2.2.2 on mandatory HTTP standard headers, the User-Agent header in HTTP/2 requests is required to include the NF type of the HTTP/2 client. Additionally, it is specified that the content of the User-Agent header may be followed by a hyphen and custom information when needed, providing greater flexibility for identifying the originating NF type or adding other specific details.
To accommodate this requirement, I modified the code to allow for additional information to be appended after the NF type in the User-Agent header, separated by a hyphen.
This change ensures that the User-Agent header format can be customized as needed for indirect communication scenarios and requests originating from the SCP, improving compliance with the specification and …

[SBI] Enable Custom Info in User-Agent Header for HTTP/2 Requests (#3555)

---

src/amf/ngap-handler.c

Current function only compares if the plmn contained in the gnb_id is present in the broadcasted plmns, which reject register. Avoiding a single cell to only broadcast different plmns from the main gnb plmn.
Now the function compares with supported AMF's plmn as specified in TS38.413, Section 8.7.1.4 Abnormal Conditions:
_If the AMF does not identify any of the PLMNs/SNPNs indicate in the NG SETUP REQUEST message, it shall reject the NG Setup procedure with an appropriate cause value._

fixed function to compare with amf supported plmns

---

src/amf/context.c
src/amf/context.h
src/mme/mme-context.c
src/mme/mme-context.h
tests/handover/5gc-n2-test.c

Resolved an issue where Handover was failing when attempting to handover from GNB-ID/eNB-ID 1 to GNB-ID/eNB-ID 0.
The problem occurred because the hash table managing GNB_ID values would remove any entry with the default GNB-ID/eNB-ID of 0 before re-adding entries.
Consequently, any GNB/eNB configured with a GNB-ID/eNB-ID of 0 would be inadvertently deleted whenever another GNB was added.
This fix modifies the handling of the hash table to prevent the default GNB-ID/eNB-ID (0) from being removed unintentionally, allowing handovers between GNB-ID/eNB-ID 0 and other GNBs/eNBs to proceed without error.

[AMF/MME] Fix handover failing due to GNB/eNBID hash table handling

---

lib/sbi/conv.c

TS 29.571 - 5.5.2 Simple Data Types defines BitRate type as
String representing a bit rate that shall be formatted as follows:
Pattern: '^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$'
Examples: "125 Mbps", "0.125 Gbps", "125000 Kbps"
Taking the "0.125 Gbps" example, rather than round 0.125 down to 0, parse it as a double-float first before multiplying by 10^9, resulting in 1.25e8 (bps).

Support non-integer bitrate strings more accurately

---

lib/app/ogs-config.c
lib/app/ogs-config.h
src/mme/emm-build.c

In case an external HSS is used, and the NAM field is set to 0 (PACKET_ONLY), Open5GS MME will only respond with an "EPS_ONLY" attach accept. This behavior causes a lot of UEs (mainly phones) to disconnect after 1-2 seconds without further signalling.
To resolve this, a new flag is introduced:
```
global:
parameter:
fake_csfb: true
```
If this flag is set to 'ture', the MME will respond with a combined EPS/IMSI attach accept even if the HSS NAM field is set to "PACKET_ONLY", or if the MME has no SGs connection towards a CS core.
By default this flag is false, thus not modifying the original behavior.
Note: some commercial core network vendors do include the LAI part in a "fake" combined EPS/IMSI attach accept message. As that field is optional, and testing also indicates that it is not …

[MME] Add fake combined attach

---

src/amf/ngap-path.c

This PR fixes a possible heap-buffer-overflow issue in ngap_send_to_nas function when handling empty NAS PDUs.

[AMF] Fix a possible heap-buffer-overflow in ngap_send_to_nas

---

src/amf/gmm-sm.c

This pull request addresses an issue in the AMF where it crashes upon receiving the Nausf_UEAuthentication_Authenticate response in the gmm_state_exception function.
The crash occurs when the same UE continuously sends registration requests while the previous UE context is released before the AUSF response is received, leading to incorrect states in the gmm state machine.
The root cause was a lack of proper handling in the gmm_state_exception function for the scenario where multiple registration requests from the same UE cause the AMF to process outdated authentication vectors.
This update introduces a fix to handle this edge case and prevent the AMF from crashing.

[AMF] Fix crash due to incorrect handling of UE registration requests(#3608)

---

src/amf/gmm-handler.c

In case that UE sends "mapped HPLMN" in the Session Establishment Request, AMF did not save it and forward it in the request to SMF.

[AMF] save mapped HPLMN from Session Est Req

---

src/smf/context.c

Newer phones reject the type of TFTs that SMF sends because they include the local address.
With this patch the SMF will reply with Network support of Local address in TFT indicator, which is the same 0011H value in the PCO; if the UE has advertised support for the local address in TFT (by including the corresponding 0011H PCO in the PDN Connectivity Request or in the corresponding ESM Information Response
For phones which do not indicate support for MS_SUPPORT_LOCAL_ADDR_TFT_INDICATOR there is no problem since they also don't complaint about the TFTs with local address and they seem to apply them (without the local address but they work).
This patch is necessary for VoLTE/VoNR with newer phones

Support for MS_SUPPORT_LOCAL_ADDR_TFT_INDICATOR

---

lib/sbi/nnrf-path.c
lib/sbi/path.c
lib/sbi/path.h
src/amf/context.c
src/pcf/nbsf-build.c
src/pcf/nbsf-handler.c
src/pcf/nnrf-handler.c
src/pcf/npcf-handler.c
src/pcf/nudr-handler.c
src/pcf/sbi-path.c
src/pcf/sbi-path.h
src/pcf/sm-sm.c
src/scp/sbi-path.c

Modified the PCF logic to bypass the BSF dependency when it is not available. This change ensures that the 5G Core can operate without requiring a BSF, allowing PDU sessions to be established successfully in setups where only a single PCF is used.

[BSF] Remove mandatory BSF dependency for PDU session establishment (#3626)

---

lib/diameter/common/base.h
lib/diameter/common/util.c
src/smf/context.c
src/smf/gn-handler.c
src/smf/s5c-handler.c

Modify the function to return true if the peer is a relay, otherwise check for advertised application.

[SMF] Add check for relay peer in ogs_diam_is_relay_or_app_advertised function (#3589)

---

configs/csfb.yaml.in
configs/open5gs/mme.yaml.in
lib/sctp/ogs-lksctp.c
lib/sctp/ogs-sctp.h
lib/sctp/ogs-usrsctp.c
src/mme/mme-context.c
src/mme/mme-context.h
src/mme/sgsap-sctp.c
tests/common/sctp.c
tests/sctp/sctp-test.c

Added support for binding to local IP addresses in ogs_sctp_client and ogs_sctp_server, and correct SGsAP configuration
Implemented the ability to bind to one or multiple local IP addresses using `sctp_bindx()` in both the `ogs_sctp_client()` and `ogs_sctp_server()` APIs.
Users can now specify local addresses in the configuration files under the new `local_addresses` field, reducing unnecessary complexity and signaling caused by binding to `ANY_ADDR`.
This update addresses issue https://osmocom.org/issues/6509 by ensuring correct operation in multi-interface and complex networking setups.
Additionally, corrected the `sgsap` configuration by changing it from `server` to `client`, and added support for specifying `local_addresses` for local binding as follows:
```
sgsap:
client:
- address: …
```

[SCTP] Support setting local address (#3344)

---

configs/open5gs/amf.yaml.in
configs/open5gs/ausf.yaml.in
configs/open5gs/bsf.yaml.in
configs/open5gs/nrf.yaml.in
configs/open5gs/nssf.yaml.in
configs/open5gs/pcf.yaml.in
configs/open5gs/scp.yaml.in
configs/open5gs/sepp1.yaml.in
configs/open5gs/sepp2.yaml.in
configs/open5gs/smf.yaml.in
configs/open5gs/udm.yaml.in
configs/open5gs/udr.yaml.in
debian/open5gs-common.dirs
lib/sbi/client.c
lib/sbi/client.h
lib/sbi/context.c
lib/sbi/context.h
lib/sbi/nghttp2-server.c
lib/sbi/server.c
lib/sbi/server.h
meson.build

- Add `sslkeylogfile` configuration options to `*.yaml.in` in NFs.
- Update `open5gs-common.dirs` to include `var/log/open5gs/tls` directory
- Extend `ogs_sbi_context_s` structure in `context.h` to include `sslkeylog`
- Modify `context.c` to parse and handle `sslkeylogfile` settings
- Update `server.c` and `server.h` to manage the `sslkeylog` field in server structures
- Update `ogs_sbi_client_add` and `ogs_sbi_client_remove` functions to handle `sslkeylog` field.
- Adjust `meson.build` to create the TLS log directory during installation
This commit introduces SSL key logging functionality to Open5GS, enabling the capture of SSL/TLS keys. This feature is essential for debugging encrypted traffic and allows integration with tools like Wireshark for decrypting TLS sessions.

[SBI] Enable SSL Key Logging for Enhanced Debugging and Analysis (#3647)

---

configs/open5gs/amf.yaml.in
configs/open5gs/ausf.yaml.in
configs/open5gs/bsf.yaml.in
configs/open5gs/nrf.yaml.in
configs/open5gs/nssf.yaml.in
configs/open5gs/pcf.yaml.in
configs/open5gs/scp.yaml.in
configs/open5gs/smf.yaml.in
configs/open5gs/udm.yaml.in
configs/open5gs/udr.yaml.in
lib/sbi/context.c

This update allows the parsing and handling of user-defined port numbers in the `advertise` field or explicitly in the `server` configuration for SBI. Users can now specify non-default ports for both binding and advertising while maintaining compatibility with existing configurations. The feature includes logic to handle FQDNs with embedded port numbers (e.g., `example.com:8080`) and ensures proper memory management during parsing. Updated the client association logic to utilize custom ports when specified.
Examples:
- Bind to the address on the eth0 and advertise as open5gs-amf.svc.local
```
sbi:
server:
- dev:eth0
advertise: open5gs-amf.svc.local
```
- Specify a custom port number 7777 while binding to the given address
```
sbi:
server:
- address: amf.localdomain
port: 7777
```
- Bind …

[SBI] Added support for custom port numbers in SBI configuration with FQDN(#3385)

---

configs/open5gs/amf.yaml.in
configs/open5gs/ausf.yaml.in
configs/open5gs/bsf.yaml.in
configs/open5gs/nssf.yaml.in
configs/open5gs/pcf.yaml.in
configs/open5gs/scp.yaml.in
configs/open5gs/smf.yaml.in
configs/open5gs/udm.yaml.in
configs/open5gs/udr.yaml.in
lib/sbi/context.c
lib/sbi/context.h
lib/sbi/message.c
lib/sbi/path.c
src/scp/sbi-path.c

Introduce client_delegated_config to manage delegation settings for NRF and SCP separately. This ensures that in Model C, all NRF-related procedures (registration, heartbeat, deregistration, etc.) communicate directly with the NRF without routing through the SCP. This change aligns Open5GS behavior with 3GPP standards, providing consistent direct communication for both discovery and management in Model C, and maintaining indirect communication in Model D.
- Direct Communication with NRF
```
sbi:
client:
nrf:
- uri: http://127.0.0.10:7777
```
- Indirect Communication by Delegating to SCP
```
sbi:
client:
scp:
- uri: http://127.0.0.200:7777
```
- Indirect Communication without Delegation
```
sbi:
client:
nrf:
- uri: http://127.0.0.10:7777
scp:
- uri: http://127.0.0.200:7777
delegated:
nrf: …
```

[SBI] Allow direct NRF communication in Model C by configuring delegation modes (#3399)

---

src/amf/gmm-sm.c

This commit addresses an Open5GS bug where the AMF process crashes when receiving npcf-am-policy-control service responses during UE handovers. The crash was occurring in the gmm_state_authentication() function when the AMF encountered an unexpected SBI (Service Based Interface) message from the PCF related to AM Policy Control requests.
Added a new case block in gmm_state_authentication() to explicitly handle messages with the service name OGS_SBI_SERVICE_NAME_NPCF_AM_POLICY_CONTROL.

[AMF] prevent crash on npcf-am-policy-control SBI response handling (#3671)

---

src/udm/nudm-handler.c

Previously, the function `udm_nudm_sdm_handle_subscription_create()` would trigger a fatal assertion failure if the maximum number of SDM subscriptions was reached.
This commit adds error handling to check if the subscription pool allocation fails.
If `udm_sdm_subscription_add()` returns NULL, an appropriate error message is logged, and a 400 Bad Request response is sent back to the client instead of causing a crash.

[SEC] Handle maximum SDM subscription limit gracefully (#3688)

---

lib/pfcp/path.c
lib/pfcp/path.h
src/sgwc/pfcp-path.c
src/sgwu/pfcp-path.c
src/smf/pfcp-path.c
src/upf/pfcp-path.c

This commit adds additional checks in the PFCP receive callback to ensure that a complete PFCP message is received before parsing. A minimum header length check and a total message length validation are now performed. This prevents incomplete, fragmented messages from being processed and avoids potential parsing errors and DoS conditions.

[SEC] Improve PFCP Message Validation to Prevent Fragmentation Attacks (#3689)

---

src/amf/gmm-sm.c

During handover between two gNBs, the AMF enters an invalid state when it receives an unexpected SBI response from the UDM in the process of sending a smf-select-data request. This bug could lead to an AMF crash as the state machine in gmm_state_registration encountered an unknown state.
The fix adds explicit handling for SBI messages with resource names such as AM_DATA, SMF_SELECT_DATA, UE_CONTEXT_IN_SMF_DATA, and SDM_SUBSCRIPTIONS. If the HTTP response status is not OK, CREATED, or NO_CONTENT, a warning is logged and the message is ignored. This prevents the AMF from transitioning into an abnormal state and improves overall stability during frequent handovers.

[AMF] Fix AMF crash during UE handover by handling unexpected SBI responses (#3707)

---

lib/metrics/prometheus/context.c

Prometheus v3 enforces stricter validation of the `Content-Type` header when scraping metrics. If the default configuration of Prometheus v3 is used, a `Content-Type` header is required. See the official documentation for more details:  
[Prometheus v3 Migration Guide - Scrape Protocols](https://prometheus.io/docs/prometheus/3.0/migration/#scrape-protocols).
When using the default Prometheus v3 configuration, the following error occurs:
```
Error scraping target: non-compliant scrape target sending blank Content-Type and no fallback_scrape_protocol specified for target.
```
This Pull Request fixes this issue by adding the required `Content-Type` header, ensuring compatibility with the default Prometheus v3 configuration.

Fix Prometheus v3 Content-Type Header Requirement

---

lib/pfcp/context.c

Test scenario:
- start 5G core
- wait for 5 minutes after SMF establishes PFCP association to UPF (DNS query refresh interval)
- register UE and establish PDU session
- crash
[upf] DEBUG: upf_state_operational(): UPF_EVT_N4_MESSAGE (../src/upf/upf-sm.c:51) [upf] DEBUG: upf_pfcp_state_associated(): UPF_EVT_N4_MESSAGE (../src/upf/pfcp-sm.c:185) [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:217) [upf] DEBUG: Session Establishment Request (../src/upf/n4-handler.c:66) [gtp] INFO: gtp_connect() [127.0.0.8]:2152 (../lib/gtp/path.c:60) [upf] INFO: UE F-SEID[UP:0x1230 CP:0x5817] APN[local] PDN-Type[1] IPv4[10.46.0.2] IPv6[] (../src/upf/context.c:532) [upf] INFO: UE F-SEID[UP:0x1230 CP:0x5817] APN[local] PDN-Type[1] IPv4[10.46.0.2] IPv6[] (../src/upf/context.c:532) [upf] …

[PFCP] fix crash for when PFCP NodeId is FQDN

---

lib/sbi/client.c
lib/sbi/client.h
lib/sbi/context.c
lib/sbi/context.h

Currently with the SBI interface, libcurl sets up all outgoing HTTP sessions by not binding a local port/interface/IP at all and just letting the OS routing system decide what makes sense. This is fine in certain contexts but is less than ideal in others.  Problem examples include (1) a system with multiple public IPs, (2) machines that bridge public/private networks, or (3) most important to me, the loopback interface, where the logs can get confusing because a service like the AMF can *bind* the interface 127.0.0.5 but all outgoing comms still come from 127.0.0.1.
This PR adds the optional "interface" config parameter to an SBI clienet that allows an operator to restrict the local interface to a specific interface or IP address by passing a string to libcurl. Allowable syntax includes …

[sbi] add option to support binding local interface/ip for sbi calls

---

lib/sbi/custom/links.c
lib/sbi/custom/links.h
lib/sbi/message.c
lib/sbi/nf-sm.c
lib/sbi/nnrf-build.c
lib/sbi/nnrf-build.h
lib/sbi/nnrf-path.c
lib/sbi/nnrf-path.h

Before this, there were 2 different ways to search for neighbouring NF's:
a) in the case AMF was started _before_ UDM, AMF would create subscription to NRF to notify it when a UDM would (un)register. In this case, NF instance would remain in AMF's context indefinitely.
b) in the case AMF was started _after_ UDM, AMF would have to use NF discovery mechanism to search for NF's. In this case, NF instance would remain in AMF's context for the duration of Search's validity (defaults to 30 seconds). After validity expires, NF would expire. This means that for heavy traffic situations, AMF would constantly issue discovery requests.
[SBI] save only wanted NF instances on NF List Retrieval
When retrieving a list of NF Instances from NRF, save only the NF's that we want. Check the NF instance …

[SBI] retrieve all currently registered NF's on app startup

---

src/upf/context.c

When receiving a PFCP Session Establishment Request with an invalid PDN type(0), the UPF would crash due to a failed assertion.
This commit improves error handling by:
- Removing the session_type assertion check that caused the crash
- Changing warning log to error log for better visibility
- Returning CAUSE_SERVICE_NOT_SUPPORTED instead of proceeding with invalid type
This prevents potential DoS attacks through malformed PFCP messages.

[UPF] Fixes: Crash in upf_sess_set_ue_ip when PDN type is invalid (#3727)

---

src/ausf/ausf-sm.c

Hi @acetcom,
During testing, I found that sending a blank `supiOrSuci` to the AUSF would result in a crash.  I used this command to cause the crash:
```
curl -v -X POST --http2-prior-knowledge "http://127.0.0.11:7777/nausf-auth/v1/ue-authentications" -d '{"supiOrSuci":"","servingNetworkName":"5G:mnc533.mcc302.3gppnetwork.org"}'
```
This was the observed failure:
```
02/26 23:19:15.805: [core] FATAL: ogs_hash_get_debug: Assertion `klen' failed. (../lib/core/ogs-hash.c:316)
02/26 23:19:15.805: [core] FATAL: backtrace() returned 10 addresses (../lib/core/ogs-abort.c:37)
/usr/local/lib/x86_64-linux-gnu/libogscore.so.2(ogs_hash_get_debug+0x13a) [0x7f82918be92e]
/usr/local/bin/open5gs-ausfd(+0x668c) [0x556fdd9d168c]
/usr/local/bin/open5gs-ausfd(+0x673a) [0x556fdd9d173a] …
```

[AUSF] Check length of SUCI_or_SUPI before trying to process

---

src/ausf/ue-sm.c

Hi @acetcom,
I have noticed that while running open5gs's AUSF with a commercial AMF, that certain scenarios would cause the AUSF to stop functioning over time.  I would observe this error in the logs:
```
ERROR: ogs_pool_id_calloc() failed (../src/ausf/context.c:138)
ERROR: Not found [POST] (../src/ausf/ausf-sm.c:158)
```
We do not have many devices on this network.  From further checking of the logs, a single UE would generate multiple different SUCIs over many failed authentication attempts causing the memory pool to be full at around 1024 `ausf_ue`'s.  I am suggesting this change to remove an `ausf_ue` if the user is not found in the UDM.

[AUSF] Cleanup ausf_ue when it is not found in UDM

---

src/mme/s1ap-handler.c
tests/attach/crash-test.c
tests/common/s1ap-build.c
tests/common/s1ap-build.h

This pull request resolves an issue where the system would crash when Inter_SystemInformationTransferType was not present.

[SEC] Fix crash in eNBDirectInformationTransfer due to missing Inter_SystemInformationTransferType

---

src/ausf/ue-sm.c
src/smf/gsm-sm.c
src/udm/nudr-handler.c

In case that NF do not send ProblemDetails in the response. Do not assume that ProblemDetails is always present, to prevent null pointer dereferencing.

[all] fix possible null dereference when using ProblemDetails

---

lib/sbi/client.h
lib/sbi/context.c
lib/sbi/context.h
lib/sbi/mhd-server.c
lib/sbi/nghttp2-server.c
lib/sbi/path.c
lib/sbi/server.c
lib/sbi/server.h
src/amf/gmm-handler.c
src/amf/init.c
src/amf/namf-build.c
src/amf/namf-handler.c
src/amf/nnrf-handler.c
src/amf/sbi-path.c
src/ausf/init.c
src/bsf/init.c
src/nrf/init.c
src/nssf/init.c
src/pcf/init.c
src/scp/context.c
src/scp/context.h
src/scp/init.c
src/sepp/context.c
src/sepp/context.h
src/sepp/init.c
src/smf/init.c
src/udm/init.c
src/udr/init.c

This pull request addresses Issue #3740, where an incomplete NF instance cleanup due 
to a reference counting error causes the system to fall back to the default port 80 
after a UDR restart. The stale nf_instance pointer retained in service_type_array results 
in an invalid client being used, leading to connection failures when the UE re-registers.
In curl 8.9.1, the issue is compounded by curl reusing existing connections when another 
NF restarts, which causes the nghttp2 server to send an RST. To resolve this, we now 
send a GOAWAY frame to every active session on server shutdown, ensuring graceful 
termination and preventing RST errors. This behavior was not observed in previous versions 
(e.g. curl 7.81.0).
This PR consists of two commits:
1. [SBI] Send GOAWAY on shutdown for all …

[SBI] Fix NF Instance Cleanup and Prevent RST on NF Restart (#3740)

---

configs/attach.yaml.in
configs/meson.build
lib/sbi/client.c
tests/attach/abts-main.c

Previously, sample.yaml was used for both 5GC and EPC attach tests. Because SMF had SBI configured, it sent a register PUT to NRF even in EPC-only tests (where nrf/scp was not run), leading to a missing HTTP response and connection timer expiry.
Now, attach.yaml is used for EPC, preventing the unwanted NRF registration.

[SMF] Separate EPC-only attach config to avoid NRF register timeout

---

src/mme/emm-build.c
src/mme/emm-handler.c
src/mme/mme-context.c
src/mme/mme-context.h
src/mme/mme-gn-build.c
src/mme/mme-gn-handler.c
src/mme/mme-s6a-handler.c
tests/attach/crash-test.c
tests/attach/guti-test.c
tests/attach/issues-test.c
tests/attach/simple-test.c
tests/attach/ue-context-test.c
tests/non3gpp/epdg-test.c
tests/volte/bearer-test.c
tests/volte/rx-test.c
tests/volte/session-test.c
tests/volte/simple-test.c
tests/volte/video-test.c

Previously, the EPC used the UE-provided KSI directly in the Authentication Request (except for the special case where the UE sent OGS_NAS_KSI_NO_KEY_IS_AVAILABLE, which was reset to 0).
This commit changes the EPC to follow the 5G Core approach for issuing KSI in Attach-Request.
Now, when a Attach Request is received and a new Authentication Vector is generated, the EPC performs the following steps:
- Extract the KSI value from the UE's request.
- Increment the extracted KSI by 1.
- Use the incremented KSI in the Authentication Request sent to the UE.
This detailed process ensures that the EPC issues the KSI consistently with 5G Core standards, improving key management and interoperability.

[KSI] Update EPC KSI issuance to match 5G Core behavior

---

src/amf/context.c
src/amf/context.h
src/amf/gmm-sm.c
src/mme/emm-handler.c
src/mme/emm-handler.h
src/mme/emm-sm.c
src/mme/mme-context.c
src/mme/mme-context.h
tests/attach/auth-test.c
tests/registration/auth-test.c
tests/registration/reset-test.c

- Backup sensitive security context fields (e.g. xres, kasme, rand, autn, keys, counters) when transitioning from REGISTERED state.
- Set the can_restore_security_context flag in common_register_state() based on whether the transition originates from a REGISTERED or de-registered state.
- In emm_state_authentication(), restore the security context and revert to the REGISTERED state on authentication failure only if restoration is allowed; otherwise, transition to an exception state.
- Remove the redundant unconditional state transition in the cleanup block to prevent overriding a valid restoration.

[AMF/MME] Fix security context restoration and state transition cleanup (#3756)

---

lib/sbi/context.h
lib/sbi/nnrf-build.c
lib/sbi/nnrf-handler.c
src/amf/context.c

- [SBI] replace calls to `free_<nf>_info()` with `OpenAPI_<nf>_info_free()`   - this commit can be removed in case we prefer manual free()-ing of OpenAPI structs or if we do something differently than the auto-generated code
- fix AMF crash in case it's configuration contains multiple TAC ranges which causes an out-of-array-bounds write
- add support for TAI ranges in the AmfInfo instead of manually adding multiple TAI items

Add support for TAI ranges in AmfInfo

---

src/amf/context.c
src/amf/context.h
src/amf/gmm-sm.c
src/mme/emm-sm.c
src/mme/mme-context.c
src/mme/mme-context.h
tests/attach/crash-test.c

Renamed backup/restore security context functions to save/restore memento and updated flag to "can_restore_context". Updated AMF and MME state machines to restore context on failure, preventing malicious deletion triggered by spoofed NAS messages.

[AMF/MME] Fix UE context deletion vulnerability using memento restoration (#3754)

---

src/amf/context.c
src/mme/mme-context.c

When a UE handover occurs, the target UE may already be removed. This patch adds a NULL pointer check and logs an error instead of causing a segmentation fault in both enb and sgw deassociation functions.

[AMF/MME] Fix segfault on NG/S1 handover cancel by checking for NULL target UE (#3789)

---

lib/sbi/message.h
lib/sbi/nnrf-build.c
src/amf/nsmf-build.c
src/amf/nudm-build.c
src/nrf/nnrf-build.c
src/smf/nudm-build.c

This commit fixes an issue where the callback header (3gpp-Sbi-Callback) was incorrectly added in non-callback requests. Specifically, for registration (PUT) and subscription requests in the AMF and SMF modules, the callback header was included even though these are not asynchronous notifications.
Changes include:
- Removing the callback header assignment in src/amf/nudm-build.c and src/smf/nudm-build.c for registration and subscription requests.
- Removing the callback header in NRF subscription-related builds in lib/sbi/nnrf-build.c where it was not required.
- Adding the callback header only for actual notification or callback operations (e.g. in src/amf/nsmf-build.c for N1/N2 transfer failure and in src/nrf/nnrf-build.c for NF status notifications).
- Introducing a new callback macro …

[SBI] Fix improper inclusion of callback headers in non-callback requests (#3798)

---

lib/core/ogs-epoll.c
lib/core/ogs-signal.c
src/main.c

In Open5GS 2.7.x, when using curl 8.x with external epoll, an issue occurred where the peer connection was closed, triggering EPOLLERR. At this point, POLL_OUT should have been set to trigger the write event handler, invoking `event_cb()` and calling `curl_multi_socket_action`. This would allow `curl_multi_info_read` to execute without blocking.
However, when `event_cb()` wasn't invoked, `curl_multi_socket_action` was not called, causing `curl_multi_info_read` to block. This resulted in a busy loop in epoll, continuously checking for the closed peer connection.
This issue specifically affects Open5GS 2.7.x with curl 8.x, and is observed on Ubuntu versions starting from **noble** and later. It does not occur on Ubuntu Jammy.
The solution involves globally ignoring SIGPIPE and fixing the …

[CORE] Fix busy loop and blocking in curl with EPOLLERR handling in Open5GS 2.7.x (#3807, #2411, #2312)

---

lib/dbi/ims.c
lib/proto/types.h
src/hss/hss-context.c

This PR enhances the SAA message generation by fetching Initial Filter Criteria (IFC) data from the database and embedding it into the cx-user-data XML tag. The change ensures SAA responses dynamically include subscriber-specific IFC configurations, improving compliance with 3GPP Cx interface requirements. Integration tests validate data consistency, and existing APIs remain unaffected. This enables richer service triggering for VoLTE/IMS use cases.

[HSS,DBI] Fetch IFC Data from DB and Insert into CX User Data AVP

---

src/hss/hss-context.c
src/smf/npcf-build.c

This commit enhances the SM Policy request sent to the PCF by incorporating user location information and time zone data.
The SMF now builds a userLocationInfo structure using the session's NR TAI and NR CGI details, along with a timestamp generated from the current GMT time.
Additionally, the UE's time zone is included in the request context, and the ratType is explicitly set to NR.

[SMF] Add userLocationInfo and timeZone to PCF SM Policy request (#3755)

---

lib/diameter/s6a/message.c
lib/diameter/s6a/message.h
src/hss/hss-s6a-path.c

This commit adds support for two Supported-Features AVPs in the UpdateLocationAnswer (ULA) to enable 5G-NSA roaming. The first AVP includes subscriber restrictions, while the second AVP signals that NR as Secondary RAT is supported. Updates include modifications to lib/diameter/s6a/message.c, lib/diameter/s6a/message.h, and src/hss/hss-s6a-path.c.

[HSS,S6A] Add two Supported-Features AVPs to ULA for 5G-NSA roaming (#3832)

---

src/udm/ue-sm.c

- In `udm_ue_state_operational()`:
- Wrap the call to `udm_nudr_dr_handle_subscription_authentication()` in an `if` check.
- On failure (`false`), log an error via `ogs_error("udm_nudr_dr_handle_subscription_authentication() failed")`.
- Transition the FSM to `udm_ue_state_exception` using `OGS_FSM_TRAN()`.
This change ensures that failures during subscription authentication REST calls are not silently ignored, and that the UE state machine moves into an exception state for proper error handling and recovery.

[UDM] Update UE state machine to handle authentication retrieval errors (#3864)

---

src/amf/gmm-handler.c

When a UE asks for a DNN that the core does not support, it would be helpful to expand the error message in the AMF to print the name of the DNN for easier debugging.

more verbose DNN reject message

---

src/bsf/bsf-sm.c
src/pcf/am-sm.c
src/pcf/context.c
src/pcf/context.h
src/pcf/event.h
src/pcf/namf-build.c
src/pcf/namf-build.h
src/pcf/nbsf-build.c
src/pcf/nbsf-handler.c
src/pcf/nnrf-handler.c
src/pcf/npcf-handler.c
src/pcf/npcf-handler.h
src/pcf/nudr-build.c
src/pcf/nudr-build.h
src/pcf/nudr-handler.c
src/pcf/nudr-handler.h
src/pcf/pcf-sm.c
src/pcf/sbi-path.c
src/pcf/sbi-path.h
src/pcf/sm-sm.c
src/smf/context.c
src/smf/context.h
src/smf/npcf-build.c
src/smf/nsmf-handler.c

Separate the monolithic PCF_UE structure into PCF_UE_AM and PCF_UE_SM to fully decouple AM‐ and SM‐policy lifecycles.

[PCF] split PCF_UE context into distinct AM and SM contexts (#3868)

---

lib/sbi/nghttp2-server.c

Prior to this change, `session_write_callback()` unconditionally asserted that `sbi_sess->poll.write` was non-NULL when the write queue drained, then removed it from the poll set. In edge cases—particularly when using curl 8.x with external epoll and `SIGPIPE` disabled—a late `EPOLLOUT` or errant write-ready notification could arrive after `poll.write` had already been cleared. This triggered the assertion in `nghttp2-server.c:1765`, aborting the process on shutdown or session teardown.
This commit replaces the hard assertion with a runtime guard. If `poll.write` is present, it is removed and reset to NULL as before. If it is already NULL, we emit an warning log (`ogs_warn`) instead of aborting. This ensures any stray write events after cleanup are safely ignored, allowing a clean exit …

[SBI] Guard against missing poll.write in session_write_callback to prevent shutdown assertion (#3893, #3807, #2411, #2312)

---

src/amf/gmm-handler.c

In case AMF is configured for multiple PLMN's, it would send a wrong GUAMI in the Registration Accept message to the UE, also in other NAS and SBI messages. Previously, it would only send the first configured PLMN.

[AMF] save the correct serving GUAMI for particular UE

---

lib/sbi/custom/links.c

Previously, Open5GS assumed the _links map contained an array under the key "items". However, the 3GPP specification (TS29.510 section 4.9.4 and TS29.501 Table 6.1.6.2.25-1) defines this member name as "item".
As a result, when interacting with vendor NRF implementations that use "item", Open5GS could not find the array and logged "No items", causing JSON errors.
This change updates both serialization and parsing in lib/sbi/custom/links.c:
- In ogs_sbi_links_convertToJSON(), replace the property name "items" with "item" when building JSON.
- In ogs_sbi_links_parseFromJSON(), retrieve the array under "item" and adjust the error message to "No item" if the member is missing.
With these corrections, Open5GS will correctly handle NRF responses using "item" and remain compliant with the …

[SBI] Fix parsing and serialization of _links "item" array (#3897)

---

src/amf/ngap-build.c

Cause goes before TimeToWait accoding to 3GPP TS 38.413 ASN.1 definition "NGSetupFailureIEs NGAP-PROTOCOL-IES" and section 9.2.6.3.

[AMF] Fix order of IEs in NG Setup Failure

---

src/smf/context.c
src/smf/gn-handler.c
src/smf/npcf-handler.c
src/smf/s5c-handler.c

In src/smf/context.c:
- Wrap UPF selection logic in a conditional that checks if pfcp_node is non-NULL.
- If no UPF is available (pfcp_node == NULL), log an error and assert that sess->pfcp_node remains NULL, instead of crashing.
- Only call selected_upf_node() and set up the GTP session when a prior UPF entry exists.
In src/smf/gn-handler.c:
- After invoking smf_sess_select_upf(), verify sess->pfcp_node.
- If no UPF was selected, log an error ("No UPF available for session") and return OGS_GTP1_CAUSE_SYSTEM_FAILURE instead of asserting.
In src/smf/s5c-handler.c:
- Mirror the same check for sess->pfcp_node after smf_sess_select_upf().
- If no UPF is available, log an error and return OGS_GTP2_CAUSE_SYSTEM_FAILURE.
- If the selected UPF is not yet PFCP-associated, log a specific error …

[SMF] Handle missing UPF gracefully in SMF session selection (#3907)

---

src/smf/ngap-handler.c
tests/handover/5gc-xn-test.c

Fix missing N2 signaling when tunnel information is unchanged, causing AMF crash on repeated PathSwitchRequest
When a second PathSwitchRequest arrives without any tunnel changes, the handler previously returned HTTP 204 No Content and omitted N2 information.
This led to a fatal assertion in the AMF SM context, since it expected to receive updated N2 data even when the tunnel remained the same.
This patch modifies ngap_handle_path_switch_request_transfer to build and send the N2 SM buffer in the “else” branch.
It calls ngap_build_path_switch_request_ack_transfer to construct the Path Switch Request Acknowledge N2 message and then delivers it with smf_sbi_send_sm_context_updated_data_n2smbuf.
A new test case is also added to verify that N2 signaling is correctly transmitted when tunnel …

[SMF] Include N2 ACK for unchanged tunnel on repeated PathSwitchRequest (#3909)

---

src/amf/gmm-sm.c
src/mme/emm-sm.c

Prevent crashes when UE context is missing in AMF and MME by replacing direct assertions with conditional checks and error logging.
Removed unconditional ogs_assert(ran_ue) in AMF's GMM handlers and ogs_assert(enb_ue) in MME's EMM handlers.
Now, if the UE context lookup returns NULL, log an error (including SUPI/IMSI, NAS message type, and IDs), dump the NAS packet in hex for debugging, and exit the handler gracefully instead of aborting.

[AMF/MME] Prevent AMF/MME crash when UE context is deleted (#3910)

---

src/amf/nas-path.c
src/mme/mme-s6a-handler.c

According to 3GPP TS 29.272 Annex A, when the HSS/UDM responds with DIAMETER_ERROR_USER_UNKNOWN (5001), the MME/AMF should respond to the UE with NAS EMM cause #8 (EPS services and non-EPS services not allowed), rather than cause #11 (PLMN not allowed).
Previously, Open5GS returned cause #11 by default. However, this behavior is problematic for private LTE environments where multiple operators may use the same PLMN (e.g., 999/99 as per ITU-T E.212). In such cases, a UE rejected with cause #11 will add the PLMN to its Forbidden PLMN list (FPLMN), causing the device to avoid that PLMN for an extended period—even if another compatible private network using the same PLMN exists.
This patch restores compliance with TS 29.272 by changing the default mapping from cause #11 to cause #8 in both …

[MME/AMF]: Align reject cause for unknown UE/IMSI with 3GPP TS 29.272 Annex A (#3924)

---

lib/sbi/client.c

In lib/sbi/client.c, the conditional compilation for CURLMOPT_MAX_CONCURRENT_STREAMS was using #ifdef, which does not ensure the option is set when the symbol is undefined.
Replace the check with #if CURL_AT_LEAST_VERSION(7,67,0) so that the client applies the max concurrent streams setting on supported libcurl versions. This fixes pool.event always showing the default value and enables dynamic adjustment according to pool.stream.

[SBI] use CURL_AT_LEAST_VERSION for MAX_CONCURRENT_STREAMS check

---

src/amf/ngap-handler.c
tests/handover/5gc-n2-test.c

In the previous implementation, the AMF would send a Partial-handover error indication whenever it encountered a session not found in the subscriber DB, even if valid sessions remained. This resulted in unexpected error responses during NG handover.
To resolve this, we record the initial SMF transaction count before iterating through the UE session list. Sessions without a valid SMF context now produce a warning and are skipped, while continuing to send Handover Notify messages for provisioned sessions. After processing, we compare the SMF transaction count to the initial value. If no valid sessions were handled, we send a Partial-handover error indication.
With this change, unprovisioned sessions no longer trigger a premature error indication, allowing valid PDU sessions to complete NG …

[AMF] Skip unprovisioned sessions to prevent premature error indication (#3951)

---

src/amf/nas-path.c
src/amf/nas-path.h
src/amf/ngap-build.c
src/amf/ngap-build.h

When SM Context creation fails (e.g. 504 from SMF) the AMF continued to build and send a NAS downlink message by dynamically looking up the AMF UE context from ran_ue->amf_ue_id inside ngap_build_downlink_nas_transport(). If ran_ue_deassociate() had already removed that mapping, the lookup would return NULL, triggering a fatal assertion and crashing the AMF.
This patch changes:
1. nas_5gs_send_to_downlink_nas_transport() and ngap_build_downlink_nas_transport() signatures to accept an explicit amf_ue_t * parameter alongside ran_ue_t *.
2. All calls to nas_5gs_send_to_downlink_nas_transport() to pass the correct amf_ue pointer (from sess->amf_ue_id).
3. Removal of the dynamic lookup and fatal assertion in ngap_build_downlink_nas_transport(), replacing it with ogs_assert(amf_ue) on the …

[AMF/SEC] pass AMF UE context to downlink NAS transport to prevent fatal crash (#3950)

---

lib/proto/types.c
src/smf/context.c
src/smf/gn-build.c
src/smf/gsm-build.c
src/smf/s5c-build.c

Previously, malformed Protocol Configuration Options (PCO) data would trigger ogs_assert failures in both the generic parser and SMF build routines, causing the SMF process to abort unconditionally.
This commit replaces those fatal assertions with conditional checks:
In ogs_pco_parse(), switch from ogs_assert(size == data_len) to ogs_expect(size == data_len), allowing the function to return gracefully.
In SMF's PCO build (smf_pco_build) and all downstream build paths (including GN, GSM, S5C modules), replace ogs_assert(pco_len > 0) with explicit if (pco_len <= 0) checks that:
Ensure that malformed or incomplete PCOs no longer crash the process, but instead are handled cleanly so the network function can continue operating.

[SMF] Improve robustness of PCO parsing and building by replacing fatal assertions with error handling (#3969)

---

src/amf/context.c
src/amf/context.h
src/amf/ngap-handler.c
src/amf/nsmf-handler.c
src/amf/sbi-path.c
src/mme/mme-context.c
src/mme/mme-context.h
src/mme/mme-gtp-path.c
src/mme/mme-s11-handler.c
src/mme/s1ap-handler.c

**Problem:**
During inter-eNB/RAN handover scenarios, such as S1/N2 handover followed by X2/Xn handover cancellation, the UE context may end up partially moved or duplicated across multiple eNBs. If the handover is canceled by the target eNB and followed by subsequent UE Context Release or PathSwitchRequest procedures, the MME can crash due to inconsistent context state. Specifically, when deassociating the mme_ue <-> enb_ue (or amf_ue <-> ran_ue) pair, the code unconditionally resets the association fields (`mme_ue->enb_ue_id`, `enb_ue->mme_ue_id`, etc.), even if they no longer reflect an actual association due to the earlier handover cancellation.
**Root Cause:**
The MME or AMF state machine incorrectly assumes that the associated context IDs are still valid and proceeds to unlink the …

[AMF/MME] Fix crash during S1/X2 handover cancellation by validating UE context association before deassociation (#3983)

---

lib/core/ogs-sockaddr.c
lib/core/ogs-sockaddr.h
src/smf/context.c
src/smf/context.h

This change revises the existing ogs_addaddrinfo() function to handle partial failures without aborting the process, ensure proper cleanup of any nodes allocated before an error, and emit more informative logs (including getaddrinfo() errors and situations where no usable addresses are returned). By introducing “tail” and “first_new” pointers, new entries can be appended to an existing list and safely detached if memory allocation fails mid‐stream.
On top of that, a new helper API, ogs_sockaddr_from_ip_or_fqdn(), was added. It automatically detects whether its input is a numeric IPv4/IPv6 literal or a hostname (using AI_NUMERICHOST when appropriate), then delegates resolution to ogs_addaddrinfo(). Errors are logged at the error level but do not trigger a fatal exit, and any partial lists …

[SMF] Refactor core address‐resolution to robustly support both IP literals and hostnames (#4008)

---

src/smf/context.c
src/smf/nsmf-handler.c

Previously, Outer Header Removal was set according to PDU session type. However, outer header IP version is independent of inner packet IP version or PDU session type. It typically depends on UPF and gNB configuration. Set it to `GTP-U/UDP/IP` to handle both IPv4 and IPv6 cases, according to _TS 29.244, Table 8.2.64-1, Note 4: "The CP function shall use this value to instruct UP function to remove the GTP-U/UDP/IP header regardless it is IPv4 or IPv6."_
No changes at UPF are necessary because it already ignores Outer Header Removal Description type and Kernel correctly decapsulates the outer IP header at socket level.

[SMF] Use PFCP Outer hdr. removal type IP regardless of sess. type

---

lib/nas/5gs/types.c
src/smf/gsm-handler.c

The older version of the code was wrong (or at least not exactly
correct) in many (corner) cases.
* Split the parsing of Packet Filter List into its own helper function
to simplify the code
* Improve error logging to provide more info on which QoS rule failed.
* Add some extra logic checking match between 'Length of QoS rule' and
existance of m+1 and m+2 bytes.
* Correct logic checking expected/unexpected presence of m+1 and m+2
octets based on Rule Operation Code according to specs.

[5G-NAS] Improve QoS Rules parsing

---

src/mme/sgsap-sm.c

This is not mentioned anywhere in the specs and may just create an endless loop of open5gs-mmed re-connecting and VLR sending a RESET.

[MME] SGsAP: Do not close SCTP socket upon rx SGsAP-RESET-INDICATION

---

src/mme/sgsap-build.c
src/mme/sgsap-build.h
src/mme/sgsap-handler.c
src/mme/sgsap-handler.h
src/mme/sgsap-path.c
src/mme/sgsap-path.h
src/mme/sgsap-sm.c
src/mme/sgsap-types.h

Answer ALERT-REQUEST with either ALERT-ACK or ALERT-REJECT.
This commit leaves unimplemented (to be implemented in the future) the part regarding setting of internal NEAF flag for UE inside MME and then triggering SGsAP-UE-ACTIVITY-INDICATION towards VLR.
See 3GPP TS 23.272 and 3GPP TS 29.118 (grep for "Alert" and "Activity") for further information.

[MME] SGsAP: Implement initial Rx of ALERT-REQUEST

---

lib/sbi/client.c
lib/sbi/mhd-server.c
src/amf/amf-sm.c
src/amf/gmm-sm.c

This pull request addresses several crash and stability issues in the AMF and SBI layers, primarily related to unhandled HTTP methods and unsafe timer callbacks. These changes aim to improve the robustness of AMF when handling unexpected SBI messages and prevent use-after-free (UAF) or double-free scenarios under heavy load.
---
**Commits:**  
- [`81fe41c`](https://github.com/open5gs/open5gs/commit/81fe41c8188bd3f5e9676a9f5f62dea24c246ae6)  
- [`4303bb4`](https://github.com/open5gs/open5gs/commit/4303bb4b64540a64235a4c76dfec58fd83fe0f36)
**Details:**
- Previously, if the AMF received a `PATCH` or `DELETE` request for the Registration API while in `gmm_state_authentication`, it would crash because these HTTP methods were not handled.
- These scenarios appear to be caused by race …

[AMF][SBI] Fix AMF crashes and prevent timer callbacks from accessing freed objects (#4074)

---

src/amf/ngap-handler.c
src/mme/s1ap-handler.c
src/mme/s1ap-path.c
src/mme/s1ap-path.h

- Added explicit size checks for critical IE fields (PLMNIdentity, TAC, GTP-TEID, Cell-ID, UE security capability algorithms, etc.) before memcpy() operations.
- When size mismatch is detected, log an error and return an Error Indication (or Setup Failure) with appropriate protocol cause (semantic_error or message_not_compatible_with_receiver_state).
- Introduced s1ap_send_error_indication1(enb_ue_t *enb_ue, ...) as a helper for cases where ENB UE context is available directly. s1ap_send_error_indication2(mme_ue_t *mme_ue, ...) now delegates to the new function, reducing code duplication.
- Replaced ogs_assert() checks with graceful error handling paths to avoid abnormal process termination.
This improves robustness against malformed or non-compliant NGAP/S1AP messages and prevents …

[AMF/MME] Add size validation for NGAP/S1AP IE fields to prevent crashes (#4087)
