open5gs/open5gs

- src/mme/mme-context.c
New format to SGSAP for mme.conf:
sgsap:
addr: 127.0.0.1
port: 29118
tai:
plmn_id:
mcc: 001
mnc: 01
tac: 12345
lai:
plmn_id:
mcc: 002
mnc: 02
lac: 54321
Thanks
> Change in the config to allow different MCC/MNC in the LAI for CSFB

- docs/_docs/guide/04-setting-up-kamailio-IMS.md
I have edited the IMS guide for easier/faster setup by installing from the deb packages
> Edit IMS setup guide to install from deb packages

- docs/_docs/guide/01-quickstart.md
Signed-off-by: Sudheesh Singanamalla <sudheesh@cs.washington.edu>
> Adds Additional troubleshooting documentation for issues experienced

- src/mme/sbc-handler.c
buidl -> build in `src/mme/sbc-handler.c`
> fix trivial typos in comments

- docs/_docs/tutorial/02-VoLTE-setup.md
- Added more info to disable VoIP calling so that it doesnt intefere with VoLTE call test
- Checkout 5.3 branch of kamailio (better for IPSec requiring phones)
> Minor doc improvement

- docs/_docs/tutorial/03-VoLTE-dockerized.md
Hi @acetcom ,
Not sure if I followed the right format of writing a tutorial.  I saw quite a few people got stuck by VoLTE in the issue list.  Hope the tutorial help a bit.  Also, many thanks to @herlesupreeth 's help in the discussion of issue #337 .
Thank you!
> Adopt tutorial format to dockerized VoLTE lab

- webui/src/components/Subscriber/View.js
Switched UL and DL values as they were reversed (DL showing UL & UL showing DL)
> Update View.js to switch UL/DL Values in Web UI

- src/smf/fd-path.c
- Added Gx Vendor-Specific-Application-Id for SMF
> Add Vendor-Specific-Application-Id in CER of SMF to advertise Gx Diameter application

- docs/_pages/docs.md
Added links to some recent posts I did on Static IPs and using UERANSIM
> Added links to Docs Page for UERANSIM and Static IP posts

- src/smf/context.c
Hello
I created an info log to show when the user disconnect the APN, with IMSI, APN and IPv4/IPv6.
Thanks
Romeu Medeiros
> Update to generate SMF Log for Session Removed.

- docker/debian/latest/stretch
- docs/_docs/platform/02-centos.md
- vagrant/Vagrantfile
Hi All,
I just started working with Open5GS a couple of days ago and ran into a couple of minor hiccups when trying to follow the instructions for CentOS 8, so I updated the CentOS 8 instructions a little bit, added a Vagrantfile to create a clean CentOS 8 virtual machine which can be used as the baseline for following these instructions.
There is also one additional commit to remove a bad, self referential symlink which was causing issues.
thanks!
Dan
> Centos devel

- docs/_docs/hardware/01-genodebs.md
I tested this two models without any problem
> Added NOKIA enodeBs

- src/amf/ngap-handler.c
As described in TS 38413 9.2.5.3 UPLINK NAS TRANSPORT
IE/Group Name | Presence | Range | IE type and reference | Semantics description | Criticality | Assigned Criticality
-- | -- | -- | -- | -- | -- | --
Message Type | M |   | 9.3.1.1 |   | YES | ignore
AMF UE NGAP ID | M |   | 9.3.3.1 |   | YES | reject
RAN UE NGAP ID | M |   | 9.3.3.2 |   | YES | reject
NAS-PDU | M |   | 9.3.3.4 |   | YES | reject
User Location Information | M |   | 9.3.1.16 |   | YES | ignore
AMF handle UE-location in ngap uplink nas transport, maybe ue update it's location.
> handle user location in ngap uplink nas transport

- docker/build/Dockerfile
Changed the name of the default branch so it meets new naming scheme
> Changed the branch name

- docs/_docs/tutorial/02-VoLTE-setup.md
- docs/_docs/tutorial/03-VoLTE-dockerized.md
Following are the corrections in document
1. Fix the IMPU added for a IMS user
2. Added QCI settings if Video call is attempted
> Update IMPUs to be added for a IMS user

- src/mme/mme-s11-build.c
Add indication Dual Address Bearer in the create session request when the PDN is IPv4v6 Type, Info: 3GPP TS 29.274
For resolve the issue: #1047 
Thanks
Romeu Medeiros
> Indication Dual Address Bearer for create session request.

- lib/pfcp/types.h
Hi Sukchan,
I've created this PR to reflect my changes to main repo in PR 1289.
> reflect PR #1289

- configs/systemd/99-open5gs.network
- configs/systemd/open5gs-amfd.service.in
- configs/systemd/open5gs-ausfd.service.in
- configs/systemd/open5gs-mmed.service.in
- configs/systemd/open5gs-nssfd.service.in
- configs/systemd/open5gs-sgwcd.service.in
- configs/systemd/open5gs-sgwud.service.in
- configs/systemd/open5gs-smfd.service.in
- configs/systemd/open5gs-udmd.service.in
- configs/systemd/open5gs-upfd.service.in
This pull request refines the systemd unit file sequencing to allow clean startup with ogstun and the upf when the machine is using systemd-networkd. See https://github.com/open5gs/open5gs/issues/826 for more details.
> Systemd sequencing

- src/smf/gn-build.c
In the event we have 2 local IP addresses available for use, put the one
having same IP version in "GGSN Address *" IE, and the one with the
other IP version in "Alternative GGSN Address *" IE.
> [SMF] Fix adding 2 IP addresses to one GSN Address IE

- src/smf/gn-build.c
In the event we have 2 local IP addresses available for use, put the one
having same IP version in "GGSN Address *" IE, and the one with the
other IP version in "Alternative GGSN Address *" IE.
Same fix was applied recently to CreatePDPContextResponse.
> [SMF] UpdPDPCtxRsp: Fix adding 2 IP addresses to one GSN Address IE

- src/smf/n4-handler.c
3GPP TS 29.244 sec 8.2.21 "Report Type" states:
At least one bit shall be set to "1". Several bits may be set to "1".
> [SMF] PFCP Session Report Req: Allow receiving multiple bits in Report Type

- lib/pfcp/handler.c
As per 3GPP TS 29.244 Table 7.5.4.4-1 those IEs are optional, and shall
be applied if values need to be modified.
> [PFCP] Avoid requiring optional fields in Update URR IE

- src/smf/gx-path.c
Catch Origin-Host during CCA and set it as Destination-Host during
subsequent CCRs. This way we ensure UPDATE/TERMINATION Requests are sent
back explicitly to the same Diameter peer. Moreover, it seems
freediameter relies on this AVP to properly send the message over the
correct SCTP association when several diameter peers are available.
> [SMF] Gx: Add Destination-Host AVP to CCR

- src/smf/gx-handler.c
- src/smf/gx-path.c
- src/smf/smf-sm.c
Related: https://github.com/open5gs/open5gs/issues/1455
> [SMF] Gx: Fix crash receiving DIAMETER_UNABLE_TO_DELIVER

- misc/db/python/README.md
This resolved https://github.com/open5gs/open5gs/issues/1425 for me.
> update instructions for adding a subscriber with Python

- src/smf/gx-path.c
AN-Trusted AVP is only relevant for non-3GPP access networks e.g. WLAN.
This commit address following aspects:
- Adds a check for non-3GPP access network in order to include AN-Trusted AVP in CCR or not.
- Clears the M bit for AN-trusted AVP as per TS 29.212 version 16.4.0, Table 5.4.0.1
- Handles scenario where ePDG is not able to acquire access technology type and GTPv2 RAT Type is set to Virtual (TS 29.274 version 16.11.0, Table 7.2.1-1)
> Fix AN-Trusted AVP sent in CCR

- src/smf/event.c
The ogs_pool*() APIs are not thread safe. Since we alocate smf_event
from both the main thread and some worked freeDiameter thread, we need
tro protect it to avoid concurrent access to fields.
Related: https://github.com/open5gs/open5gs/issues/1543
> [SMF] Prevent concurrent access to ogs_pool allocating smf_event

- lib/sbi/context.c
- lib/sbi/context.h
- src/nrf/nrf-sm.c
> [NRF] Don't abort if there are too many registered NF instances

- configs/open5gs/amf.yaml.in
- src/amf/context.c
- src/amf/context.h
- src/amf/init.c
- src/amf/meson.build
- src/amf/metrics.c
- src/amf/metrics.h
AMF initial metrics support.
Added metrics:
- ran_ue
- amf_session
- gnb
> AMF metrics initial support

- lib/pfcp/types.h
this commit is made to reflect changes in PR open5gs#1581
> PR open5gs#1581

- lib/pfcp/types.h
Updating the apply action size.
> Apply action ie

- src/smf/npcf-handler.c
Signed-off-by: networkmama <networkmama12@gmail.com>
> Set v4/6 flag in F-TEID IE request type

- misc/db/open5gs-dbctl
I did not find the purpose of their use
> removing extra lines

- src/amf/namf-handler.c
[AMF] Accept Deregistration Notification from UDM only for registered UE
Add additional check when receiving Deregistration Notification from
UDM. UE should already be in registered state before accepting the
request and deregistering the UE.
Also add additional check that PCF association policy exists before
sending a delete request to PCF.
> [AMF] Accept Deregistration Notification from UDM only for registered UE

- docs/_docs/hardware/01-genodebs.md
Add some Ericsson eNB and gNB devices I've personally tested with, and fix capitalization of Baseband 6630 while I'm at it :)
> Add tested Ericsson gNodeBs and eNodeBs

- src/upf/context.c
Uplink and Downlink data of URR Usage Report was swapped.
> Fix UL and DL URR Usage Report

- lib/pfcp/types.h
rearranging the dropped dl traffic threshold ie.
> fix dropped_dl_traffic_threshold ie.

- src/amf/gmm-sm.c
In https://github.com/open5gs/open5gs/pull/1923 I accidentally introduced a duplicate CASE statement, sorry. This patch should fix it, thanks.
> [AMF] Fix deletion of auth data from AUSF

- lib/dbi/subscription.c
- lib/proto/types.h
- src/smf/context.c
- src/smf/npcf-build.c
- src/smf/npcf-handler.c
- src/smf/nudm-handler.c
- src/udr/nudr-handler.c
Framed routes are stored in mongo as
```json
{
"imsi" : "$IMSI",
...,
"slice" :
[{
...,
"session" :
...,
"ipv4_framed_routes" : ["10.45.33.0/24", "10.45.35.0/24"],
}],
}],
},
```
> Framed routes udr

- .github/ISSUE_TEMPLATES/bugreport.yaml
- .github/ISSUE_TEMPLATES/config.yaml
- .github/ISSUE_TEMPLATES/feature_request.yaml
Added:
* ISSUE_TEMPLATES with templates for Bugs and Feature Requests
* config.yaml
* Disallows blank issues
* Defines some contact links
> Issue housekeeping

- lib/sbi/nnrf-handler.c
- src/nrf/nnrf-handler.c
This pull request should have also included the following commits:
- [SBI] Added Handler for Subscription PATCH (ad9e5b28cf60ef6548190b6e30bbfc4d393013f1)
But there was a mistake and I missed it.
Anyway, I created this pull request to solve issue #2152.
> NFManagement subscriptions API conform to 3GPP SBI specification

- configs/open5gs/amf.yaml.in
- configs/open5gs/mme.yaml.in
- configs/sample.yaml.in
- lib/proto/types.h
- src/amf/context.c
- src/amf/context.h
- src/amf/gmm-handler.c
- src/mme/emm-handler.c
- src/mme/mme-context.c
- src/mme/mme-context.h
These mechanisms are described in the GSMA roaming guidelines. Chapters called Access Control.
For 4g: https://www.gsma.com/newsroom/wp-content/uploads//IR.88-v21.0.pdf
For 5g: https://www.gsma.com/newsroom/wp-content/uploads//NG.113-v6.0.pdf
> [AMF/MME] PLMN access control

- misc/db/open5gs-dbctl
> Add ambr_speed option, this allow to change the speed value

- docs/_pages/docs.md
- lib/proto/types.h
- src/amf/context.c
- src/amf/context.h
- src/mme/esm-build.c
- src/mme/esm-handler.c
- src/mme/mme-context.c
- src/mme/mme-context.h
- src/mme/mme-s11-build.c
- src/mme/mme-s11-handler.c
- src/smf/context.c
- src/smf/context.h
- src/smf/gsm-build.c
- src/smf/gsm-handler.c
- src/smf/s5c-build.c
- src/smf/s5c-handler.c
- tests/attach/guti-test.c
- tests/attach/simple-test.c
- tests/common/context.h
- tests/common/esm-build.c
MME/PGW also supports Extended Protocol Configuration Options.
> [MME/PGW] Added Extended-PCO in 4G/LTE (#2261)

- lib/sbi/ogs-sbi.h
- src/smf/context.h
- src/smf/n4-handler.c
- tests/registration/paging-test.c
Disable Network triggered service request
while UE triggered service request
(#2294)
> [SMF] Disable Network Service request while ACTIVATING

- docs/_pages/docs.md
SRS Project Documentation was updated.
> Updated SRS 5G SA Tutorial URL

- configs/open5gs/mme.yaml.in
- lib/nas/eps/types.h
- src/mme/meson.build
- src/mme/mme-context.c
- src/mme/mme-context.h
- src/mme/mme-event.c
- src/mme/mme-event.h
- src/mme/mme-gn-build.c
- src/mme/mme-gn-build.h
- src/mme/mme-gn-handler.c
- src/mme/mme-gn-handler.h
- src/mme/mme-gtp-path.c
- src/mme/mme-gtp-path.h
- src/mme/mme-sm.c
- src/mme/s1ap-build.c
- src/mme/s1ap-build.h
- src/mme/s1ap-handler.c
- src/mme/s1ap-handler.h
- src/mme/s1ap-path.c
- src/mme/s1ap-path.h
- src/mme/s1ap-sm.c
Related: https://github.com/open5gs/open5gs/issues/2410
> MME: Initial Gn iface GTPv1C support (Echo & RIM procedures)

- src/mme/s1ap-handler.c
This is a preparation towards adding other handover types in the future.
> mme: s1ap: Split rx HandoverRequired handling based on HandoverType

- webui/src/components/Subscriber/List.js
This will allow the user to search the subscriber either by the IMSI or MSISDN.
> add search with msisdn

- lib/sbi/nghttp2-server.c
Whether or not to send a Setting ACK is determined by the nghttp2 library. Therefore, when nghttp2 informs us that it want to send an SETTING frame with ACK by nghttp2_session_want_write(), we need to call session_send() directly to send it.
> [SBI] nghttp2 SETTING ACK should be sent (#2385)

- lib/core/ogs-tlv-msg.c
- src/sgwc/gtp-path.c
- src/smf/gtp-path.c
See below for details.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59414
> [GTP] gtp_message_fuzz: Abrt in ogs_abort

- lib/gtp/v1/message.c
- lib/gtp/v1/message.h
- lib/gtp/v1/support/gtp1-tlv.py
- lib/gtp/v2/message.c
- lib/gtp/v2/message.h
- lib/gtp/v2/support/gtp-tlv.py
See below for details
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61780#c1
> [TLV] GTP parser crashg from FuzzingLabs

- src/amf/context.c
- src/amf/gmm-handler.c
Cannot convert SUCI in `Not implemented SUPI format [4]`
> [AMF] amf_ue_set_suci: Assertion `suci` (#2567)

- lib/sbi/context.c
- lib/sbi/nnrf-build.c
- lib/sbi/nnrf-path.c
- src/amf/sbi-path.c
- src/ausf/sbi-path.c
- src/nrf/nnrf-handler.c
- src/nrf/sbi-path.c
- src/pcf/sbi-path.c
- src/smf/sbi-path.c
- tests/af/sbi-path.c
The format of subscrCond must be 'oneOf'.
> [SBI] Fixed invalid format of subscrCond (#2630)

- src/mme/sgsap-build.c
- src/mme/sgsap-types.h
Added TAI/ECGI to the SGaAP-MO-CSFB-INDICATION message.
> [MME] SGaAP-MO-CSFB-INDICATION w/ TAI/ECGI (#2664)

- src/smf/gy-path.c
This commit splits filling Requested-Service-Unit, Used-Service-Unit and QoS-Information into their own helper functions for better readibility, and then partially reverts 125740727e558c7604897eda711d4d40f2906239, where lots of AVPs were left out of INITIAL_REQUEST messagesi during the changes made.
After looking through 3GPP TS 32.299 and rfc4006, it seems expected to send Requested-Service-Unit only during INITIAL_REQUEST, and Used-Service-Unit during UPDATE_REQUEST, so that part is kept.
However, I am not able to find clear indications that AVPs such as QoS Information and RAT-Type should not be sent during INITIAL_REQUEST. So, since we have the info, better set it already during INITIAL_REQUEST, since the OCS may want to grant different resources based on that information if available …
> [SMF] Gy: Keep sending extra AVPs in INITIAL_REQUEST

- src/amf/ngap-handler.c
- src/mme/s1ap-handler.c
The MME/AMF can crash when the TAI information received through UplinkNASTransport is different from what was received in the InitialUEMessage.
This is because when building the Registration/Attach Accept, it calls amf/mme_find_served_tai(), and if it can't find the TAI, Open5GS handles it with an assert.
> [AMF/MME] Fixed crash when receiving invalid packet (#2737)

- src/amf/gmm-build.c
- src/mme/emm-handler.c
Fix DST always being set to 0 ("No adjustment for Daylight Saving Time").
Related: 3GPP TS 24.008 § 10.5.3.12
> [MME] [AMF] Set Daylight Saving Time

- lib/core/ogs-pool.h
- src/amf/context.c
- src/mme/mme-context.c
M-TMSI pool release was incorrectly modified and has now been corrected.
> [AMF/MME] Fixed M-TMSI pool release (#2307)

- lib/dbi/ims.c
- lib/dbi/subscription.c
- lib/gtp/v2/path.h
- lib/pfcp/context.c
- lib/sbi/nnrf-handler.c
- src/hss/hss-s6a-path.c
- src/pcf/context.c
- src/pcrf/pcrf-context.c
- src/scp/sbi-path.c
- src/sepp/sbi-path.c
The issues fixed here were identified with clang-tidy static analysis tool.
> Minor fixes

- lib/diameter/s6b/message.h
- src/smf/context.h
- src/smf/gsm-sm.c
- src/smf/s6b-path.c
- src/smf/smf-sm.c
So far the Gy session creation triggered by S2b interface (ePDG) was not implemented. Fix it.
> [SMF] Setup Gy session when creating UE session over S2b interface

- lib/sbi/message.c
- tests/unit/sbi-message-test.c
When building the MIME Multipart Media Encapsulation format within an SBI message in the NF of a third-party product, Open5GS does not parse properly if it contains a Preamble CRLF.
For example,
```
TCP/HTTP2
Stream: Data, Stream ID: 1, Length 841
MIME Multipart Media Encapsulation, Type: multipart/related, Boundary: "gc0pJq08jU534c"
--->Preamble: 0d0a
First boundary: --gc0pJq08jU534c\r\n
Encapsulated multipart part: (application/json)
Boundary: \r\n--gc0pJq08jU534c\r\n
Encapsulated multipart part: (application/vnd.3gpp.5gnas)
Boundary: \r\n--gc0pJq08jU534c\r\n
Encapsulated multipart part: (application/vnd.3gpp.ngap)
Last Boundary: \r\n--gc0pJq08jU534c--\r\n
```
> [SBI] Preamble parsing issues in MIME (#3058)

- lib/crypt/ecc.c
a cryptographic vulnerability in the SUCI decryption routines of Open5GS 5G—specifically Profile B, which uses P-256 (secp256r1) for its elliptic curve routines.
If a mobile device user passes a public key within its SUCI that does not correspond to a valid point on the P-256 elliptic curve, the Open5GS UDM will not check the point
before running elliptic curve operations with it and returning a response to the mobile device user.
If the public key is not checked to be a valid point, an attacker can leverage this behavior to extract the Profile B private key from the UDM, as has been done in other domains
(https://owasp.org/www-pdf-archive/Practical_Invalid_Curve_Attacks_on_TLS-ECDH_-_Juraj_Somorovsky.pdf).
Note that Profile A is not similarly vulnerable to this, as it is impossible to …
> [UDM] Added validation for pubkey

- src/udm/nudm-handler.c
- src/udm/nudm-handler.h
- src/udm/ue-sm.c
Processing of HTTP GET request for Amf3GppAccessRegistration data is enabled (29503 - 5.3.2.5.2)
> [UDM] Added Amf3GppAccessRegistration Information Retrieval Feature

- src/mme/emm-sm.c
- src/mme/mme-gn-build.c
- src/mme/mme-gn-build.h
- src/mme/mme-gn-handler.c
- src/mme/mme-gn-handler.h
- src/mme/mme-gtp-path.c
- src/mme/mme-gtp-path.h
* Remove duplicate ntoh
* Fix GUTI<->RAI/PTMSI mapping
Fixes: #3021
> [RFC] Fixes for Gn SGSN Context messages

- src/smf/binding.c
- src/smf/binding.h
- src/smf/n4-handler.c
Fixes issue seen in https://github.com/open5gs/open5gs/issues/3291
> [SMF]: Issue PFCP session modification request if there are additional flows in RAR

- lib/proto/types.h
- src/smf/s5c-handler.c
- src/smf/smf-sm.c
> Revert "[TFT] Incrase the number of flows 8->16 (#3339)"

- src/nrf/sbi-path.c
This can be used when retrieving a list of registered NRF's and how to connect to them.
> [NRF] Add it's own available services to the NfProfile

- configs/open5gs/mme.yaml.in
- lib/proto/types.c
- lib/proto/types.h
- src/mme/mme-context.c
- src/mme/mme-context.h
- src/mme/mme-fd-path.c
> [MME] Implement HSS Selection process

- src/pcrf/pcrf-init.c
This will be needed once metrics are included.
> [PCRF] Enable ogs_app pollset

- src/mme/sgsap-build.c
Added UE's current TAI and E-CGI to SGsAP-LOCATION-UPDATE-REQUEST message as per TS 29.118 5.2.2.2.1
> [MME] TAI and E_CGI IEs in SGs (#3518)

- src/amf/gmm-sm.c
Added a handler in gmm_state_registered() to process SBI client events for UE context transfer, preventing fatal errors and AMF crashes during Initial Registration.
> [AMF] Fix state machine crash during UE context transfer in REGISTERED state (#3613)

- lib/sbi/conv.c
- lib/sbi/conv.h
- lib/sbi/message.h
- src/nrf/nnrf-handler.c
- Added functionality to parse and validate the plmnList JSON array during a PATCH request.
- Updated the nf_instance structure with new PLMN data from the request.
- Ensured robust error handling for invalid PLMN entries and excessive PLMN counts.
- Responded with appropriate HTTP status codes for success and error scenarios.
> [NRF] Implemented PLMN list update handling in nrf_nnrf_handle_nf_update (#3566)

- src/amf/nsmf-handler.c
When a duplicate PDU session establishment is received, the AMF logs a warning and proceeds to update the SM context via the SBI interface. This process eventually calls amf_nsmf_pdusession_build_create_sm_context(), which uses the SUPI to build the SBI URI header. If the SUPI is NULL, then the header's resource component becomes NULL. This leads to a call to ogs_uridup() that asserts on the NULL value, causing a crash.
This commit adds a check before invoking the SBI update. If the SUPI is NULL, the update is skipped and a warning is logged. This prevents the invalid URI build process and avoids the subsequent crash in ogs_uridup().
> [AMF] Fix crash on duplicate PDU session requests due to NULL SUPI (#3710)

- lib/pfcp/types.c
- lib/pfcp/util.c
Fix Integer overflow in #3841 and stack overflow in #3839, #3847
> [PFCP] Fix stack overflow in node_id and integer overflow in sdf_filter

- src/pcf/sbi-path.c
Added AF type in allowed NF types when PCF advertises to NRF
> [PCF] Add AF in list of allowed NF types for PCF

- docs/_docs/tutorial/07-infoAPI-UE-gNB-session-data.md
- docs/_pages/docs.md
> Doc info api
